pingcap/tiup

Makefile, cmd/root.go, cmd/run.go, pkg/localdata/constant.go
This PR changes the way the profile directory is populated. The new behavior should match the old behavior for the default case.
`TIUP_HOME` was not being propagated correctly because of the order of environment assignment; that's fixed in this PR.
This PR adds DefaultTiupHome and ProfileDirName variables to pkg/localdata/constant.go to allow a build-time ldflags -X flag to set the variable. The Makefile adds EXTRA_LDFLAGS to further support this. This is useful for environments like homebrew where the tiup binary itself should be built to have a default directory outside the home directory of the installing user.
This new behavior can be achieved by executing something like this:
```
make EXTRA_LDFLAGS='-X "github.com/pingcap-incubator/tiup/pkg/localdata.DefaultTiupHome=/usr/local/var/tiu …
```
=> Created and moved some variables to facilitate setting build-time defaults

cmd/root.go, pkg/meta/meta_test.go, pkg/meta/repository.go
This PR includes two changes:
1. mirror flag actually cannot work properly because it take effect after initialization of repo, thus fix it.
2. current version check is somehow too strict, add an another flag for disabling it (temporarily).
=> cmd: fix mirror flag and add a new flag for disabling semver check

components/client/endpoint.go, components/client/main.go
now the compiler complains:
```
components/client/endpoint.go:3:6: exported type Endpoint should have comment or be unexported
```
=> cmd: not export Endpoint to stop compiler's complain

cmd/root.go, components/client/main.go, components/package/main.go, index.html, install.sh, tests/expected/tiup/tiup-help-install.output, tests/expected/tiup/tiup-help.output, tests/expected/tiup/tiup.output
1. fix help doc
2. fix compiler's complain: ```components/package/main.go:189:10: if block ends with a return statement, so drop this else and outdent its block```
3. fix `tiup run playground`
=> cmd: fix help doc and run bug

.gitignore, cmd/root.go, cmd/run.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/tidb.go, components/playground/instance/tikv.go, components/playground/main.go, pkg/meta/meta.go, tests/expected/tiup/tiup-h.output, tests/expected/tiup/tiup-help.output, tests/expected/tiup/tiup.output
UCP https://github.com/pingcap-incubator/tiup/issues/77
Support specifies the binary path when running a component.
it runs like `tiup playground --kv 3 --db 3 --pd 3 --db.binpath /xx/tidb-server --kv.binpath /xx/tikv-server --pd.binpath /xx/pd-server`
Tests 
- Manual test
=> specify component binary path

README.md, cmd/root.go, cmd/run.go, tests/cases.json, tests/expected/tiup/tiup-h.output, tests/expected/tiup/tiup-help.output, tests/expected/tiup/tiup-run-test3.output, tests/expected/tiup/tiup.output
Clean temporary data directory after instance terminated if the `TAG` doesn't specify.
=> cmd: clean temporary data in default

cmd/run.go, components/playground/instance/tikv.go, components/playground/main.go, tests/expected/tiup/tiup-run-test-flag.output, tests/expected/tiup/tiup-run-test-v1.1.1.output, tests/expected/tiup/tiup-run-test.output, tests/expected/tiup/tiup-run-test2.output, tests/expected/tiup/tiup-run-test3.output
* #106 
* #108
* Prevent tikv config from being overwritten
* Gracefully stop `tiup run`
* Process the signal in `playground`
Tests 
* Manual test (add detailed scripts or steps below)
1. sh run.sh
```bash
nohup tiup playground nightly --kv.config=./tikv.toml --db=1 --pd=1 --kv=1 >tiup.log 2>&1 &
echo "$!" > tiup.pid
```
2. sh stop.sh
```bash
kill `cat tiup.pid`
rm -f tiup.pid
```
=> Prevent tikv config from being overwritten and  Gracefully stop

cmd/run.go, tests/expected/tiup/tiup-run-test-flag.output, tests/expected/tiup/tiup-run-test-v1.1.1.output, tests/expected/tiup/tiup-run-test.output, tests/expected/tiup/tiup-run-test2.output, tests/expected/tiup/tiup-run-test3.output
Exit message is redundant and misleading:
```
$ tiup cluster start example
...
Started cluster `example` successfully
Success to stop component `cluster`
```
One can easily misinterprets the message as "success to stop cluster".
Only print error messages.
=> cmd: refine exit message

components/bench/tpcc.go
Signed-off-by: mahjonp <junpeng.man@gmail.com>
The output and tables should be placed inside the prepare subcommand.
```
Usage:
./bench tpcc prepare [flags]
Flags:
-h, --help            help for prepare
--output string   Output directory for generating file if specified
--tables string   Specified tables for generating file, separated by ','. Valid only if output is set. If this flag is not set, generate all tables by default
```
Tests 
```
Manual
```
Code changes
```
None
```
Side effects
```
None
```
```
None
```
=> bench: adjust tpcc prepare flags

components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, pkg/utils/ioutil.go
cluster manager should be a directory rather than a binary.
Tests 
=> Fix TiFlash cluster manager path

Makefile, cmd/clean.go, cmd/cmd_test.go, cmd/help.go, cmd/install.go, cmd/list.go, cmd/root.go, cmd/run.go, cmd/status.go, cmd/uninstall.go, cmd/update.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/main.go, pkg/localdata/profile.go, pkg/meta/meta.go, pkg/repository/version_test.go, tests/expected/tiup/tiup-help-doc.output, tests/expected/tiup/tiup-run-test-v1.1.1.output, tests/expected/tiup/tiup-run-test.output, tests/expected/tiup/tiup-run-test0.output, tests/expected/tiup/tiup-run-test2.output, tests/expected/tiup/tiup-run-test3.output, tests/run.sh
This PR is a step towards making unit tests more unit-y and a better long-term test framework
cc #111
PTAL @lonng 
The first commit refactors the list component so that it can be unit tested without also testing the generic running framework or the table writing code.
The second commit refactors the `profile` and `repo` globals into an `Environment` struct. This removes global, mutable state and will allow for tests to run concurrently using different environments.
Tests 
- Unit test
(existing tests, all work is refactoring)
Code changes
Side effects
none
none
=> Refactoring for better testing

Makefile, tests/run.sh
Previously if tests fail, then we never tidy up failpoints changes, so some changes are left to files, and some files which should be deleted are left in tree.
Closes #98
Change the makefile to run tests recursively rather than directly, thus letting disable failpoints run.
PTAL @lonng
=> Always tidy up after tests, even if tests fail

pkg/repository/keys.go, pkg/repository/manifest.go, pkg/repository/manifest_test.go
cc #201 this is ~~most of~~ the first task in group 2. ~~It is missing serialisation though.~~
PTAL @AstroProfundis 
It seems that we had not been running unit tests due to a bad argument to `go test`, this PR fixes that and adds TODOs where tests need fixing.
=> repository: create some basic manifest infrastructure

.gitignore, Makefile, components/bench/Makefile, components/bench/misc.go, components/bench/tpcc.go, components/bench/tpch.go, doc/user/bench.md, go.mod, go.sum
* Port latest changes in [pingcap/go-tpc](https://github.com/pingcap/go-tpc) to make it more friendly to run a benchmark on TiDB cluster with TiFlash.
* Port latest files in `pingcap/go-tpc` · `cmd/go-tpc` to `components/bench`
* Add Makefile for components/bench
Tests 
Code changes
- None
Side effects
- Need to release a new version of `tiup bench`
=> Update `tiup bench` with more tpch flags

pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go, pkg/repository/v1manifest/manifest.go, pkg/repository/v1manifest/repo.go, pkg/repository/v1manifest/types.go
implement update root
Seems we should VerifySignature according to the threshold of the manifest type but not just all signatures?
Also we should update the keys of `LocalRoot` when we get or save a new root manifest
=> implement update root

pkg/repository/v1manifest/local_manifests.go, pkg/repository/v1manifest/types.go
Init keys of the FsManifests
ms.keys is never set before and will be used to check the signature of manifests.
=> Init keys of the FsManifests

cmd/repo.go, pkg/repository/crypto/keys.go, pkg/repository/v1manifest/repo.go
This PR introduce a sub command:
```
tiup repo sign <manifest-file> [key1] [key2]
```
It will append signature to the manifest file
Tests 
```
cat /tmp/repo/timestamp.json
tiup repo init /tmp/repo -i /tmp/keys
tiup repo sign /tmp/repo/timestamp.json /tmp/keys/*-root.json
cat /tmp/repo/timestamp.json
```
Code changes
Side effects
=> Support `repo sign` subcommand for manually sign

pkg/repository/file_source.go, pkg/repository/mirror.go, pkg/repository/v1manifest/repo.go, pkg/utils/ioutil.go
When downloading tarball, it fails to decompress
There was a `FIXME` comment that suggests to store downloaded files in memory other than files to reduce disk IO, but after fixing that, the behavior of handling tarballs are not correct.
In `pkg/repository/file_source.go`, we check file hash before decompress it, so the returned reader was read twice if `expand` is true, the 2nd read can only get `EOF`. There is a `Seek()` call to reset the offset before decompressing, however, this only works for `os.File`, but not other reader types.
This PR partially revert #213 and changed the process back to storing downloaded files on disk in a temp dir. (This also avoids the risk that downloading large file may lead to too much memory usage)
Tests 
- Unit test
- Manual test (add detailed scripts or …
=> repository: fix tarball downloading

pkg/repository/v1manifest/manifest.go
Reject duplicate key id signatures
protect giving a duplicate signature to bypass threshold
=> Reject duplicate key id signatures

pkg/repository/mirror.go
Fix panic when passing a maxSize less than the file size.
err is nil here
=> Fix panic when passing a maxSize less than the file size.

cmd/repo.go, go.mod, go.sum, pkg/repository/v1manifest/manifest.go, pkg/repository/v1manifest/repo.go, pkg/repository/v1manifest/types.go, tools/migrate/main.go
Make the `migrate` tool being able to migrate a v0 repo to v1 format manually.
Not generating root keys when running `migrate new`, and the `root.json` generated by `migrate` is kept unsigned.
Holders of root keys can then sign the `root.json` in private, and send back their dedicated signed `root.json` to the server.
On server, use `migrate update` sub sommand to join those signatures and update the repository.
Tests 
- Unit test
```
tiup mirrors repov0 -f --arch amd64,arm64
migrate new repov0 repov1
tiup repo genkey --save # the key is saved at CWD
tiup repo sign repov1/manifests/root.json
migrate update repov1 <a-signed-root.json> [b-signed-root.json ...]
```
Code changes
- Has exported …
=> tools: manual migrate a v0 repo to v1 format

cmd/help.go, cmd/root.go, cmd/run.go, pkg/localdata/profile.go, pkg/meta/meta.go, pkg/repository/v1_repository.go, pkg/repository/v1manifest/local_manifests.go, pkg/repository/v1manifest/types.go
Make run components works for v1
test (see #245 for what is `tt` here)
```
➜  tiup git:(check_com) ✗ tt tidb
The component `tidb` is not installed; downloading from repository.
Starting component `tidb`: /Users/huangjiahao/code/tiup/testprofile/components/tidb/master/tidb-server
[2020/05/24 23:14:20.712 +08:00] [INFO] [printer.go:41] ["Welcome to TiDB."] ["Release Version"=v4.0.0-beta-447-gad63c03e50] ["Git Commit Hash"=ad63c03e5090e9fed17d39e05938630f895a53b1] ["Git Branch"=HEAD] ["UTC Build Time"="2020-03-18 12:07:57"] [GoVersion=go1.13.4] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=v3.0.0-60965b006877ca7234adaced7890d7b029ed1306]
[2020/05/24 23:14:20.713 +08:00] [INFO] [printer.go:54] ["loaded config"] …
```
=> Make run components works for v1

cmd/repo.go, pkg/repository/v1manifest/repo.go
Save keyinfo files with `0600` if it contains private key
Check if the `KeyInfo` contains private key block before saving it to disk
Tests 
Code changes
Side effects
- N/A
- N/A
=> manifest: save private key with 0600 permission

cmd/repo.go, doc/design/manifest.md, pkg/repository/v1manifest/types.go, tools/migrate/main.go
Add basic support of "nightly" versions to manifest definition and the migrate tool
- Add a "nightly" section to component manifest, that points to the latest daily build
- Add support of migrating nightly builds from v0 manifest
Tests 
Code changes
Side effects
=> *: add basic support of nightly versions

cmd/clean.go, cmd/run.go, cmd/status.go, doc/design/manifest.md, pkg/localdata/profile.go, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go, pkg/repository/v1manifest/key_store.go, pkg/repository/v1manifest/local_manifests.go, pkg/repository/v1manifest/manifest.go
This PR is a bit of a bag of different things I found while checking we were properly doing signature and hash verification. It includes:
* Handling verification of expired root manifests by checking keys for expiry when they are used, not when loaded.
* Make `ReadJSON` in `Profile` private to reduce the surface area of json decoding. I have checked that every place where we decode JSON verifies the result if necessary. I created a `ReadMetaFile` function to accomplish this, I think it is a good abstraction in any case.
* Removed some mention of `sha512` hashes which we do not support.
* Removed the unused `DownloadComponent` from `v1Repository`
* Removed an unnecessary reload of the root manifest in `ensureManifests`, this was a mistake from a previous PR (whoops).
PTAL @lucklove …
=> Misc security fixes and tidying up for v1 manifests

pkg/repository/v1manifest/manifest.go
Extend the expire time to 1 month
Extend the expire time of snapshot and timestamp to 1mon, we'll need to change them back to 24 hours when everything is stable
Tests 
- Unit test
- No code
Code changes
Side effects
=> manifest: extend the expire time of snapshot and timestamp

pkg/meta/meta.go, pkg/repository/v0manifest/version.go, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go, pkg/repository/v1manifest/types.go
=> Support nightly

doc/design/manifest.md, pkg/repository/v1_repository_test.go, pkg/repository/v1manifest/repo.go, pkg/repository/v1manifest/types.go, tools/migrate/main.go
I think we should not have both name and id, it is confusing and has potential for errors where one is required but the other is used.
PTAL @lonng
=> Remove name field from component manifest

pkg/repository/clone_mirror.go, pkg/repository/hash.go, pkg/repository/v1manifest/keys.go, pkg/repository/v1manifest/repo.go, tools/migrate/main.go
Update an exist repo (generated by `migrate new`) without regenerating root.json and keys.
This is useful when some of the files in repository has changed, or when the v0 manifest has changed, but there is already a v1 repository generated and it's not convenient to resign the `root.json` with keys held by different individuals.
Add a `migrate rehash` command, it reads the `root.json` and `index.json` and then find keys for other manifests. Then it performs operations similar as `migrate new` but without generating new keys.
Tests 
Code changes
Side effects
=> tools/migrate: add function to rehash tarballs and update with existing keys

pkg/meta/meta.go, pkg/repository/progress.go, pkg/repository/v1_repository.go
```
download http://172.16.5.134:8989/pd-nightly-linux-amd64.tar.gz 37.35 MiB / 37.36 MiB 99.99% 993.56 KiB p/s
download http://172.16.5.134:8989/tidb-nightly-linux-amd64.tar.gz 41.06 MiB / 41.06 MiB 99.99% 885.73 KiB p/s
download http://172.16.5.134:8989/tikv-nightly-linux-amd64.tar.gz 131.15 MiB / 131.15 MiB 100.00% 927.64 KiB p/s
Error: the component `mirrors` does not have a nightly version; skipped
the component `playground` does not have a nightly version; skipped
```
Don't report errors if some components don't have a nightly version.
=> Don't report errors if some components don't have a nightly version.

pkg/repository/v1manifest/manifest.go, tools/migrate/main.go
The version and expire time of `index.json` is not correctly set on update. Also fixes wrong expire time of `snapshot.json`.
Update values for exist manifests
Tests 
Code changes
=> tools/migrate: fix version and expire time of updated manfiests

pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go
Don't report error when installing exists version.
```
➜  tiup git:(verbose-list) tiup install tidb:v3.0.11 tikv:nightly pd:v4.0.0-rc.1
download http://172.16.5.134:8989/pd-v4.0.0-rc.1-darwin-amd64.tar.gz 37.88 MiB / 37.88 MiB 100.00% 7.59 MiB p/s                                                                                            
Error: component tidb version v3.0.11 is already installed
component tikv version nightly is already installed
➜  tiup git:(verbose-list) git branch -b verbose-list  
```
Tests 
```
➜  tiup git:(fix-install) ✗ tiup install tidb:v3.0.11 tikv:nightly pd:v4.0.0-rc.1
component tidb version v3.0.11 is already installed
component tikv version nightly is already installed …
```
=> Don't report error when installing exists version

cmd/mirror.go, pkg/meta/meta.go, pkg/repository/mirror.go, pkg/repository/v1_repository.go
attach the mirror source information into the error message.
```
➜  tiup git:(attach-mirror-addr) ✗ tiup list
Error: read manifest from mirror(/c/devel/pingcap/tiup/localpath) failed: not enough signatures (0) for threshold 1 in timestamp.json
```
=> attach the mirror source information into error message

go.mod, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go
problem in origin branch problem:
- the local contains only root.json
- run into ensureManifest()
- failed at `r.updateLocalRoot`
- the local contains root.json timestamp.json, snapshot.json
- run ensureManifest() again()
* r.updateLocalSnapshot return nil, nil
* ensureManifest just return false and nil, but local still have not index.json
this pr make it always check local index exists and update it if the version < the version in snapshot
the origin implementation also can not make sure snapshot exist in `ensureManifest` if it save the timestamp but failed to save the snapshot. then the later call will not update snapshot unless the hash of snapshot in timestamp is changed
=> ensureManifest truely ensure index exist

Makefile, cmd/cmd_test.go, cmd/help.go, cmd/list.go, cmd/root.go, cmd/telemetry.go, components/bench/main.go, components/bench/tpcc.go, components/client/main.go, components/playground/main.go, tools/migrate/main.go
upgrade golang-ci and enable all default linter.
you may need to delete `tools/bin/golangci-lint` for it to reinstall the new version one.
=> upgrade golang-ci and enable all default linter.

cmd/mirror.go, pkg/repository/clone_mirror.go
`tiup mirror clone <target-dir> [global version] [flags]` will download versions that matching specific version prefix.
`tiup mirror clone <target-dir> [global version] [flags]` will download versions that match exactly by default. Users can use `--prefix` option to download versions that matching prefix if they want.
Tests 
```
tiup mirror clone package v4.0.0 --os=linux --prefix
tiup mirror clone package v4.0.0 --os=linux 
```
=> Add --prefix option for tiup mirror clone

cmd/list.go, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go
Persistent the snapshot first and prevent the snapshot.json/timestamp.json inconsistently
1. timestamp.json will fetch every time
2. saved timestamp.json and crash before saving snapshot.json will cause snapshot.json doesn't be updated anymore
This PR saves snopshot.json before saving timestamp.json.
In addition, this PR optimizes the `tiup list` and reduce the duplicated fetch timestamp.json and snapshot.json.
=> Save snopshot.json before saving timestamp.json

cmd/list.go, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go, pkg/repository/v1manifest/local_manifests.go, pkg/repository/v1manifest/manifest.go, server/store/qcloud.go
The `snapshot.json` is not always checked to be the latest, if an operation interrupted before, there might be a new `timestamp.json` and an old `snapshot.json`, and the `snapshot.json` is not been updated before next time the `timestamp.json` is updated.
1. force checking hash of `snapshot.json` every time `timestamp.json` is fetched, no matter it is updated or not, to ensure local cached `snapshot.json` matches the version in `timestamp.json`
2. use `cjson.Marshal` instead of `cjson.Encoder` when writing files, to avoid newline at the end of file
Tests 
Code changes
Side effects
- Need to cherry-pick to the …
=> *: fix manifest update

.gitignore, components/cluster/command/display.go, pkg/cluster/api/pdapi.go, pkg/cluster/meta/topology.go
Show dashboard node status even that node is abnormal.
Get the dashboard address from all PD nodes instead of the node self, because when the node is down, it can't return the response.
Tests 
- Run a cluster with 3 PD nodes
- Kill the PD node which runs the dashboard
- Run `tiup cluster display clusterName` to see the nodes status
Side effects
=> Fix dashboard address

server/main.go, server/router.go, server/server.go, server/static.go, server/store/qcloud.go, server/store/qcloud_test.go, server/store/store.go
When we want to build a test mirror, we have to clone all manifests and tarballs which
waste a lot of time. This PR introduces a COW(copy-on-write) way to do this. We can
build an empty mirror and set upstream as https://tiup-mirrors.pingcap.com (the official mirror).
When requests to the test mirror, it will try to find files locally, if failed, it will fetches the upstream.
=> Support upstream in tiup-server

go.mod, go.sum, pkg/repository/v1_repository_test.go, pkg/utils/ioutil.go
When importing ansible deployed clusters, as "is a directory" error is reported and the process aborted. It does not broke the cluster from using, just the ansible directory remains where it is and not moved to the hidden profile directory.
This was introduced in #225 
Check if `src` is a directory and use `copy.Copy()` to copy it recursively.
Tests 
- Unit test
Code changes
Side effects
=> cluster/import: fix copying directory

cmd/list.go
This PR adds release time and platforms for nightly.
Before this PR, this nightly release and platforms is empty:
```
JoshuadeMacBook-Pro:tidb-foresight joshua$ tiup list ctl
Available versions for ctl:
Version      Installed  Release                    Platforms
-------      ---------  -------                    ---------
nightly
v3.0.1                  2020-04-27T19:39:08+08:00  darwin/amd64,linux/amd64,linux/arm64
```
After this PR, it will show the latest nightly version info:
```
JoshuadeMacBook-Pro:tidb-foresight joshua$ tiup list ctl
Available versions for ctl:
Version      Installed  Release                    Platforms
-------      ---------  -------                    ---------
nightly                 2020-06-03T21:20:01+08:00 …
```
=> Add nightly release time and platorms in list command

cmd/mirror.go, pkg/repository/remote/upload.go
The command `tiup mirror publish` need a flag --repo to specific the remote tiup-server. However, in real use the remote server address will be the mirror address, so we make them same in flag default options
=> Publish: use mirror address as default endpoint

cmd/mirror.go, pkg/repository/remote/upload.go, server/handler/component.go, server/handler/error.go, server/handler/tarball.go, server/model/model.go
Manifests are not renewed when updating via server
Reset expire time of manifests based on the time it is updated
Tests 
- Unit test
Code changes
Side effects
=> server: renew manifests on update

pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go
Fix #444 
Report a warning when updating non-exist components instead of returning an error.
=> Report a warning when updating non-exist components

components/playground/playground.go
fail to start without monitor cause monitor is nil.
introduced by https://github.com/pingcap/tiup/pull/431
but we have not released any version having this issue.
=> don't generate config file of prometheus if we don't start it

pkg/repository/v1_repository.go
The cluster component can't deploy nightly version since the
ComponentVersion method of V1Repository tries to find "nightly"
directly in component manifests. It should read the field nightly
and redirect to the real nightly version.
=> Fix `cluster deploy xxx nightly`

README.md
The link in `README.md` pointing to the dev doc is not correct.
Corrects the link.
Tests 
- No code
=> Fix a dead link in README.md

components/cluster/command/deploy.go, components/cluster/command/destroy.go, components/cluster/command/display.go, components/cluster/command/edit_config.go, components/cluster/command/exec.go, components/cluster/command/patch.go, components/cluster/command/reload.go, components/cluster/command/restart.go, components/cluster/command/root.go, components/cluster/command/scale_in.go, components/cluster/command/scale_out.go, components/cluster/command/start.go, components/cluster/command/stop.go, components/cluster/command/upgrade.go
remove args in Command.
the default will be the command names join by space, and the specified command run can append more args if need.
currently, all cluster name is hash, and the version is appended raw.
example: "command":"cluster start cluster_0cc175b9c0f1b6a831c399e269772661"
=> Remove args in Command

pkg/cluster/meta/topology.go
resolve a part of #472 
Enlarge the PD API query timeout duration from 2 seconds to 10 seconds, because when there are some PD nodes are down, the `/pd/health` API will usually cost more than 2 seconds.
Before:
After:
Tests 
=> enlarge the pd api timeout time to fix the pd nodes statuses are not stable

cmd/root.go
Fix https://github.com/pingcap/tiup/issues/151
1. Fix the bug that `--help` can't locate component.
2. If no arg is specified (`tiup --version`), print tiup version directly.
3. If component is specified(`tiup cluster --version`), use `--version` as an argument for this component.
Tests 
- Unit test
- No code
Code changes
Side effects
=> fix help bug and add version flag for tiup

components/cluster/command/display.go, pkg/cluster/meta/topology.go
The raw store state returned from TiKV is misleading, the "offline" is a state that the store is being transferred to other node and "tombstone" is when the offline is really complete.
There is risk that user misunderstand the meaning of "Offline" and use `--force` arg to scale in other instances in the cluster, which may lead to data loss.
Set the displayed state to "Pending Offline" for better understanding.
=> display: update state displaying for offline tikv node

pkg/cluster/executor/ssh.go
We use string matching to check for command outputs at several places, and that might fail if the user's deploy server is not using an English locale.
Force all SSH commands to be executed with `LANG=C` environment variable set.
=> executor/ssh: force using C locale for commands

pkg/environment/env.go, pkg/repository/mirror.go, pkg/repository/v1_repository.go, pkg/verbose/verbose.go
Fix #485 
Support output verbose log for debugging.
```
➜  tiup git:(verbose-log) TIUP_VERBOSE=1 bin/tiup list
Verbose: Initialize repository finished in 1.6469ms
Verbose: Download resource https://tiup-mirrors.pingcap.com/timestamp.json in 308.4553ms
Verbose: Fetch timestamp finished in 309.4367ms
Verbose: Download resource https://tiup-mirrors.pingcap.com/snapshot.json in 251.293ms
Verbose: Update local snapshot finished in 565.8799ms
Verbose: Download resource https://tiup-mirrors.pingcap.com/2.root.json in 261.1945ms
Verbose: Update local root finished in 262.4301ms
Verbose: Update local index finished in 491.3µs
Verbose: Ensure manifests finished in 830.36ms
Verbose: Initialize repository finished in 1.2396ms
Verbose: Download resource …
```
=> Support output verbose log for debugging

pkg/repository/remote/upload.go
We should only keep one nightly version in
manifest to avoid lengthy manifest files
=> Remove history nightly version in manifests

go.mod, go.sum, pkg/cluster/meta/bindversion.go
Update bindversion of insight, the latest version disables tidb version check, which is not needed in tiup
=> cluster/check: update version of insight collector

components/playground/instance/pd.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/playground.go
fix #418 #419 #421
in #430, we just stop the process whatever, that ok for non-stateful component, this PR handle scale in of kv/pd/flash gracefully.
kv example:
pd example:
not having test tiflash cause it support mac now, but should be same as kv.
will test it when finally all issues in [playground refactor](https://github.com/pingcap/tiup/projects/6) done.
=> Handle scale in of kv/pd/flash in playground

components/playground/grafana.go, components/playground/grafana_test.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/main.go, components/playground/monitor.go, components/playground/playground.go
fix #417
Support grafana and the build in dashboard when enable monitor
also, run prometheus with the specified version cause we bind it as the same version of tidb.
```
➜  playground git:(grafana) ✗ tp --monitor
Starting component `playground`: /Users/huangjiahao/code/tiup/components/playground/playground --monitor
Playground Bootstrapping...
Starting component `prometheus`: /Users/huangjiahao/.tiup/components/prometheus/v4.0.0/prometheus/prometheus --config.file=/Users/huangjiahao/.tiup/data/S1UWrQO/prometheus/prometheus.yml --web.external-url=http://127.0.0.1:9090 --web.listen-address=0.0.0.0:9090 --storage.tsdb.path='/Users/huangjiahao/.tiup/data/S1UWrQO/prometheus/data'
start grafana:  tiup grafana --homepath /Users/huangjiahao/.tiup/data/S1UWrQO/grafana --config …
```
=> Support grafana and the build in dashboard when enable monitor

cmd/mirror.go, components/cluster/command/scale_in.go
move init mirror to preRun for `tiup mirror clone`. tiup --help and --version commands (expect `tiup mirror clone --help`) don't need init environment and connect to network any more.
Don't parse args for `tiup mirror clone` at beginning. Do it in running progress.
Tests 
- Unit test
- No code
Code changes
Side effects
=> move init mirror to preRun for `tiup mirror clone`

components/playground/command.go, components/playground/instance/drainer.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/pump.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/main.go, components/playground/playground.go
fix #422 
this pr also fix the issue when --host is set as "0.0.0.0".
according to the doc:https://pingcap.com/docs-cn/dev/tiup/tiup-playground/
```
--host string              设置每个组件的监听地址（默认为 127.0.0.1），如果要提供给别的电脑访问，可设置为 0.0.0.0
```
this actually can't work cause many advertise addr also use "0.0.0.0:<port>"
Note the default config of drainer is replicate to 127.0.0.1:3306, user must set up the downstream itself or provide the custom config for drainer, or drainer will fail to run.
usage example:
run MySQL local at port 3306.
start a playground with:
- tp --pump 3 --drainer 1
check the replication works
in another terminal
- scale-in one pump
- scale-in one drainer
- scale-out one pump
- scale-out one drainer
=> Support pump&drainer in playground

components/cluster/command/display.go, components/dms/command/display.go, pkg/cluster/api/pdapi.go, pkg/cluster/meta/topology.go
Resolve a part of #472 
Currently, the "Unhealthy" PD node is recognized as "Down" status, and the "Unhealthy" status never displays.
Differ the "Down" and "Unhealthy" status for PD node, when all nodes don't work, recognize them as "Down", else recognize the not work node as "Unhealthy".
Tests 
Deploy a cluster with 3 PD nodes, pause 1 node.
Before:
After:
Pause 2 PD nodes:
=> Simplify PD node status

pkg/cluster/meta/drainer.go, pkg/cluster/meta/logic.go, pkg/cluster/meta/logic_dm.go, pkg/cluster/meta/pump.go, pkg/cluster/meta/server_config.go, pkg/cluster/meta/topology_test.go
The tiup config should always have higher priority
than tiup-ansible ones.
This PR gives tiup config higher priority than imported tidb-ansible config to reduce
the confusion.
I changed the merge methods and let it accept more than one overwrites, it will overwrite the orig with the overwrites one by one, so the latter overwrites have higher priority.
Tests 
- Unit test
=> Reorder imported config priority

pkg/cluster/executor/ssh.go
If the command is executed without shell, the PATH might be empty.
Fix the order of setting LANG and PATH values
Tests 
=> executor/ssh: fix PATH for non-shell executors

pkg/cluster/clusterutil/clusterutil.go, pkg/cluster/clusterutil/clusterutil_test.go, pkg/cluster/task/mkdir.go
When the user specifies a directory which contains lots of content (200GB for example) as log/data directory, the chown -R command will wait a long time to timeout.
`chown -R` -> `chown`
=> Fix timeout when target directory exists and there is lots of content

pkg/cluster/template/scripts/pd.go, tests/tiup-cluster/script/cmd_subtest.sh, tests/tiup-cluster/test_cmd.sh
https://github.com/pingcap/tiup/issues/517
Tiup cluster scale-out pd will fail because scale-out generates wrong run_pd.sh in scale stage.
I changed it to the correct one
Tests 
=> Enable intergrate test & Fix scale-out pd

components/playground/command.go, components/playground/instance/drainer.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/process.go, components/playground/instance/pump.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/main.go, components/playground/playground.go, components/playground/utils/utils.go
1. redirect std output to the log file, only print the latest 10 lines of
output form log file if the instance quit abnormally.  maybe fix https://github.com/pingcap/tiup/issues/342
2. make the scale-in/scale-out/display not hidden and improve help
message.
3. enable monitor default. fix #491 
4. add uptime in display
example of 1:
example of 4:
=> Redirect std output to log file

components/ctl/main.go
`tiup ctl cdc` won't work since the command contains a space in `cdc cli`, the system will identify them as an indivisible whole.
Split command by space.
=> Fix cdc cli

components/playground/main.go, components/playground/playground.go, pkg/cluster/operation/operation.go, pkg/utils/mock/mock.go
After all tiflash mac binary are updated to tiup mirror, this PR will be safe to test & merge.
enable playground to use tiflash component on mac by default.
Tests 
=> Enable playground TiFlash component on Mac

components/playground/grafana.go, components/playground/monitor.go
fix #534  also, for Prometheus, listen on the specified host.
we call GetFreePort with the specified host.
Note that we can listen on both "0.0.0.0" and some specified ip like "127.0.0.1"
=> Fix custom config of grafana

components/playground/instance/tiflash.go
Should use service port instead of `Port`
test:
=> Fix scale-in of tiflash in playground

Makefile
In GNU make, the first goal becomes the default.
so the default goal is build_integration_test in tests/Makefile
when run `make`
=> Change the default goal in makefile

pkg/cluster/spec/server_config.go
The scale-in process doesn't need to check config at all. But it still fails when other errors in the config check stage threw.
All errors  in the config check stage should be config check error
=> Fix init config with check config

components/cluster/command/root.go, pkg/cluster/module/systemd.go, pkg/cluster/operation/action.go, pkg/cluster/operation/scale_in.go, pkg/cluster/operation/upgrade.go
The systemd module uses a hard-coded 100s timeout and ignores the `--wait-timeout` global argument.
Properly pass the value of `--wait-timeout` to systemd module, so that the SSH execute timeout of `systemctl` operations has the timeout specified with `--wait-timeout`.
Tests 
Code changes
Side effects
=> cluster: properly pass --wait-timeout to systemd operations

components/ctl/main.go
=> Fix the bug that ctl working directory is different with TiUP

components/cluster/command/reload.go, components/cluster/command/root_test.go, components/cluster/command/scale_out.go, components/cluster/command/scale_out_test.go, components/cluster/command/upgrade.go, components/cluster/command/upgrade_test.go
`imported: true` is not allowed for scale out instances, currently we check that when building scale out tasks, this might be too late for some circumstances, this PR move that check to an early stage of the process, to let it fail ASAP.
Move the check to an early stage of the process.
Tests 
Code changes
Side effects
=> cluster/scale-out: check for imported field earlier

pkg/cluster/api/pdapi.go
When deleting some identity from the cluster via PD API, it's ok to ignore not found error, as that's what we want. This would make it easier to keep `scale-in` operation idempotent.
Check for PD API response and ignore not found errors.
Tests 
- Unit test
Code changes
=> cluster: ignore not found error when deleting something via PD API

cmd/completion.go, cmd/root.go
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Fixes #73 
Add a `tiup completion [bash | zsh]` command. 
Tests 
- Unit test
- No code
Code changes
Side effects
=> Support bash and zsh completion

cmd/mirror.go, pkg/repository/remote/modify.go, pkg/repository/v1manifest/manifest.go, pkg/repository/v1manifest/types_test.go, tests/tiup/tiup.toml
At this time tiup only supports yank a whole component (include all versions). 
In some scenes, we should yank a single version (for example, we push a wrong version).
This PR makes it possible to yank a single version.
=> Support yank a single version on client side

components/cluster/command/edit_config.go
Add help msg of EDITOR
```
➜  tiup git:(editor) ✗ ./bin/tiup-cluster edit-config -h
Edit TiDB cluster config.
Will use editor from environment variable `EDITOR`, default use vi
Usage:
tiup-cluster edit-config <cluster-name> [flags]
Flags:
-h, --help   help for edit-config
Global Flags:
--ssh-timeout int    Timeout in seconds to connect host via SSH, ignored for operations that don't need an SSH connection. (default 5)
--wait-timeout int   Timeout in seconds to wait for an operation to complete, ignored for operations that don't fit. (default 120)
-y, --yes                Skip all confirmations and assumes 'yes'
```
=> Add help msg of EDITOR

pkg/cluster/ansible/dirs.go, pkg/cluster/ansible/dirs_test.go
fix #611
import command will only get data_dir from inventory.ini and start
script of tiflash and the start script contains the only config file
flag, so it can not get the truly use path and use the default value.
parse the config file of tiflash to get `path` and `tmp_path` and set it in `DataDir` and `TmpDir` in spec.
- unit-test
- manual-test
* test using import command and check the spec.
=> Fix data_dir of tiflash when import cluster

components/cluster/command/edit_config.go, components/dm/command/edit_config.go, go.mod, go.sum, pkg/cluster/edit/diff.go, pkg/cluster/edit/diff_test.go, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/cdc.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/pd.go, pkg/cluster/spec/prometheus.go, pkg/cluster/spec/pump.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tidb.go, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/tikv.go, pkg/cluster/spec/tispark.go, pkg/dm/spec/topology_dm.go, pkg/meta/resource_ctrl.go, pkg/repository/v1manifest/types_test.go, pkg/utils/diff.go, pkg/utils/diff_test.go, pkg/utils/edit.go
add validation for topology diff to forbid changes of immutable fields
Tests 
- Unit test
Code changes
Side effects
=> cluster: validate topo changes after edit-config

components/cluster/command/edit_config.go, pkg/cliutil/tui.go
In `edit-config`, if the new topology fails parsing or validation, it just returns error and exists, changes are not saved and lost.
Prompt the user to choose to continue editing or not.
Tests 
Code changes
=> cluster: allow continue editing when new topology has errors

components/cluster/command/reload.go, tests/tiup-cluster/script/scale_core.sh
Support refresh configuration only when reload
Tests 
- No code
=> Support refresh configuration only when reload

components/cluster/command/reload.go
Fix https://github.com/pingcap/tiup/issues/628
=> Refresh monitor configs on reload

components/cluster/command/check.go, components/cluster/command/deploy.go, components/cluster/command/scale_out.go
Support posix style argument for --user"
```
$ tiup cluster deploy -uroot
```
=> Support posix style argument for --user"

go.mod, go.sum, pkg/cluster/api/pdapi.go
Fix #637 
Fix PD config incompatible when retrieving dashboard address
Manual test:
```
➜  tiup git:(pr/638) bin/tiup-cluster display simple
TiDB Cluster: simple
TiDB Version: v4.0.3
ID                     Role  Host             Ports        OS/Arch       Status  Data Dir  Deploy Dir
--                     ----  ----             -----        -------       ------  --------  ----------
192.168.137.101:2379   pd    192.168.137.101  2379/2380    linux/x86_64  Up      data      deploy/pd-2379
192.168.137.102:2379   pd    192.168.137.102  2379/2380    linux/x86_64  Up|L    data      deploy/pd-2379
192.168.137.103:2379   pd    192.168.137.103  2379/2380    linux/x86_64  Up|UI   data      deploy/pd-2379
192.168.137.101:4000   tidb  192.168.137.101  4000/10080 …
```
=> Fix PD config incompatible when retrieving dashboard address

pkg/exec/run.go
The following hint is weired.
```
root@control:/tiup-cluster# tiup tidb:nightly
The component `tidb` is not installed; downloading from repository.
download https://tiup-mirrors.pingcap.com/tidb-v5.0.0-nightly-20200729-linux-amd64.tar.gz 42.07 MiB / 42.07 MiB 100.00% 7.34 MiB p/s
Found tidb newer version:
The latest version:         v4.0.3
Local installed version:    nightly
Update current component:   tiup update tidb
Update all components:      tiup update --all
Starting component `tidb`: /root/.tiup/components/tidb/nightly/tidb-server
[2020/07/29 07:11:43.278 +00:00] [INFO] [printer.go:33] ["Welcome to TiDB."] ["Release Version"=v4.0.0-beta.2-852-g1e7454c81] [Edition=Community] ["Git Commit Hash"=1e7454c81d1f4fae464e835d1a4023a911cfa87b] ["Git …
```
=> Dont hint user to update component when user specify version

Makefile, components/dm/command/deploy.go, components/dm/command/deploy_test.go
pre-check the deploy version must not less than v2.0
```
root@control:/tiup-cluster# tiup-dm --yes deploy  testa v1.0 ./tests/tiup-dm/topo/full_dm.yaml -i ~/.ssh/id_rsa
Error: Only support version not less than v2.0
Verbose debug logs has been written to
/tiup-cluster/logs/tiup-cluster-debug-2020-07-30-10-28-13.log.
```
=> Pre-check deploy version of dm

pkg/cluster/spec/tikv.go
Fix https://github.com/pingcap/tiup/issues/661
=> Skip evict store when only 1 tikv

.github/workflows/install.yaml, pkg/environment/env.go, pkg/repository/clone_mirror.go
Fix https://github.com/pingcap/tiup/issues/658
=> Fix tiup update --self with offline package

.github/workflows/integrate.yaml, components/cluster/command/clean.go, components/cluster/command/destroy.go, components/cluster/command/root.go, components/cluster/command/test.go, pkg/cluster/manager.go, pkg/cluster/operation/destroy.go, pkg/cluster/operation/operation.go, tests/tiup-cluster/script/cmd_subtest.sh, tests/tiup-dm/test_cmd.sh
Fix https://github.com/pingcap/tiup/issues/138
TODOLIST:
=> Add clean sub command

pkg/cluster/operation/destroy.go, pkg/cluster/spec/instance.go
ref: https://github.com/pingcap-incubator/tiup-cluster/pull/350
Remove WaitForDown when destroy and clean
Tests 
Release notes:
```release-note
NONE
```
=> don't wait the listen port disappear when destroy and clean

pkg/exec/run.go
Do not change the run component's wd
Tests 
before: (main.go exist in the current directory)
```
root@control:/tiup-cluster# tiup dmctl:nightly --config ./main.go
Starting component `dmctl`: /root/.tiup/components/dmctl/nightly/dmctl/dmctl --config ./main.go
parse cmd flags err: open ./main.go: no such file or directory
```
after:
```
root@control:/tiup-cluster# tiup dmctl:nightly --config ./main.go
Starting component `dmctl`: /root/.tiup/components/dmctl/nightly/dmctl/dmctl --config ./main.go
parse cmd flags err: Near line 0 (last key parsed ''): bare keys cannot contain '/'
Error: run `/root/.tiup/components/dmctl/nightly/dmctl/dmctl` (wd:) failed: exit status 2
```
Release notes:
```release-note
NONE
```
=> Do not change the run component's wd

docker/control/bashrc, pkg/cluster/task/install_package.go
fix #680
also, init the tiup env so we can use `tiup-cluster` directly in the control node
Annotate the err for more direct error reason.
for why scp failed like no disk or no privilege can not know now, this may need to improve the third pkg, but the current annotate is enough for user to find out the reason.
Tests 
using a 
before:
after:
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> More clear error msg when fail copy file

components/dm/spec/alertmanager.go, components/dm/spec/grafana.go, components/dm/spec/prometheus.go, pkg/cluster/manager.go
when reload or scale the altermanager.yml will be overwritten. 
never overwrite altermanager.yml, only init the example config when deploying the instance.
also, handle the custom deploying an instant in upgrade and scale-out
Tests 
deploy a cluster and update the config -> try reload -> check config file not overwritten
```release-note
NONE
```
=> Do not overwrite alertmanager.yml for dm when InitConfig

go.mod, go.sum, pkg/cluster/ansible/import.go, pkg/cluster/ansible/import_test.go, pkg/cluster/ansible/test-data/inventory.ini, pkg/cluster/ansible/test-data/meta.yaml
The global `deploy_dir` is not set during the process of importing from ansible deployed cluster, however, as we detect and set deploy dir for each instance individually, this only affect monitoring agents (node_exporter and blackbox_exporter).
Read the value of `deploy_dir` in `inventory.ini` and set it to `global.deploy_dir` and `monitored.deploy_dir` global variables.
Note that as we read and set dirs for each instance individually, this change does not effect them.
Tests 
- Unit test
Code changes
Side effects
None
Release notes:
```release-note
Set correct `deploy_dir` of monitoring agents when importing ansible deployed clusters
```
=> cluster/import: read and set deploy_dir properly on import

components/dm/spec/grafana.go, components/dm/spec/prometheus.go, pkg/cluster/operation/telemetry.go, pkg/cluster/task/install_package.go
Make sure the decompressed files are owned by the current user
Add `--no-same-owner` flag to `tar` command when decompressing
Tests 
Code changes
Side effects
None
Release notes:
```release-note
NONE
```
=> cluster: set owner to current user when decompressing tarballs

components/cluster/command/check.go, pkg/cluster/operation/check.go
- `check` sub command is not working properly with existing cluster
- checks are not performed for instance with no data dir defined
- Fix credential settings for existing clusters
- Handle data dir properly
- `ss -ltn` may report multiple records for on port (with different fd, may because of `TCP_PORT_REUSE`), only one is enough for the check
Tests 
Code changes
Side effects
None
Release notes:
```release-note
NONE
```
=> cluster/check: fix checking of existing cluster

components/cluster/command/root.go, components/dm/command/root.go, components/dm/main.go, pkg/cliutil/cliutil.go
Set the magic arg0 for dm. Remove RunE for both cluster and dm because
they are just not runable. Remove the wrong custom UseLine although we nolonger
show it.(the raw useline we get "tiup cluster [flags]", the custom
useline will be "tiup cluster cluster [flags]")
fix https://github.com/pingcap/tiup/issues/703
Set the magic arg0 for dm. Remove RunE for both cluster and dm because
they are just not runable. Remove the wrong custom UseLine although we nolonger
show it.(the raw useline we get "tiup cluster [flags]", the custom
useline will be "tiup cluster cluster [flags]")
Tests 
Release notes:
```release-note
NONE
```
=> Fix showing  misleading usage for cluster and dm

components/dm/ansible/import.go, components/dm/ansible/import_test.go, components/dm/command/import.go, tests/tiup-dm/test_import.sh
dm-worker 1.0 will write some data  at  {wd}/dm_worker_meta.
and 2.0 bootstrap need this directory(after bootstrap, this directory will be deleted by worker)
So we must always keep using the same wd when upgrade to 2.0
Deploy dir MUST always keep the same and CAN NOT change.
dm-worker will save the data in the wording directory and there's no configuration
to specify the directory.
We will always set the wd as DeployDir.
also, mark `cluster-version` required instead of nightly default.
Tests 
- Unit test
Release notes:
```release-note
NONE
```
=> Keep deploy dir for worker while import from ansible

components/playground/main.go, components/playground/playground.go, pkg/cliutil/progress/example_single_bar_test.go
fix #719 
Using a single bar when checking db or kv/tiflash status.
This pr also adds an example for the single bar and simplifies code about starting tiflash by wrapping related code in a func in playground.
Tests 
Release notes:
```release-note
NONE
```
=> Display checking state using bar

components/playground/grafana.go, components/playground/instance/proc_attr_default.go, components/playground/instance/proc_attr_linux.go, components/playground/instance/process.go, components/playground/main.go, components/playground/monitor.go, pkg/exec/run.go
fix #720 
Set Pdeathsig to kill subprocess if playground dead
After this pr, if playground dead and some subprocess still running,
the subprocess will be killed by OS instead of becoming an orphaned child
adopted by init. This feature is linux only.
Tests 
before this pr:
after this pr:
Release notes:
```release-note
Set Pdeathsig to kill subprocess if playground dead
```
=> Set Pdeathsig to kill subprocess if playground dead

components/dm/spec/grafana.go, pkg/cluster/executor/ssh.go, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/prometheus.go
Fix https://github.com/pingcap/tiup/issues/736
=> Bugfix: cleanup wrong conf files

server/handler/tarball.go
This variable name is different from its real context and is misleading, the doc of  [`func (r *Request) ParseMultipartForm(maxMemory int64) error`]( https://github.com/golang/go/blob/master/src/net/http/request.go#L1271-L1277) as below:
> // ParseMultipartForm parses a request body as multipart/form-data.
// The whole request body is parsed and up to a total of maxMemory bytes of
// its file parts are stored in memory, with the remainder stored on
// disk in temporary files.
// ParseMultipartForm calls ParseForm if necessary.
// After one call to ParseMultipartForm, subsequent calls have no effect.
Tests 
- Unit test
- No code
Code changes
- …
=> server/handler: MaxFileSize -> MaxMemory

docker/up.sh
The `/bin/echo` in macOS defaults to BSD's, and which can't print out a message with the colorful output:
_ps_: If you want to use colorful echo output in macOS, you can install `coreutils` and put the binutils  first in PATH
```bash
brew install coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes: …
=> fix(docker): ompatible with macOS's echo

pkg/cluster/executor/ssh.go, pkg/localdata/constant.go, pkg/utils/ioutil.go, pkg/utils/ioutil_test.go
#711  
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> executor/ssh: introduce TIUP_SSH_PATH,TIUP_SCP_PATH

components/cluster/main.go, pkg/cliutil/cliutil.go
fix #753 
Tests 
- Unit test
- No code
**Manual test**
```bash
(base) root@rabbit:tiup <fix/cluster-help-inconsistent(v1.1.0-15-gf645c99)>$ ./bin/tiup cluster check -h
Perform preflight checks for the cluster. By default, it checks deploy servers
before a cluster is deployed, the input is the topology.yaml for the cluster.
If '--cluster' is set, it will perform checks for an existing cluster, the input
is the cluster name. Some checks are ignore in this mode, such as port and dir
conflict checks with other clusters
Usage:
tiup cluster check <topology.yml | cluster-name> [flags]
Flags:
--apply                  Try to fix failed checks
--cluster                Check existing cluster, the input is a cluster name. …
```
=> cliutil: set cmdLine if registered

examples/topology.example.yaml
the example value of parameter `spark.tispark.grpc.framesize` is too small
see https://github.com/pingcap/tispark/pull/1597
let `spark.tispark.grpc.framesize` = 2147483647
Tests 
- No code
Release notes:
```release-note
NONE
```
=> update tispark example parameter spark.tispark.grpc.framesize value

pkg/cluster/operation/action.go, pkg/cluster/spec/tiflash.go
Fix the issue that tiflash's data is not clean up when tombstone
when tombstone
before this pr:
after this pr:
We use ServicePort in DestroyClusterTombstone to construct id and filter by id,
but the id of instances of the cluster is construct using Port(TCPPort for
tiflash),
so it will not get the instance and clean its data in DestroyClusterTombstone.
Note the GetMainPort() is TCPPort now, change the code to both
using GetMainPort() to avoid inconsistent.
Tests 
deploy -> scale-in -> check work as expect
Release notes:
```release-note
Fix the issue that tiflash's data is not clean up when tombstone
```
=> Fix the issue that tiflash's data is not clean up when tombstone

cmd/env.go, cmd/root.go, pkg/localdata/constant.go, tests/tiup/test_tiup.sh
Fix https://github.com/pingcap/tiup/issues/632
Fix https://github.com/pingcap/tiup/issues/632
Add the env subcommand
Tests 
Release notes:
```release-note
Support tiup env sub command
```
=> Support tiup env command

components/cluster/command/clean.go, components/cluster/command/destroy.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster/command: missing short help of clean/destory

pkg/cluster/operation/download.go
Fix https://github.com/pingcap/tiup/issues/565
Fix https://github.com/pingcap/tiup/issues/565
Stop ignoring nightly when check if we should download. This is ok because the `VerifyComponent` step will remove old nightly version.
Tests 
Release notes:
```release-note
NONE
```
=> Skip download nightly package when it exists

components/dm/ansible/import.go, components/dm/command/deploy.go, components/dm/command/root.go
maybe fix #781.
IMO, we should set the type of timeout from `int64` to `uint64`, and bind with `Uint64Var`  https://github.com/pingcap/tiup/blob/65fdf56b28440506356942167b007315802a7e52/pkg/cluster/operation/operation.go#L29-L31
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> dm: forget to set sshType,sshTimeout

components/cluster/command/patch.go, components/cluster/command/reload.go, components/cluster/command/root.go, components/cluster/command/scale_in.go, components/cluster/command/upgrade.go, components/dm/ansible/import.go, components/dm/command/display.go, components/dm/command/patch.go, components/dm/command/reload.go, components/dm/command/root.go, components/dm/command/scale_in.go, components/dm/command/upgrade.go, pkg/cluster/ansible/config.go, pkg/cluster/ansible/inventory.go, pkg/cluster/ansible/service.go, pkg/cluster/manager.go, pkg/cluster/operation/action.go, pkg/cluster/operation/destroy.go, pkg/cluster/operation/operation.go, pkg/cluster/operation/scale_in.go, pkg/cluster/spec/instance.go, pkg/cluster/task/builder.go, pkg/cluster/task/context.go, pkg/cluster/task/ssh.go
fix #813 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> *: set timeout's type from int64 to uint64

components/cluster/command/check.go, components/cluster/command/deploy.go, components/cluster/command/destroy.go, components/cluster/command/reload.go, components/cluster/command/scale_out.go, pkg/cluster/ansible/config.go, pkg/cluster/manager.go, pkg/cluster/operation/action.go, pkg/cluster/operation/destroy.go, pkg/cluster/operation/upgrade.go, pkg/cluster/task/builder.go, pkg/cluster/task/step.go, pkg/cluster/task/task.go
Fix https://github.com/pingcap/tiup/issues/750
Fix https://github.com/pingcap/tiup/issues/750
Ignore remote error while `scale-in`, `reload`, `upgrade` and `destroy` cluster
Tests 
Assume we have a broken cluster (host lost):
Side effects
Release notes:
```release-note
NONE
```
=> Force relaod, scale-in and destroy

doc/dev/README.md
Fix https://github.com/pingcap/tiup/issues/829
Tests 
- No code
=> Update dev doc

pkg/cluster/manager.go
Fix https://github.com/pingcap/tiup/issues/823
Fix https://github.com/pingcap/tiup/issues/823
Skip auto-start because before any really action, tiup need to check the labels set in PD(https://github.com/pingcap/tiup/blob/b4c0a9f59e9ffb1e5e7c20e2515a84fb8844053a/pkg/cluster/manager.go#L602), which implies that the PDs must be started.
Tests 
Release notes:
```release-note
NONE
```
=> Skip atuo-start cluster before scale-out action

components/cluster/command/import.go, components/err/error.go, pkg/cluster/manager.go, pkg/localdata/profile.go, pkg/utils/ioutil.go, pkg/utils/ioutil_test.go
We copy file with tiuputils.CopyFile, which is dup with tiuputils.Copy and both of them forget to change the mode of created file.
call os.Chmod after create target.
Tests 
- Unit test
Release notes:
```release-note
NONE
```
=> Fix copy file without mode

doc/user/README.md, pkg/cluster/api/pdapi.go, pkg/cluster/manager.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go
Fix https://github.com/pingcap/tiup/issues/838
For imported clusters, it will report missing label when executing `tiup cluster display` since the server.labels is missing in meta.yaml. 
Read labels config from PD server instead of meta.yaml.
Tests 
- Unit test
Release notes:
```release-note
NONE
```
=> Introduce a more graceful way to check labels

components/errdoc/main.go, components/errdoc/spec/spec.go
This PR refine the output of errdoc search results and make it more pretty.
Tests 
```
Failed to read auto-increment value from storage engine
Generated column '%s' cannot refer to auto-increment column.
Expression index '%s' cannot refer to an auto-increment column
```
Release notes:
```release-note
Update the search result output of errdoc component
```
=> Update the output of errdoc component

components/cluster/command/display.go, components/cluster/command/prune.go, components/cluster/command/root.go, components/dm/command/display.go, components/dm/command/prune.go, components/dm/command/root.go, go.sum, pkg/cluster/manager.go, pkg/cluster/operation/action.go, pkg/cluster/operation/scale_in.go, tests/tiup-cluster/script/util.sh, tests/tiup-dm/script/util.sh
With TiUP, if we want to offline a TiKV server, we need do this first:
```sh
tiup cluster scale-in <cluster-name> -N <tikv-node-id>
```
This will send a request to PD servers to tell them that we want to offline this TiKV server, then PD servers will transfer all regions in this TiKV to some other place. After transferring data, the state of this TiKV server will be tombstone. At this point, the data of this server will be deleted (see the yellow line in the picture below).
But oncel the user execute the `display` command:
```sh
tiup cluster display <cluster-name>
```
The TiKV server in tombstone state will be destroyed and cleanup at once, this may confuse users and it's unsafe.
DO NOT cleanup tombstone TiKV servers in display command, but add a prune command to do this, and give the …
=> More safe way to cleanup tombstone nodes

pkg/cluster/api/pdapi.go, pkg/cluster/manager.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go
Fix https://github.com/pingcap/tiup/issues/863
Skip tiflash and tombstone TiKV while fetch labels
Tests 
Release notes:
```release-note
NONE
```
=> Fix labels warning

.github/pull_request_template.md, CONTRIBUTING.md
The old URL was returning a HTTP 404 Not Found.
This seems to be the result of https://github.com/pingcap/community/commit/41fd697b523adace5f717e97d433201336653fc4
Updated the URL to what seems to be the correct URL.
Tests 
- No code
Release notes:
```release-note
NONE
```
=> Correct 'Contribution Guide' URL

pkg/cluster/audit/audit.go, pkg/cluster/audit/audit_test.go, tests/tiup-dm/run.sh
In my local dev's env, I've found the audit log file was base52 encoded with `time.Now().Unix()`, while at the same time, if the command is run fast enough, then the later file with the same name will cover the previous one.
In my local dev, I'm running `tiup-dm test-cmd`
```bash
bash /tiup-cluster/tests/tiup-dm/run.sh --native-ssh --do-cases test_cmd
exit 1
```
the below case **maybe**(occasional) failed of this line https://github.com/pingcap/tiup/blob/11535d272a90f904ad5b8f73af5dddc224c2894d/tests/tiup-dm/test_cmd.sh#L28
Tests 
- Unit test
- No code
Code changes
Side effects
- …
=> cluster/audit: audit log in seconds maybe leads to file overwriten

components/cluster/command/prune.go, pkg/cluster/operation/action.go, pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go, tests/tiup-cluster/script/scale_tools.sh, tests/tiup-cluster/topo/full.yaml.tpl, tests/tiup-cluster/topo/full_scale_in_tiflash.yaml.tpl
fix #865 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix the issue when `dataDir` contains `,` can't detect `CountDir()` exceptions and `dirConflictsDetect()` 
```
=> Fix dataDir not deleted if containing comma

pkg/cluster/audit/audit.go, pkg/cluster/audit/audit_test.go
The old audit's filename was based on `second`, after #879 merged, the filename changed to `nanosecond` based. So this PR fixes the difference between those two situations. 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix(cluster/audit): compatible with old second based ts

pkg/cluster/manager.go
Fix https://github.com/pingcap/tiup/issues/883
Use metadata from specManager instead of hardcoded cluster metadata
Tests 
```sh
JoshuadeMacBook-Pro:dm joshua$ tiup dm patch test ~/.tiup/storage/dm/packages/dm-worker-v2.0.0-linux-amd64.tar.gz -R dm-worker
Starting component `dm`: /Users/joshua/.tiup/components/dm/v1.2.0/tiup-dm patch test /Users/joshua/.tiup/storage/dm/packages/dm-worker-v2.0.0-linux-amd64.tar.gz -R dm-worker
+ [ Serial ] - SSHKeySet: privateKey=/Users/joshua/.tiup/storage/dm/clusters/test/ssh/id_rsa, publicKey=/Users/joshua/.tiup/storage/dm/clusters/test/ssh/id_rsa.pub
+ [Parallel] - UserSSH: user=tidb, host=172.16.5.139
+ [Parallel] - UserSSH: user=tidb, host=172.16.5.139
+ [Parallel] - UserSSH: user=tidb, …
```
=> Fix tiup dm patch can't detect correct version

go.mod, go.sum
Signed-off-by: mahjonp <junpeng.man@gmail.com>
fix #886
Ref: https://github.com/pingcap/go-tpc/pull/63
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> update pingcap/go-tpc version

cmd/mirror.go, pkg/cluster/manager.go, pkg/cluster/spec/bindversion.go, pkg/repository/v1_repository.go
Fix https://asktug.com/t/topic/37633
Just return emtpy version in version mapper and in download and deploy stage, we use the latest stable one if the version is empty.
Release notes:
```release-note
NONE
```
=> Fix ti-spark scale-out

components/cluster/command/scale_out.go, tests/tiup-cluster/script/scale_core.sh
fix #875 
Tests 
- Unit test
- Manual test 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: enable service after scale out

pkg/cluster/manager.go
Fix #909 
Ignore no tispark master error when listing clusters
Tests 
Code changes
Release notes:
```release-note
cluster: ignore no tispark master error when listing installed clusters
```
=> cluster: ignore no tispark master error when listing clusters

install.sh
Add a new line for the export path of TIUP, fix the issue caused by adding the path export to the previous line.
Adding a `\n` new line in front of the inject sentence
Tests 
Code changes
Release notes:
```release-note
NONE
```
=> fix(install): install script export path

CHANGELOG.md, pkg/version/version.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Bump v1.2.4

pkg/cluster/manager.go, pkg/cluster/operation/scale_in.go, pkg/cluster/spec/spec_manager.go
Make it possible for broken clusters to fix no tispark master error by scaling out a new tispark master node
Ignore topology validation error when listing clusters, this is a following up of #920
Tests 
Code changes
Release notes:
```release-note
NONE
```
=> cluster: fix tispark master scaling handling

pkg/cluster/spec/parse_topology_test.go, pkg/cluster/spec/tiflash.go
Signed-off-by: JaySon-Huang <tshent@qq.com>
If there is only one directory in TiFlash storage.* configuration, the TiFlashSpec DataDir become unexpected value.
Introduced by #931 
Fix a bug that if there is only one directory in TiFlash storage.* configuration
Tests 
- Unit test
Code changes
- N/A
Side effects
Release notes:
```release-note
NONE
```
=> Fix bug for only one directory in TiFlash storage.* configuration

pkg/cluster/task/tls.go
This PR updates TLS certificate generator to support issuing certificates for host names, not only IP addresses.
This contributes towards fixing #337.
If host name is detected field `DNSNames` of x509 SAN extenstion is used instead of `IPAddresses`.
* https://en.wikipedia.org/wiki/Subject_Alternative_Name
* https://tools.ietf.org/html/rfc5280#section-4.2.1.6
Tests
Integration tests that cover this functionality is available in #950.
Release notes:
```release-note
NONE
```
=> Support host names in TLS certificates

pkg/repository/v1manifest/manifest.go, pkg/repository/v1manifest/types.go
As https://github.com/pingcap/tiup/blame/master/doc/design/manifest.md#L256 specified, the dependencies filed should be `map[string]string`. But in the current implementation, it's `[]string`, fortunately, this field is not used up until now and it's aways a `null` in the manifest json file, which adopted both `[]string` and `map[string]string`. But in the future, we may use this field, so it's better to correct it as early as possible.
- change `[]string` to `map[string]string`
- upgrade the spec version from `v0.1.0` to `v0.1.1`
Tests 
- Unit test
- No code
Code changes
Side effects …
=> Fix the dependencies field to match the specification

components/cluster/command/clean.go, components/cluster/command/deploy.go, components/cluster/command/root.go, components/cluster/command/scale_out.go, components/dm/command/root.go, pkg/cluster/operation/destroy.go, pkg/set/string_set.go
Part of #947 
- Mark experimental features more visible
- Check for paths to avoid deleting files if data dir is a sub path of log dir
- Only delete `*.log` when deleting log files
Tests 
Code changes
Side effects
Release notes:
```release-note
cluster: adjust checking process when cleaning log files
```
=> cluster: refine log_dir handling on `clean` (part 1)

pkg/cluster/manager/cleanup.go, pkg/cluster/operation/destroy.go
Prompt the user for file paths that are going to be delete and ask for confirmation, so that the user has a chance to cancel the process if there's anything unexpected.
This is a following up of #981 and closes #947 
Calculate the file list before promoting for confirmation.
Tests 
Code changes
Release notes:
```release-note
cluster: refine `clean` sub command for better usability
```
=> cluster/clean: prompt list of paths to be delete before processing (part 2)

pkg/cluster/operation/check.go
Introduced by https://github.com/pingcap/tiup/pull/964
Related issue: https://github.com/pingcap/tiup/issues/1006
There is a newline at the end of output of cat command,
so the '[never]' check will fail on the empty newline.
=> Fix tail newline on thp check

cmd/mirror.go
=> Fix tiup mirror merge usage

pkg/cluster/spec/tikv.go
Workaround of https://github.com/tikv/pd/issues/3303
A case of the issue is at: https://asktug.com/t/topic/66779
When we iterate over the store list, check if any store is marked as "tombstone" state, if **not**, use it as the final state of the "host:port" store, otherwise use the state from store that has the max ID.
Sorting the slice should be not necessary as we are iterating the whole list anyway, and are only finding specific item in.
Tests 
Code changes
Side effects
Release notes:
```release-note
cluster/spec: add workaround to get correct store state when PD is not assigning store ID monotonically
```
=> cluster/spec: workaround if store IDs are not monotonically assigned

pkg/cluster/spec/prometheus.go
Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.
Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.
Fix the spelling of "Drainer"
Tests 
- Unit test
- No code
Release notes:
```release-note
NONE
```
=> Tiny fix for the problem that the Drainer monitoring configuration of Prometheus is lost due to spelling.

pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go
The `root.json` should be updated before `snapshot.json`.
Release notes:
```release-note
NONE
```
=> respository: update root before snapshot

pkg/cluster/api/error.go, pkg/cluster/api/error_test.go, pkg/cluster/api/pdapi.go, pkg/cluster/spec/tikv.go
This is a following up of #1011 
Some more functions than checking store state are querying for store info of the latest / current store from PD that matching a specific host, so use a dedicated function to archive that purpose and implement the workaround of non-monotonic ID issue of PD there.
Tests 
Code changes
Release notes:
```release-note
NONE
```
=> cluster: refine the process of getting latest store info from pd

cmd/env.go
TIUP_TELEMETRY_STATUS and TIUP_TELEMETRY_UUID is passed to component
by TiUP itself, and it should not be set by user, so we should NOT
list it in tiup env
=> Remove env that should not be set by user

pkg/cluster/manager/reload.go
The prometheus URL in PD is not updated on `reload`, thus dashboard is not using the correct prometheus for querying.
Currently, run `reload` with any node (even a non-exist node) could trigger the update and workaround this. 
Tests 
Release notes:
```release-note
cluster: update dashboard metadata on reload
```
=> cluster: update dashboard metadata on reload

components/cluster/command/deploy.go, components/cluster/command/upgrade.go, components/dm/command/deploy.go, pkg/utils/semver.go, pkg/utils/semver_test.go, tests/tiup-cluster/script/cmd_subtest.sh, tests/tiup-cluster/test_cmd.sh, tests/tiup-cluster/test_cmd_tls_native_ssh.sh
1. prepend `v` to bare version number, so that `v4.0.8` and `4.0.8` are both valid input
2. validate input version to ensure it's a valid semver string
Close #350 
Tests 
Release notes:
```release-note
cluster, dm: support version input without leading 'v'
```
=> cluster, dm: format semver input

pkg/cluster/manager/cleanup.go
Fix https://github.com/pingcap/tiup/issues/1028
=> Add warn on clean log

pkg/cluster/spec/pd.go
Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>
* When  `tiup reload pd` is executed, PD service may be unavailable for about 10 seconds.
* If the PD immediately becomes the target of the transfer leader when it is just started, the [publish operation](https://github.com/etcd-io/etcd/blob/v3.4.3/etcdserver/server.go#L731) of the ETCD in the PD will block until it times out after 10 seconds, causing the PD Leader to be unavailable for a short time.
* When rolling restart PD, confirm that each peers can serve after starting
Tests 
- sysbench
- `tiup reload pd`
Release notes:
```release-note
Fix: wait the restarted PD instance to be healthy before stopping next one during …
```
=> cluster: when rolling restart PD, confirm that each peers can serve

pkg/cluster/spec/prometheus.go, tests/tiup-cluster/script/scale_tools.sh
fix #1038
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tests/tiup-cluster: check prometheus monitored components

pkg/cluster/manager/transfer.go, pkg/cluster/manager/transfer_test.go, tests/tiup-cluster/script/cmd_subtest.sh
Introduced by https://github.com/pingcap/tiup/pull/1044, TiUP can't notice that the TiDBSpec don't have DataDir and will render an empty string
Convert pointer to struct it point to if the `s` of renderSpec is a pointer.
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix push with template

pkg/cluster/manager/display.go
the dashboardAddr maybe `none` or `auto`,  don't print it. 
ref https://github.com/pingcap/tiup/blob/9fd5a221df15ddc9d507383777d6c6f84c16fb00/components/cluster/command/display.go#L98-L102,
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix(cluster/display): don't print dashboardAddr if none or auto

cmd/completion.go
rename the completion's filename from `~/.completion.bash.inc` to `~/.tiup.completion.bash`
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> feat(cmd): add tiup as completion's prefix name

pkg/cluster/spec/grafana.go
Introduced by https://github.com/pingcap/tiup/pull/982
Close https://github.com/pingcap/tiup/issues/1055
=> Fix the issue that dm grafana doen't has home.json

go.mod, go.sum, pkg/utils/diff.go, pkg/utils/diff_test.go
Allowing value type change for `edit-config`. Especially useful when editing configs.
The latest version of `r3labs/diff` has an option to ignore type mismatch error, so we upgrade the dependency and enable that option.
Tests 
- Unit test
(Change `tikv_servers.(server).config.key: 10` to `tikv_servers.(server).config.key: "10MB"`)
Before:
After:
Save as normal.
Release notes:
```release-note
cluster: allow value type change in `edit-config`
```
=> cluster: allow type change when editing topology

components/cluster/command/check.go, pkg/cluster/manager/exec.go, pkg/cluster/manager/transfer.go, pkg/cluster/task/builder.go, pkg/cluster/task/shell.go, pkg/cluster/task/task.go
We had added a simple implementation of rendering input as template with instance specification in #1044 which makes it easier to close #894 
Render command string as template before sending it to executor.
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: support spec template for `exec`

pkg/repository/v1manifest/manifest.go
For the cloned mirror, we set the expires filed expire after 50 years since the user rarely modify the mirror so we can assume that's safe. However, when the user try to publish component to the cloned mirror, the problem occurred：the expire time will be shortened to just one. month because we think it's unsafe if the user need to modify it. It's OK when the user need to modify it frequently, because every time he modify it, the expire time will be push forward to a month latter. However, what if the user just modify it once and use it alone the time? The mirror will expire after a month so that the user must modify it again in a month even though he don't want to do that.
We compare the new expire time and the old one, use the longer one.
Tests 
- Unit test
- Manual …
=> Fix the issue that the expires shortened after merging cloned mirror

cmd/mirror.go, pkg/repository/clone_mirror.go, pkg/repository/v1manifest/repo.go
Add `Warning` if the private key exists
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> typo(cmd/mirror): add warning if key already exists

pkg/cluster/executor/local.go, pkg/cluster/executor/local_test.go
Fix the issue triggerd in #1073 [grafana unit-test](https://github.com/pingcap/tiup/pull/1073/checks?check_run_id=1714008844#step:4:287): 
```bash
--- FAIL: TestLocalDashboards (0.10s)
grafana_test.go:64: 
Error Trace:	grafana_test.go:64
Error:      	Expected nil, but got: stderr: bash: s/${DS_.*-CLUSTER}/tiup-test-cluster-fe80bb2e-9094-425c-ab5f-a258e928e759/g: bad substitution
: executor.ssh.execute_failed: Failed to execute command locally {ssh_stderr: bash: s/${DS_.*-CLUSTER}/tiup-test-cluster-fe80bb2e-9094-425c-ab5f-a258e928e759/g: bad substitution
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H -u runner bash -c "cd; find /tmp/tiup-166443879/dashboards -type f -exec sed -i "s/\${DS_.*-CLUSTER}/tiup-test-cluster-fe80bb2e-9094-425c-ab5f-a258e928e759/g" …
```
=> fix(cluster/executor): local executor should in single quote command

pkg/cluster/operation/destroy.go, pkg/cluster/spec/testdata/countdir.yaml, pkg/cluster/spec/util.go, pkg/cluster/spec/util_test.go, pkg/cluster/spec/validate_test.go
If an imported cluster has deploy dir ending with `/`, and sub dirs as `<deploy-dir>//sub`, the result of `CountDir()` may not be accurate, and could results to delete wrong paths on `scale-in`.
One of the case is when:
- The deploy dir is `/foo/`, and
- The log dir is `/foo//log`, and
- There **is and only is** 1 instance with only 1 sub directory under deploy dir (e.g., tidb with log dir under deploy dir) deployed on host `1.2.3.4`, and
- There are other instances without log dir and data dir (e.g., grafana) deployed on the same host
The deploy dir will be deleted when `scale-in` the grafana instance, so that the tidb instance is also broken.
1. Not deleting deploy dir for imported instance
2. Trim redundant slashes from the path when parsing meta file
Tests 
- Unit test
Code changes
- …
=> cluster: fix parsing of paths if there are redundant slashes in it

components/cluster/command/destroy.go, components/dm/command/destroy.go
implement #1079 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Feature/dm destroy support --force --retaion-node-data --retaion-role-data

pkg/cliutil/tui.go, pkg/cluster/manager/edit_config.go
Close #1090 
Release notes:
```release-note
tui: add user's answer in the error message if prompted challenge didn't pass
```
=> cliutil: return user's answer on prompt

install.sh, pkg/cluster/template/install/local_install.sh.go
The darwin-arm64 is not supported currently, and add some friendly hint.
temporary fix for #1122 
Add some hints 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Add darwin-arm64 not support hint for install.sh

pkg/repository/mirror.go, server/handler/component.go, server/main.go, server/server.go
So that we can place the keys directory outside the mirror
At current tiup-server try to find private keys in the {mirror-root}/keys directory, this need the user put the private keys under the root directory, which is risky.
Add a `keys` flag so that the user can specify a directory that stores the keys.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Add --keys flag for server

pkg/repository/merge_mirror.go
Close https://github.com/pingcap/tiup/issues/1120
Don't ignore yanked versions because official offline package will yank all the versions other than that package version.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that merge not work with official offline package

components/playground/playground.go
A `tiup playground nightly` results in:
```
To connect TiDB: mysql --host 127.0.0.1 --port 4000 -u root
```
Running this doesn't work:
```
$ mysql --host 127.0.0.1 --port 4000 -u root
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)
```
This happens if a `~/.mylogin.cnf` is present or if a password is configured in `~/.my.cnf`.
```
$ mysql_config_editor print
[client]
password = *****
```
Adding a `-p` to `mysql` will cause this to prompt for passwords, just pressing
enter then results in a working connection.
Another option would be to set a password for the root user and use `-p<passwd>`
on the command.
Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Change the playground info for connecting to TiDB

pkg/cliutil/tui.go, pkg/cluster/manager/manager.go
when  tuip deploy
deafult  choice is N, but  here is no default description
Attention:
1. If the topology is not what you expected, check your yaml file.
2. Please confirm there is no port/directory conflicts in same host.
Do you want to continue? [y/N]  (default=N):
have a  default description
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> add default description

pkg/cluster/task/update_topology.go, tests/tiup-cluster/script/cmd_subtest.sh
fix #333 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
fixed an issue with hang forever when updating topology
```
=> cluster: updateTopology maybe hang forever

components/playground/instance/drainer.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/pump.go, components/playground/instance/ticdc.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/playground.go
fix #1007 
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: set grafana topology in pd

cmd/install.go
partly implement #1077 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tiup: install --force to reinstall

components/playground/playground.go
fix #1135 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: use the advertised host instead of 0.0.0.0

tools/check/check-lint.sh
check-lint.sh can't work on macOS
```
> make
gofmt (simplify)
goimports (if installed)
linting
./tools/check/check-lint.sh
bash: ./tools/check/check-lint.sh: /bin/env: bad interpreter: No such file or directory
make: *** [lint] Error 126
```
Change `/bin/env` to `/usr/bin/env`
Tests 
Run `make` command to do manual test.
Release notes:
```release-note
NONE
```
=> Fix check-lint.sh can't run on macOS

pkg/cluster/clusterutil/cluster.go, pkg/cluster/operation/download.go, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go, pkg/utils/sha.go
Add info to show the target that fails a checksum validation in error message, this could make it easier for users to know what went wrong.
Also cleanup some unused code after #906 
Release notes:
```release-note
NONE
```
=> *: optimize checksum mismatch error

pkg/cluster/api/pdapi.go, pkg/cluster/operation/upgrade.go
Implement task 2 in #1033 
Increase schedule limits before upgrade of TiKV, and set them back after.
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: increase schedule limit during upgrade of tikv

pkg/cluster/manager/cleanup.go, pkg/cluster/manager/destroy.go, pkg/cluster/manager/display.go, pkg/cluster/manager/edit_config.go, pkg/cluster/manager/exec.go, pkg/cluster/manager/patch.go, pkg/cluster/manager/reload.go, pkg/cluster/manager/rename.go, pkg/cluster/manager/scale_in.go, pkg/cluster/manager/scale_out.go, pkg/cluster/manager/transfer.go, pkg/cluster/manager/upgrade.go
Fix #1176 
Validate cluster name for all cluster operations.
Release notes:
```release-note
cluster: validate cluster name for all cluster operations
```
=> cluster: validate cluster name for all cluster ops

pkg/cluster/manager/builder.go, pkg/cluster/manager/destroy.go, pkg/cluster/manager/reload.go, pkg/cluster/manager/scale_in.go
Fix #1173
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: check config before reload

cmd/help.go, pkg/environment/env.go, pkg/localdata/profile.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that tiup may choose yanked version if it's already installed

components/cluster/command/template.go, components/dm/command/template.go
Fix help command does not display template
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=>  Fix  help command does not display template

pkg/environment/env.go, pkg/repository/v1_repository.go
In `v1.3.4`, TiUP will check local installed version to filter yanked versions. However, if the version is not yanked but removed from component manifest, eg. an old nightly version will be removed from manifest daily, TiUP will report an error.
In `SelectInstalledVersion`, ignore unknown version instead of reporting an error
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes: …
=> Fix the issue that old nighlty may cause error

cmd/mirror.go, pkg/repository/clone_mirror.go
Currently `mirror clone` is in serial mode, it's slow to clone the entire mirror site. So I add `--jobs` to specify the number of download jobs to speed up.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> mirror: clone in concurrent jobs 

embed/templates/scripts/run_grafana.sh.tpl, pkg/cluster/api/binlog.go, pkg/cluster/manager/display.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/validate.go
fix #1166 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> grafana: fix lightning's name not changed when cluster renamed

components/cluster/command/display.go, components/dm/command/display.go
Add an option `--version` to `display` subcommand of `cluster` and `dm` to only print cluster version to console.
This could be helpful for scripting, an sample usage case would be getting `ctl` with the same version as an deployed cluster.
Tests 
Release notes:
```release-note
Add an option to `display` subcommand to only show cluster version.
```
=> cluster&dm/display: add an option to only show cluster version

pkg/cluster/operation/upgrade.go
Upgrade errors for TiKV instances are overwritten and ignored.
This was introduced in #1161 
Tests 
Release notes:
```release-note
NONE
```
=> cluster: fix tikv upgrade error not returned correctly

pkg/cluster/manager/deploy.go, pkg/cluster/manager/upgrade.go, pkg/cluster/task/copy_component.go, pkg/cluster/task/download.go, pkg/repository/v1_repository.go
Fix https://github.com/pingcap/tiup/issues/1228
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that tiup-cluster can't deploy arm64 binary

pkg/cluster/manager/destroy.go
Fix https://github.com/pingcap/tiup/issues/1236
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that prune command will regen config for removed nodes

pkg/cluster/spec/prometheus.go, pkg/cluster/spec/prometheus_test.go, tests/tiup-cluster/test_upgrade_tls.sh
fix #990 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster,dm: replace ENV_LABELS_ENV in prometheus rules

components/cluster/command/check.go, components/cluster/command/reload.go, components/dm/command/reload.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster,dm: -R -N's help message is wrong

cmd/root.go, pkg/cluster/manager/destroy.go
Not able to show components' version as the `-v/--version` was always been processed by `tiup`. It was introduced in #1158 
Not using cobra's builtin `Version` field, but define a custom version argument in `tiup`.
Tests 
Release notes:
```release-note
NONE
```
=> tiup: fix -v/--version argument

components/cluster/command/display.go, components/dm/command/display.go, components/dm/spec/logic.go, go.mod, pkg/cluster/manager/display.go, pkg/cluster/operation/operation.go, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/cdc.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/instance.go, pkg/cluster/spec/pd.go, pkg/cluster/spec/prometheus.go, pkg/cluster/spec/pump.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tidb.go, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/tikv.go, pkg/cluster/spec/tispark.go, pkg/cluster/spec/util.go, tests/tiup-cluster/script/cmd_subtest.sh, tests/tiup-dm/test_cmd.sh
implement #1223 
display the uptime of the instance, 
if this instance is up, then `uptime` means the alive time, else is the inactive time. 
see #1223 for more detail 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> dm,cluster: display with uptime returned

tools/check/check-lint.sh
Fix typo for find command.
When running make we see
```
rkazak@rkazaknb tiup % make
gofmt (simplify)
goimports (if installed)
linting
./tools/check/check-lint.sh
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
go mod tidy
```
Added in missing '.' - local dir path.
```
rkazak@rkazaknb tiup % make        
gofmt (simplify)
goimports (if installed)
linting
./tools/check/check-lint.sh
go mod tidy
```
Tests 
- Unit test
- No code
Code changes
Side effects
- Possible performance …
=> Fix typo with find command

docker/docker-compose.yml.tpl, docker/up.sh
I'm try to reproduce this issue https://github.com/pingcap/tiup/issues/1187, and want to start N nodes, but currently TiUP only starts 5 nodes, I want to start more nodes, so I added this argument.
This PR will install the jinja2 tool from https://github.com/kolypto/j2cli, and use this tool to generate `--nodes` tiup-cluster-node.
Tests 
- Unit test
- No code
Code changes
Side effects
Release …
=> docker: support --nodes

embed/templates/systemd/system.service.tpl, pkg/cluster/task/monitored_config.go, pkg/cluster/template/systemd/system.go
Signed-off-by: STRRL <str_ruiling@outlook.com>
fix #1249
- add `AmbientCapabilities=CAP_NET_RAW` with condition `GrantCapNetRaw` in the template
- set `GrantCapNetRaw` to `true` when `componentName == spec.ComponentBlackboxExporter`
Tests 
- Unit test
- No code
Manually test with `tiup cluster deploy`.
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix: grant cap_net_raw to blackbox_exporter

pkg/cluster/manager/manager.go
IN `tiup cluster display` the topology's header is like below:
But in `tiup cluster scale-out` the topology's header is like below:
Let's be consistent
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: Type -> Rule in confirmTopology

.github/workflows/release-tiup.yaml, .github/workflows/reprotest.yaml, Makefile
Fix releasing CI, the upload to release assets step was failing.
Tests 
Release notes:
```release-note
NONE
```
=> *: fix releasing workflow

components/cluster/command/scale_out.go, components/dm/command/scale_out.go, pkg/cluster/manager/builder.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/scale_out.go, pkg/cluster/spec/pd.go, pkg/cluster/template/scripts/pd.go, pkg/cluster/template/scripts/pd_test.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: reuse cluster.DeployOption and spec.PDScaleScript

components/playground/instance/process.go, components/playground/instance/tikv.go, embed/templates/scripts/run_tikv.sh.tpl, pkg/exec/run.go
Signed-off-by: qupeng <qupeng@pingcap.com>
Close #1270 and https://github.com/tikv/tikv/issues/9538.
Tests 
1. Start a TiKV cluster with the environment variable set.
2. wget "http://172.16.4.78:50013/debug/pprof/heap?seconds=1" to dump a memory profiling
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> enable but inact memory profiling

pkg/cluster/manager/builder.go, pkg/cluster/operation/action.go, pkg/cluster/operation/operation.go
implement #1187 
Start instances in serial for Raft related components
eg: PD has more strict restrictions on the capacity expansion process, that is, there should be only one node in the peer-join stage at most.
Ref https://github.com/tikv/pd/blob/d38b36714ccee70480c39e07126e3456b5fb292d/server/join/join.go#L179-L191
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes: …
=> cluster: start pd,dm-master in sequentially

pkg/cluster/api/pdapi.go
In https://github.com/pingcap/tiup/pull/1161, we introduce a mechanism which temporarily increase schedule limit during upgrading/reloading tikv, to speed up the upgrade process. But the v3.x of PD doesn't support config schedule limit at all:
Check the current version of PD, only apply the mechanism on v4.x or latter.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes: …
=> Fix the compatibility with PD v3.x

pkg/checkpoint/checkpoint.go
Fix https://github.com/pingcap/tiup/issues/1258
=> Fix the issue that checkpoint can't parse large audit log

pkg/cluster/manager/reload.go
A temporary repair of the issue reported via https://asktug.com/t/topic/69400
The root cause of that problem is that the configuration of Prometheus is inconsistent between the two versions. The previous configuration via ansilbe maybe had problems.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: reload shoud pass through ignore-config-check

components/dm/ansible/import.go, components/dm/ansible/import_test.go, pkg/cluster/manager/deploy.go, pkg/cluster/spec/prometheus.go, pkg/cluster/spec/validate.go
When scaling cluster, tiup will check if there are directories that overlaps each other to avoid conflict. The directories include both imported an new deployed ones.
However, the components deployed by ansible will use the same directory for saving log, which is by designed. At this time, TiUP will report an error if the imported cluster share the same host with different components when you try to scale the cluster.
If the directories conflict are both imported, skip instead of report an error.
Tests 
- Unit test
- No code
Code changes
Side effects
- …
=> Fix the dir check logic on imported cluster

components/playground/instance/tiflash.go, tests/tiup-playground/test_playground.sh
This reverts commit 402079dbc40bc7397d4b136eccacee833c81d898.
We should reverts #902 because it introduced an issue:
https://github.com/pingcap/tiup/issues/1279
BTW, PD itself fixes #888 in https://github.com/tikv/pd/pull/3163
So we don't need #902 anymore with recently released PD.
However, after revert #902, ***TiFlash with old PD (before #3163) may not work with tiup-playground***
Tests 
- Unit test
- No code
Code changes
Side effects
- Need to cherry-pick to the release …
=> Revert "Fix tiflash not start with newest nightly PD (#902)"

pkg/cluster/spec/server_config.go
If a cluster is deployed with the real version of nightly of that day, e.g.: `v5.0.0-nightly-20210405` instead of `nightly`, and when there is a new nightly version overwrites that value (and as we don't keep old nightly versions, the `v5.0.0-nightly-20210405` then no longer available in the repo), a `reload` operation will fail with `unknown version` error.
If the cluster was deployed with `nightly` as version, all seems working correctly.
Check if the cluster version is a nightly version, and use `nightly` as version to query binary paths in repo for the component.
This may, in theory, encounter issues when the deployed nightly version was so far behind the real latest nightly version, the the entry point path of component has changed since it was deployed and last upgraded.
**Note** …
=> fix: workaround for nightly versions in checkConfig()

pkg/cluster/operation/action.go, pkg/cluster/operation/destroy.go, pkg/cluster/spec/pump.go
In the current implementation, node_exporter and blackbox_exporter may be invoked multiple times serially during a single `tiup cluster {start|stop|enable}` processing. 
Instead，those monitor components will be concurrently executed after all components are executed.
The process time of `tiup cluster enable` compared to old's  as follows:
```bash
Enabled cluster `c1` successfully
real    0m13.318s
user    0m2.228s
sys     0m0.319s
Enabled cluster `c1` successfully
real    0m5.687s
user    0m2.176s
sys     0m0.244s
```
Tests 
- Unit test
- No code
Code changes
Side effects
- Possible …
=> cluster: speed up start/enable monitor instances

tests/tiup-cluster/run.sh, tests/tiup-cluster/test_cmd.sh, tests/tiup-cluster/test_cmd_tls_native_ssh.sh, tests/tiup-cluster/test_scale_core.sh, tests/tiup-cluster/test_scale_core_tls.sh, tests/tiup-cluster/test_scale_tools.sh, tests/tiup-cluster/test_scale_tools_tls.sh, tests/tiup-cluster/test_upgrade.sh, tests/tiup-cluster/test_upgrade_tls.sh
Bump tidb versions in test scripts to the latest `v4.0.12` release.
Tests 
- No code
Release notes:
```release-note
NONE
```
=> ci: bump tidb versions in test scripts

pkg/exec/run.go
Some components output JSON or YAML. When the "Starting component..." message is mixed with this
the output needs to be cleaned up before it can be used.
Examples of this are:
```
tiup ctl:v5.0.0 tidb --host 192.168.122.50 schema in mysql | jq
```
```
tiup cluster template > template.yaml
```
This commit changes the output o the "Starting component..." to be send to stderr instead.
Tests 
Run the command with `> /dev/null`, you should now only see the `Starting component...` line.
Release notes:
```release-note
NONE
```
=> Send 'Staring component...' output to stderr

cmd/mirror.go, cmd/root.go
- Fix #1299 
- Fix #1301 
- Fix version handling in `tiup mirror clone` sub command, to support input versions both with and without leading `v`
- Add a `--reset` flag to `tiup mirror set` sub command to reset the mirror to builtin default (`https://tiup-mirrors.pingcap.com/`)
Tests 
Release notes:
```release-note
fix bugs and improve usability of `tiup mirror` sub command.
```
=> tiup: update `mirror` command

doc/dev/README.md
For easier navigation in github.
Fix the links in the doc/dev/README.md file, to use relative links that work on github.
Only adding '../../' for links and correcting some.
Tests
Checked the links on github
- No code
Side effects
None (no code change)
Release notes:
```release-note
NONE
```
=> doc: Updated doc/dev/README.md with relative links

Makefile, tests/Makefile
Added a target into the make file to be able to report available targets within the makefile. This was a tweak of something I saw on - https://stackoverflow.com/questions/4219255/how-do-you-get-the-list-of-targets-in-a-makefile
This help us by documenting known targets.
=> Added and tweaked the method of reporting makefile targets

cmd/mirror.go, pkg/environment/env.go, pkg/repository/mirror.go
I noticed quite a few typos and spelling/grammar problems in errors and other messages.
Tests 
- No code
Documentation updates may be needed in order to make sure the output of tiup matches example output in the docs.
Release notes:
```release-note
NONE
```
=> Fixed a variety of typos

pkg/repository/clone_mirror.go, pkg/repository/progress.go
This fixes #451
Instead of `1.23 MiB p/s` it now shows `1.23 MiB/s`.
This sets a format string for the speed element of the ProgressBar. 
Tests 
Run `tiup mirror clone ...` and inspect output.
Release notes:
```release-note
NONE
```
=> repository/progress: Format progress

pkg/repository/clone_mirror.go, pkg/utils/semver.go
When running `tiup mirror clone ... v5.0.0` it may download a different version of a component if there
is no v5.0.0 for that component. 
If you specify "v9999" it will cause `tiup mirror clone` to download the latest version of all components.
1. Print a message when falling back on the latest version for a component
2. Allow the user to specify "latest" as version to get the latest version.
Tests 
Try `tiup mirror clone /path/to/tiup-mirror --os linux --arch amd64 latest` and `tiup mirror clone /path/to/tiup-mirror --os linux --arch amd4 v5.0.0`.
Release notes:
```release-note
Allow specifying "latest" as version for `tiup mirror clone`
```
=> mirror clone: Improve handling of latest versions

cmd/mirror.go
Currently, there has no explicit command to get the current mirror address.
(An non-explicit way: `cat ~/.tiup/tiup.toml` and it is non-documented)
Add an explicit command to show the current mirror address.
Tests 
```
> ./tiup mirror show
https://tiup-mirrors.pingcap.com/
> ./tiup mirror set /Volumes/T7/local-tiup-mirror 
Successfully set mirror to /Volumes/T7/local-tiup-mirror
> ./tiup mirror show
/Volumes/T7/local-tiup-mirror
```
Release notes:
```release-note
- Add `tiup mirror show` command to display the current mirror address
```
=> mirror: add `tiup mirror show` command to print current mirror address

cmd/root.go, pkg/repository/v1manifest/local_manifests.go, pkg/repository/v1manifest/types.go, pkg/repository/v1manifest/types_test.go
This implements the code part of #1300, document updates may still be needed.
Keep the original error from std libraries, and display an extra warning message if the error is failed loading `root.json` manifest, and provide an instruction for workaround (`tiup mirror set`).
Tests 
Release notes:
```release-note
optimize error messages when `root.json` manifest file fails to load.
```
=> repository: optimize error handing if root.json fails to load

cmd/mirror.go
Fix https://github.com/pingcap/tiup/issues/1320
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that clone will add yanked component

components/playground/playground.go
https://github.com/pingcap/tidb/issues/24176#issuecomment-823865522
Add the `--comments` option to the mysql client connection tips.
Tests 
- Unit test
Code changes
NA
Side effects
NA
NA
Release notes:
```release-note
NONE
```
=> playground: add --comments option to the mysql client connection tips

cmd/mirror.go, components/playground/playground.go, pkg/repository/v1_repository.go, pkg/utils/regexp.go, pkg/utils/regexp_test.go, pkg/utils/semver.go, pkg/utils/semver_test.go, pkg/utils/utils.go
Playground is used to quickly start up a local tidb cluster for developing or testing. If it supports version constraint, it will be more convenient. For example, it can replace the combination of `tiup list` and `tiup playground` for starting up a cluster of the latest version of a major version.
implement basic semver constraint `*` `x` `^` `~` just like how https://semver.npmjs.com/ calculates, and support short form of version
In all versions that satisfies version constraint, playground will find the latest one to start up.
*`v` can be omitted*
e.g.
`5` = `5.0` =  `5.0.0`
`5.*` = `5.x` = `5.*.*` = `5.x.x` = `^5` = `^5.0` = `^5.0.0`
`5.0.x` = `5.0.*` = `~5` = `~5.0` = `~5.0.0`
prereleases always be ignored unless use constraint like `^5.0.0-rc` or `~5.0.0-rc` or `5.0.0-rc`
preview: …
=> playground: support semver constraint

cmd/mirror.go, tests/tiup-playground/test_playground.sh
- Optimize some help messages and command outputs to better describe what's going on when users try to initialize a new repository
- Extend relative paths to absolute ones on `mirror set`
Release notes:
```release-note
tiup: optimize some mirror subcommands
```
=> tiup: optimize some mirror subcommands

pkg/repository/mirror.go
Set user-agent for HTTP requests make by repository, the default is `grab` now.
Release notes:
```release-note
repository: set user agent for mirror requests
```
=> repository: set user agent for mirror requests

pkg/cluster/operation/check.go
Fix #1332 and add warning to Debian/Ubuntu users.
Our components should be working on recent Debian and Ubuntu systems, we have some development servers running Debian and Ubuntu systems and are working well, but we don't yet have them fully tested, our full test suits are only run on CentOS 7 as of now.
- Fix version check for some RHEL systems
- Add warnings for Debian and Ubuntu systems
- Check versions of Debian and Ubuntu systems and report error for very old releases
The change does not matters that much as the `check` process is optional for users trying to deploy a cluster.
Tests 
Release notes:
```release-note
cluster: fix and optimize os version check
```
=> cluster: fix and optimize os version check

install.sh, pkg/cluster/template/install/local_install.sh.go
Fix #1287 
Tests 
Release notes:
```release-note
install.sh: check depends before downloading package
```
=> install.sh: check depends before downloading package

components/cluster/command/display.go, pkg/cluster/manager/display.go, pkg/cluster/operation/operation.go
This adds JSON output for the `tiup cluster display` command. This makes it easier to parse the output and use it in other programs.
https://github.com/pingcap/tiup/issues/1355
This puts the info in a struct and uses encoding/json to format this as JSON
Tests 
`tiup cluster display mycluster`
`tiup cluster display --json mycluster`
Side effects
Release notes:
```release-note
Support JSON output for the `tiup cluster display` command
```
=> cluster: add JSON output option for display

CHANGELOG.md, pkg/version/version.go
=> bump version 1.4.3

pkg/cluster/manager/scale_in.go
Fix #1354 
It's reasonable to scale in the remaining tispark worker node in such situation
Release notes:
```release-note
cluster: allow scale-in when there is no tispark master node
```
=> cluster: allow scale-in when there is no tispark master node

pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go
* make error message for port range more clear to users, can help them to solve problems more quickly.
* modify port range error message 
Tests 
- No code
Code changes
Side effects
Release notes:
NONE
=> cluster: make port check error message more clear to users.

components/playground/instance/tikv.go
Signed-off-by: YangKeao <keao.yang@yahoo.com>
In #1361, I forgot to modify the same environment variable for `playground`. 
As discussed in tikv/tikv#10150, this option has brought some problems like tikv/tikv#10131 and other issues report (on asktug). And it could also cause performance regression or memory leaking (though, it seems not to be measuable).
=> modify MALLOC_CONF for playground

pkg/cluster/spec/parse_topology_test.go, pkg/cluster/spec/spec.go
Fix https://github.com/pingcap/tiup/issues/1375
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that the global absolute log dir path not generate correctly

pkg/cluster/api/pdapi.go, pkg/cluster/manager/display.go, pkg/cluster/manager/scale_out.go
From https://docs.pingcap.com/tidb/stable/configure-placement-rules:
> After enabling Placement Rules, the previously configured max-replicas and location-labels no longer take effect. To adjust the replica policy, use the interface related to Placement Rules.
Fix https://github.com/pingcap/tiup/issues/1371
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE …
```
=> Don't check labels when user enable placement-rule

pkg/cluster/spec/cdc.go
`gc-ttl` and `tz` should be editable in the command line parameters of cdc server
add `vaildate:xx:editable` to these two parameters
Tests 
- Unit test
Release notes:
```release-note
Make `tc-ttl` and `tz` editable in cdc server spec
```
=> cluster: make two configs in cdc spec editable

pkg/cluster/manager/check.go
Fix #1364 
Code changes
Release notes:
```release-note
cluster: fix wrong SELINUX disabling config
```
=> cluster: fix wrong SELINUX disabling config

pkg/cluster/operation/upgrade.go
The upgrade process of TiKV nodes may be skipped unexpectedly if increasing schedule limit failed
Tests 
Release notes:
```release-note
cluster: fix tikv not upgraded on error increasing schedule limit
```
=> cluster: fix tikv not upgraded on error increasing schedule limit

pkg/cluster/manager/display.go
The indent of `TLS encryption: enabled` line in display output is incorrect
Replace the tab with whitespace
Tests 
Release notes:
```release-note
cluster: fix wrong indent in display for TLS enabled clusters
```
=> cluster: fix wrong indent in display

components/cluster/command/template.go, embed/templates/examples/local.yaml
Fixes #1403 
Adds a new `local.yaml` topology file and `tiup cluster template --local` option to print a template that will deploy a cluster entirely to the local machine.
Tests 
I used the template output file to successfully deploy a cluster.
Code changes
n/a
Side effects
n/a
https://docs.pingcap.com/tidb/stable/tiup-component-cluster-template should be updated to describe the existence of this new type of template.
Release notes:
```release-note
Add a new `--local` option to `tiup cluster template`. This prints a simple topology template that will deploy a very basic cluster, with one instance of each component, to the user's local machine. …
```
=> Added tiup cluster template --local

cmd/root.go, components/cluster/command/root.go, pkg/cluster/manager/display.go
Show deploy user in `display` output.
Tests 
Release notes:
```release-note
cluster: add deploy user to display output
```
=> cluster: add deploy user to display output

pkg/cluster/clusterutil/cluster_name.go
fix #1399  #1400 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: support char dot(.) in cluster name

.github/workflows/release-tiup.yaml
Fix build error in release CI
Tests 
Release notes:
```release-note
NONE
```
=> *: fix release build

pkg/cluster/spec/spec_test.go, pkg/cluster/template/scripts/cdc.go
solve the problem that makes tiup deploy cdc v5.0.0 failed
adjust the version check logic, add new tests
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
NONE
=> spec: fix cdc data dir version issue

components/cluster/command/check.go, components/cluster/command/deploy.go, components/cluster/command/scale_out.go, components/dm/command/deploy.go, components/dm/command/scale_out.go, pkg/cliutil/ssh.go, pkg/cluster/manager/check.go, tests/tiup-cluster/script/cmd_subtest.sh
implement #1393 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: check, deploy support use ssh-agent instead of identity-file

pkg/cluster/executor/ssh.go, pkg/cluster/executor/ssh_test.go
Fix the issue of missing the port in ssh connect args
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster/executor: fix the issue of native ssh connect refused if port not 22

components/cluster/command/root.go, components/dm/ansible/import_test.go, components/dm/command/import.go, components/dm/command/root.go, pkg/cluster/ansible/config.go, pkg/cluster/ansible/service.go, pkg/cluster/ctxt/context.go, pkg/cluster/executor/local_test.go, pkg/cluster/manager/basic.go, pkg/cluster/manager/check.go, pkg/cluster/manager/cleanup.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/destroy.go, pkg/cluster/manager/display.go, pkg/cluster/manager/exec.go, pkg/cluster/manager/patch.go, pkg/cluster/manager/reload.go, pkg/cluster/manager/scale_in.go, pkg/cluster/manager/scale_out.go, pkg/cluster/manager/transfer.go, pkg/cluster/manager/upgrade.go, pkg/cluster/operation/operation.go, pkg/cluster/spec/grafana_test.go, pkg/cluster/task/init_config_test.go, pkg/cluster/task/task.go, pkg/cluster/task/tls.go
Close #649 
The concurrency is default to `5` as set in command line argument, and is the number of CPU threads for `task` if not set.
Tests 
Code changes
Release notes:
```release-note
task: implement parallel concurrency limit
```
=> task: implement parallel concurrency limit

.github/workflows/integrate-cluster-cmd.yaml, .github/workflows/integrate-cluster-scale.yaml, .github/workflows/integrate-dm.yaml, components/dm/spec/topology_dm.go, components/dm/spec/topology_dm_test.go, pkg/cluster/ansible/import.go, pkg/cluster/ansible/import_test.go, pkg/cluster/ansible/inventory.go, pkg/cluster/manager/check.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/manager.go, pkg/cluster/manager/scale_out.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/spec_manager_test.go, pkg/cluster/spec/validate_test.go
Implement #1397 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster,dm:  auto detect cpu arch

pkg/cluster/manager/transfer.go
When execute the command `tiup cluster exec <cluster-name> -R tiflash`, tiup will do nothing because it can't deal with tiflash node correctlly.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that exec command doesn't handle tiflash nodes

embed/templates/scripts/run_tidb.sh.tpl
Fix https://github.com/pingcap/tiup/issues/1440
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that slow log position not change with LogDir

components/cluster/command/import.go, pkg/cluster/ansible/config.go, pkg/cluster/executor/ssh.go, pkg/cluster/manager/builder.go, pkg/cluster/manager/check.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/manager.go, pkg/cluster/manager/reload.go, pkg/cluster/task/builder.go, pkg/cluster/task/ssh.go
Close #1366 
Use the value of `--wait-timeout` argument for SSH operations. Note that default timeout of SSH commands has changed from hard coded 60s to the default value of `--wait-timeout` of 120s.
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> *: use `--wait-timeout` for SSH command opeartions with easyssh

pkg/cluster/manager/check.go, pkg/cluster/operation/check.go
fix #1457 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster/check: apply thp fix only if thp found

.github/workflows/integrate-cluster-cmd.yaml, embed/templates/config/prometheus.yml.tpl, pkg/cluster/spec/prometheus.go, pkg/cluster/template/config/prometheus.go
I'm deploying a cluster of version 3.0.12, but failed to start it. The error message as below:
```bash
Error: init config failed: n1:9090: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@n1:22' {ssh_stderr:   FAILED: "/home/tidb/deploy/prometheus-9090/conf/tikv.accelerate.rules.yml" does not point to an existing file
, ssh_stdout: Checking /home/tidb/deploy/prometheus-9090/conf/prometheus.yml
, ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin /home/tidb/deploy/prometheus-9090/bin/prometheus/promtool check config /home/tidb/deploy/prometheus-9090/conf/prometheus.yml}, cause: Process exited with status 1: check config failed
```
This shows the Prometheus package missing the rule file `tikv.accelerate.rules.yml`, then  found this file was introduced in …
=> cluster/prometheus: tikv accelerate rules if version 3

pkg/repository/clone_mirror.go
When running something like this:
```
tiup mirror clone /tmp/tidb_mirror -a amd64 --prefix v5.1.0 --os linux
tiup mirror set /tmp/tidb_mirror
tiup mirror clone /tmp/tidb_mirror -a amd64 --prefix v5.1.0 --os linux
```
This results in metadata being changed/corrupted.
Then the next `tiup mirror clone ...` results in:
```
Error: read manifest from mirror(/tmp/tidb_mirror) failed: not enough signatures (0) for threshold 1 in timestamp.json
```
This can easily be fixed with `tiup mirror set ...`, but it is best to
avoid this. And also cloning from self is probably not what the user
wanted in the first place. So adding the source to the output to make
this easier to spot.
Related: https://tidbcommunity.slack.com/archives/C019S7HLP61/p1625059913130200
Tests 
- Manual test (add detailed scripts …
=> clone_mirror: refuse to clone from self

cmd/list.go
Update manifest errors in `list` command should not be returned, change to warning
Reason:
1. If the manifest is already available locally, the local component
should be listed, but output warning
2. If there is no local manifest, in case of update manifest error,
init manifest will also fail and will not continue
https://github.com/pingcap/tiup/issues/1465
=> Update manifest errors in list component should not be returned, change to warning

pkg/cluster/operation/check.go
Close #1449 
Adjust the error message to avoid formatting issues
Tests 
Release notes:
```release-note
NONE
```
=> cluster: adjust error message of selinux check

pkg/cluster/manager/scale_in.go
Close #1453 
Release notes:
```release-note
NONE
```
=> cluster: print more clear warning when scale in with `--force`

components/playground/main.go, components/playground/playground.go, pkg/repository/v1_repository.go
Introduced in #1325, hopefully fix #1481
If the user has any of the `binpath` arguments set, we assume the user is a developer testing their latest code, so use the latest possible version for other components if needed. The version is resolved with `linux-amd64` as platform as it's the platform with every released versions available, and ignore the real platform the user is using. This, however, may cause issue if the user didn't specify `binpath` for **all components** used, and the latest version is not available for those components in the user's platform. In such cases, the user should either specify `binpath` for all the remaining components as well, or set a version that available for those components.
Tests 
I have **not** tested this PR as I don't have access to any Apple M1 …
=> playground: ignore version check error in some cases

embed/templates/config/grafana.ini.tpl
Close #1490 
Release notes:
```release-note
cluster: distinguish cookie names of multiple grafana instances
```
=> cluster: distinguish cookie names of multiple grafana instances

components/playground/main.go
This sets the terminal title to "TiUP Playground: <name>" where name
is the last part of the datadir. With `tiup -T foobar playground` etc.
this name can be set. Also `tiup client` uses the same names.
Tests 
Release notes:
```release-note
TiUP Playground now sets the terminal title to the name of the playground
```
=> playground: Set terminal title

cmd/mirror.go, cmd/root.go, components/cluster/command/root.go, components/playground/main.go, pkg/cluster/api/binlog.go, pkg/cluster/api/dmapi.go, pkg/cluster/api/pdapi.go, pkg/cluster/spec/util.go, pkg/cluster/template/install/local_install.sh.go, pkg/repository/store/txn.go, pkg/telemetry/telemetry.go, pkg/telemetry/telemetry_test.go, pkg/utils/http_client.go
The timeout setting (hard coded 2s) was not taking affect. It was introduced in #1327 
- Disable telemetry in `local_install.sh` as offline installations does not need telemetry at all (they typically don't have access to the Internet)
- Add support of context in the `HTTPClient` in `utils` to handle timeout correctly.
Tests 
- Unit test
Code changes
Release notes:
```release-note
NONE
```
=> Fix telemetry timeout

pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go
When user scale out new instance on a host where an imported instance already exist, and the global options set monitor paths to where the imported instance is located (and the log dir overlaps with data dir), the dir overlap check fails.
Ignore log dir overlapping if one of the compared dir is data dir of a monitor instance, as node_exporter and blackbox_exporter don't need data dir at all, the field is only kept for compatibility with tidb-ansible as the field was available there.
Tests 
- Unit test
Side effects
Release notes:
```release-note
cluster: ignore exporters when check data_dir overlap
```
=> ignore exporters when check data_dir overlap

CHANGELOG.md, pkg/version/version.go
bump version 1.5.4
Release notes:
```release-note
NONE
```
=> bump version 1.5.4

pkg/cluster/manager/reload.go
Fix #1507 
Tests 
Release notes:
```release-note
NONE
```
=> cluster: skip updating topology when reload with --skip-restart

components/dm/command/scale_in.go, components/dm/spec/logic.go, components/dm/spec/topology_dm.go, pkg/cluster/manager/builder.go, pkg/cluster/manager/cleanup.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/reload.go, pkg/cluster/manager/upgrade.go, pkg/cluster/operation/action.go, pkg/cluster/operation/destroy.go, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/cdc.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/pd.go, pkg/cluster/spec/prometheus.go, pkg/cluster/spec/pump.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tidb.go, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/tikv.go, pkg/cluster/spec/tispark.go, pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go, tests/tiup-dm/test_cmd.sh
If user wants to deploy instances from multiple clusters onto one host, the monitor agents from those clusters may conflict. This PR add an optional flag in instance's spec to indicate that monitor agent is not needed for this cluster on the host. Typically this means there is already an agent deployed by another cluster.
The rendering process of Prometheus config is not changed, so that if there is already an agent, monitoring metrics in Prometheus should be fine.
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: add ability to ignore monitor agent for instances

components/playground/main.go, pkg/cluster/executor/local.go, pkg/cluster/executor/ssh.go, pkg/cluster/operation/check.go
sudo error when use devtoolset
```
[root@ip-172-16-5-33 ~]# /opt/rh/devtoolset-8/root/usr/bin/sudo -l
/var/tmp/sclk5fzvz: line 8: -l: command not found
```
fix: #1515 
use `/usr/bin/sudo` insted of `sudo`
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Use absolute path for sudo command #1515

components/playground/playground.go
Adjust --comments position，simple delete `（no password）`
The reason is that more commands can be copied and pasted
Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Adjust --comments position

docker/control/Dockerfile, docker/node/Dockerfile, pkg/cluster/executor/local.go, pkg/cluster/executor/ssh.go
In `golang:1.16` (the image we use to build node container in Github Actions), `ss` command seems not installed by default anymore.
- Add `/bin` and `/sbin` to the `PATH` when running commands.
- Install `iproute2` in docker images
Release notes:
```release-note
NONE
```
=> tests: fix CI tests

pkg/cluster/manager/basic.go
Add a warning description when the cluster restarts
Help understand the impact of restart,
Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Add some desc when execute `tiup-cluster restart`

pkg/repository/v1_repository.go
tiup list takes too long time
update ComponentManifests simultaneously when tiup list
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> update ComponentManifests simultaneously when tiup list

pkg/cluster/operation/check.go
Fix #1450 
Release notes:
```release-note
NONE
```
=> cluster: update os check

pkg/cluster/audit/audit.go, pkg/cluster/audit/audit_test.go
Fix #1525 
Tests 
Release notes:
```release-note
NONE
```
=> cluster: reverse the order of audit log list

pkg/cluster/spec/spec.go
Upgrade tikv first then cdc, to be compatible with v5.2.0 TiCDC.
Change upgrade order.
```
tiup cluster deploy cdc-cluster1 v5.0.3 top1.1kv.yml -y && tiup cluster start cdc-cluster1 -y
./tiup-cluster upgrade cdc-cluster1 5.2.0 -y
...
+ [ Serial ] - UpgradeCluster
Upgrading component pd
Restarting instance 172.16.5.33:47902
Restart instance 172.16.5.33:47902 success
Upgrading component tikv
Restarting instance 172.16.5.33:47906
Restart instance 172.16.5.33:47906 success
Upgrading component tidb
Restarting instance 172.16.5.33:47904
Restart instance 172.16.5.33:47904 success
Upgrading component cdc
Restarting instance 172.16.5.33:47913
Restart instance 172.16.5.33:47913 success
Upgrading component prometheus
Restarting instance …
```
=> cluster: upgrade tikv first then cdc

pkg/environment/env.go, pkg/exec/run.go, pkg/repository/v1_repository.go
cant run component after remove tiup mirror
remove network request before exec component
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> remove network request before enter component 

pkg/exec/run.go, pkg/logger/log/verbose.go
Sometimes some information output to stdout  mistakenly, for example: after `tiup cluster template > topology.yaml` ,the file has lines like "verbose: xxx"
change to stderr
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> use stdout on update and verbose information

components/cluster/command/prune.go, pkg/cluster/operation/destroy.go
Fix #1546 
When `--force` is set, errors are ignored when stopping and deleting the instance.
Release notes:
```release-note
NONE
```
=> cluster: add `--force` argument for `prune` subcommand

cmd/list.go, pkg/repository/v1_repository.go
`tiup playground` cant run offline
do'nt download manifest files from Internet when specify version
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> support start playground offline when specify version

pkg/repository/v1_repository.go, pkg/repository/v1manifest/key_store.go
No need to update root.json every time update something
remote update of root.json before get timestamp.json, add it after get snapshot.json
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> update root.json only when necessary

components/bench/main.go, components/bench/tpcc.go, components/bench/tpch.go
when cannot connect to DB, tiup-bench panic .  fix #1548 
instead of  panic, just exit(1) and warning
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix panic when cant openDB on tiup-bench

pkg/cluster/spec/pd.go
Fixes  https://github.com/pingcap/tiup/issues/1563
invoke function `WithNumaNode` while generating PD config file
Tests 
- Unit test
- No code
Side effects
Release notes:
```release-note
NONE
```
=> Fix the issue that lost numa_node when generating PD config

embed/templates/config/grafana.ini.tpl, pkg/cluster/spec/grafana.go, pkg/cluster/template/config/grafana.go
Add `default_theme`, `org_name`, `org_role` as supported configurations for Grafana.
Add sub-targets under grafana_servers in topology.yaml which is used as the configuration file for `tiup-cluster deploy` command.
Sample topology.yaml: 
```yaml
global:
user: "root"
ssh_port: 22
deploy_dir: "/root/tidb-deploy"
data_dir: "/root/tidb-data"
arch: "amd64"
monitored:
node_exporter_port: 9100
blackbox_exporter_port: 9115
pd_servers:
- host: $HOST_IP
tidb_servers:
- host: $HOST_IP
port: 4000
status_port: 10080
deploy_dir: "/root/tidb-deploy/tidb-4000"
log_dir: "/root/tidb-deploy/tidb-4000/log"
tikv_servers:
- host: $HOST_IP
port: 20160
status_port: 20180
deploy_dir: "/root/data1/tidb-deploy/tikv-20160"
data_dir: "/root/tidb-data/tikv-20160"
log_dir: "/root/tidb-deploy/tikv-20160/log" …
```
=> pkg/cluster/spec: add supported configuration for grafana

embed/templates/scripts/run_alertmanager.sh.tpl
tiup deployed alertmanager creating alerts with unspecified external-url
the template generating alertmanager config
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> add --external-url for alertmanager

pkg/cluster/manager/deploy.go, pkg/cluster/manager/scale_out.go
- tiup cluster report errror "TiFlash %s is not supported in TLS enabled cluster" when not enable TLS
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix mistake error about TLS

pkg/cluster/manager/manager.go
Introduced in #1423 
```
$ tiup cluster deploy aws-test-v530 v5.3.0 topo.yaml -i id_rsa -u centos
Starting component `cluster`: /home/centos/.tiup/components/cluster/v1.6.0/tiup-cluster deploy aws-test-v530 v5.3.0 topo.yaml -i id_rsa -u centos
+ Detect CPU Arch
- Detecting node 172.31.38.22 ... ⠼ Shell: host=172.31.38.22, sudo=false, command=`uname -m`
- Detecting node 172.31.40.219 ... ⠼ Shell: host=172.31.40.219, sudo=false, command=`uname -m`
+ Detect CPU Arch
+ Detect CPU Arch
- Detecting node 172.31.38.22 ... Done
- Detecting node 172.31.40.219 ... Done
- Detecting node 172.31.46.81 ... Done
- Detecting node 172.31.42.64 ... Done
- Detecting node 172.31.37.178 ... Done
- Detecting node 172.31.36.128 ... Done
- Detecting node 172.31.34.177 ... Done
- Detecting node 172.31.41.3 ... …
```
=> cluster: fix wrong keys detecting host arch

pkg/cluster/spec/tiflash.go
The status TiFlash reports could be `Ready` before it becomes `Running`, so the current error message could be confusing.
Adjust the error message.
Tests 
Release notes:
```release-note
NONE
```
=> cluster: update error message of tiflash not ready

components/cluster/command/deploy.go, components/cluster/command/display.go, components/cluster/command/root.go, components/cluster/command/scale_out.go, components/dm/command/deploy.go, components/dm/command/root.go, components/dm/command/scale_out.go, pkg/cluster/ansible/config.go, pkg/cluster/audit/audit.go, pkg/cluster/manager/builder.go, pkg/cluster/manager/check.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/destroy.go, pkg/cluster/manager/display.go, pkg/cluster/manager/exec.go, pkg/cluster/manager/list.go, pkg/cluster/manager/manager.go, pkg/cluster/manager/patch.go, pkg/cluster/manager/reload.go, pkg/cluster/manager/scale_in.go, pkg/cluster/manager/scale_out.go, pkg/cluster/manager/transfer.go, pkg/cluster/manager/upgrade.go, pkg/cluster/operation/operation.go, pkg/cluster/task/builder.go, pkg/cluster/task/step.go, pkg/logger/log/log.go, pkg/tui/progress/display_props.go
Partially implement #1208
This is an experimental feature and may due to changes and refactors in the future.
Also add an optional `TIUP_AUDIT_ID` environment variable that will be appended to timestamp based audit id string.
- Add a global argument `--format` to define output format and replaces `--json`.
- Make task outputs and loggers support JSON format
The output will be multiple JSON lines, and the last line is a `{"exit_code": 0}` (or other codes) printed to stderr.
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: implement pure JSON output mode (experimental)

pkg/cluster/task/step.go
cluster: fix progressBar return nil
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix progressBar return nil

pkg/cluster/operation/destroy.go, pkg/cluster/operation/operation.go, pkg/cluster/operation/scale_in.go, pkg/cluster/operation/upgrade.go
Close #1616 
Add 2 new environment variables in `pkg/cluster/operation`:
- `SKIP_SCALEIN_TOPO_CHECK`: If not empty, skip topology sanity check so that it's possible to delete the last PD, the last TiKV and the last TiSpark master node with worker node remains
- `FORCE_PD_ENDPOINTS`: A common separated list of available PD endpoints. Used to overwrite pd list in the topology, so that when there is no PD available in the topology `tiup-cluster` acknowledged but some are working in the actual cluster, it's still possible to scale in other instances
These two environment are **very dangerous** and are highly possible to make the cluster broken, so they are not supposed to be documented in any public documentations, they are only supposed to be used by developers and expert users who know 100% …
=> cluster: add envs to skip topology sanity check in scale-in process

components/playground/main.go
playground db.host,db.port,pd.host changed to db.Host, db.Port and pd.Host,  need to be restored
https://github.com/pingcap/tiup/issues/1632
to
Tests 
- No code
Code changes
Release notes:
```release-note
NONE
```
=> playground: fix wrong flag name

components/playground/main.go, doc/user/playground.md
Replace `--monitor` in various places
Tests 
- No code
Release notes:
```release-note
NONE
```
=> Adjust for deprecation of `--monitor`

pkg/cluster/task/step.go, pkg/logger/log/log.go, pkg/logger/log/verbose.go, pkg/tui/progress/display_props.go
A following up of #1617 and related to #1208
- Support `plain`/`text` output mode, that prints everything as plain text.
- Support custom output writer, make it possible for the `log` package to output `stdout` and `stderr` to different writers than system console
Tests 
Code changes
Release notes:
```release-note
NONE
```
=> *: implement plain text output and custom output writer

pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go
If both clusters have the same monitor deploy dir set in their topology files, scaling out one with `ignore_exporter: true` to a shared host still reporting an directory conflict error.
Ignore dir conflict error if both sides are monitor directories and one of them is marked as `ignore_exporter`.
This is a following up of #1492 
Tests 
- Unit test
Release notes:
```release-note
NONE
```
=> cluster: skip dir conflict if node marked ignore_exporter

components/playground/ngmonitoring.go, components/playground/playground.go
- close #1647 
- boot ng-monitoring when boot monitor
- boot monitor after tidb instance
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: add support of ng-monitoring

pkg/cluster/spec/monitoring.go, pkg/cluster/spec/monitoring_test.go
- close #1615 
user may use like this:
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: add additional prom scrape_configs

pkg/cluster/spec/monitoring.go
Fix #1653 
Add hosts of DM nodes to the host list so that prometheus config will be rendered with them as `node_exporter` targets.
=> dm: add dm hosts to node_exporter list

go.mod, go.sum
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> *: fix slow ssh connect when using buildin ssh

embed/templates/scripts/run_alertmanager.sh.tpl, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/spec.go, pkg/cluster/template/scripts/alertmanager.go
close #1633 
support alertmanager configuration Listen Host
add new field listen_host to Alertmanager
```
alertmanager_servers:
- host: 172.16.7.147
listen_host: 0.0.0.0
ssh_port: 22
```
if set listen_host: 0.0.0.0 
*run script*
```shell
cat run_alertmanager.sh 
#!/bin/bash
set -e
DEPLOY_DIR=/home/tidb-deploy/alertmanager-9093
cd "${DEPLOY_DIR}" || exit 1
exec > >(tee -i -a "/home/tidb-deploy/alertmanager-9093/log/alertmanager.log")
exec 2>&1
exec bin/alertmanager/alertmanager \
--config.file="conf/alertmanager.yml" \
--storage.path="/home/tidb-data/alertmanager-9093" \
--data.retention=120h \
--log.level="info" \
--web.listen-address="172.16.7.147:9093" \
--web.external-url="http://172.16.7.147:9093" \
--cluster.peer="0.0.0.0:9094" \
```
Tests 
- Manual test (add detailed scripts or …
=> cluster: support alertmanager configuration Listen Host

pkg/cluster/operation/check.go
close #1636 
```
Currently tiup cluster check does not support checking io scheduler settings, please submit a new issue to support him.
The problem of cpufreq check result output will be completed in this issue.
```
add CPU frequency check output
```
192.168.1.1  cpu-governor  Pass    CPU frequency governor is performance
192.168.1.1  cpu-governor  Warn    Unable to determine current CPU frequency governor policy
192.168.1.1  cpu-governor  Fail       CPU frequency governor is powersave, should use performance
```
Tests 
```shell
./tiup-cluster check ~/topology.yaml
```
*test with VM*
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: check add CPU frequency check output

.codecov.yml, .github/workflows/integrate-cluster-cmd.yaml, .github/workflows/integrate-cluster-scale.yaml, .github/workflows/integrate-dm.yaml, .github/workflows/integrate-playground.yaml, .github/workflows/integrate-tiup.yaml, .github/workflows/release-tiup.yaml, tests/tiup-cluster/test_scale_core_tls.sh, tests/tiup-cluster/test_scale_tools_tls.sh, tests/tiup-cluster/test_upgrade_tls.sh
Run integrate tests daily to update codecov stats, as we don't run full tests after merge, the codecov reports are missing some stats.
=> ci: run integrate tests daily to update codecov stats

components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, pkg/cluster/ansible/service_test.go, pkg/cluster/spec/tiflash.go
https://github.com/pingcap/tiup/issues/1671
Check the TiFlash version, remove the runAsDaemon config if TiFlash is in new version(>=v5.4.0) or the nightly version.
Tests 
- Unit test
Release notes:
```release-note
NONE
```
=> Remove the config 'runAsDaemon' from tiflash.toml

cmd/mirror.go, pkg/repository/model/model.go, pkg/repository/model/publish.go, server/rotate/component.go, server/rotate/root.go, server/rotate/server.go
Change the owner of a component.
Use a process like rotating `root.json`:
- On server side, the server admin run `tiup mirror transfer-owner` command to initialize a owner transfer process
- The existence of new owner is checked, then open a temp HTTP server to serve the `component.json`
- Client with the new owner's private key use `tiup mirror sign` to sign that temp URL
- Server validate the signature received and update `component.json` along with `index.json`
The process is a pure administration operation, and could be used without the participate of old owner of the component, so that it also works if the old owner is absent for long time and can not be contacted.
The new owner must be granted before the transfer.
Tests 
Code …
=> tiup/mirror: add ability to change owner of a component

embed/templates/scripts/run_drainer.sh.tpl, pkg/cluster/spec/drainer.go
close #1677 #1680 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix wrong default initial-commit-ts in drainer

pkg/cluster/spec/monitoring.go, pkg/cluster/spec/monitoring_test.go
close #1628 
render cluster name when monitoring_servers.rule_dir  is set
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: render cluster name when monitoring_servers.rule_dir  is set

embed/examples/dm/topology.example.yaml
include new config to `tiup dm template --full`
Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
Add new configuration to `tiup dm template --full` 
```
=> dm: add new config to dm template

cmd/root.go
- close #862 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> resolve flag conflicts between tiup and component

components/bench/Makefile, components/client/Makefile, components/cluster/command/start.go, components/cluster/command/test.go, embed/templates/scripts/run_tidb.sh.tpl, examples, go.mod, go.sum, pkg/cluster/spec/tidb.go, pkg/cluster/template/scripts/tidb.go, pkg/crypto/rand/passwd.go, pkg/crypto/rand/passwd_test.go
Close #1660 
An `--init` argument is added to `tiup-cluster start` subcommand, it generates a 18 chars long random password and set it to the `root@'%'` user.
Tests 
Release notes:
```release-note
NONE
```
=> cluster: support init root password

pkg/cluster/manager/check.go, pkg/cluster/manager/scale_out.go, pkg/cluster/spec/parse_topology.go, pkg/cluster/spec/parse_topology_test.go
close #1697 
scale-out topology cannot inherit the global configuration
Tests 
- Unit test
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: scale-out topology cannot inherit the global configuration

components/dm/spec/topology_dm.go, pkg/cluster/ansible/import_test.go, pkg/cluster/ansible/test-data/meta.yaml, pkg/cluster/spec/grafana.go, pkg/cluster/spec/grafana_test.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/spec_manager_test.go
- support configure grafana in server_configs
- close #1504 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: support configure grafana in server_configs

embed/examples/cluster/minimal.yaml, embed/examples/cluster/multi-dc.yaml, embed/examples/cluster/topology.example.yaml, pkg/cluster/manager/upgrade.go, pkg/cluster/spec/monitoring.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/validate.go
- close #1690 
- also fix data_dir is wrong when upgrade CDC on some version
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: ngm server default enabled during deployment

doc/user/mirrors.md, pkg/repository/clone_mirror.go
- `tiup mirrors` doesn't exist, but `tiup mirror` does
- Typo: `mirros` → `mirrors`
- Typo: `expirsAt` → `expiresAt`
Tests 
- No code
Release notes:
```release-note
NONE
```
=> mirror: Fix typos and naming

pkg/cluster/manager/deploy.go
Adjust the hint displayed after deploy to add `--init` argument.
=> cluster/deploy: adjust hint to add --init

embed/templates/scripts/run_drainer.sh.tpl, pkg/cluster/ansible/service.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/spec.go, pkg/cluster/template/scripts/drainer.go
- close #1682 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: use initial_commit_ts in drainer config file instead of start script

cmd/root.go, components/cluster/command/root.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> not record "tiup __complete" in telemetry and audit log

pkg/cluster/manager/destroy.go, tests/tiup-cluster/script/upgrade.sh, tests/tiup-dm/test_upgrade.sh
Close #1722 
Add a significant warning when the users tries to destroy a cluster. It requires the user to input a long sentence to confirm (instead of a simple "Y/y" letter) so it's highly not possible for the user to destroy a cluster by mistake.
Tests 
Release notes:
```release-note
NONE
```
=> cluster: add significant warning destroying a cluster

pkg/cluster/manager/basic.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/scale_out.go, pkg/cluster/manager/tls.go
close #1733 
Ignore the nightly version when judging whether the TiFlash version supports TLS
Tests 
```shell
./tiup-cluster deploy test nightly ~/topology.yaml
./tiup-cluster start test 
./tiup-cluster tls test enable 
```
Release notes:
```release-note
NONE
```
=> cluster: Ignore the nightly version when judging whether the TiFlash version supports TLS

pkg/cluster/operation/check.go
Mark Amazon Linux 2 as supported
- https://aws.amazon.com/blogs/startups/achieve-better-price-to-performance-for-tidb-graviton2-processors/
- https://aws.amazon.com/ec2/graviton/
- https://aws.amazon.com/amazon-linux-2/
Tests 
Release notes:
```release-note
Amazon Linux is no longer marked as unsupported
```
```
$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
```
$ rpm -E %{rhel}
7
```
```
ip-**********.eu-central-1.compute.internal  os-version    Fail    os vendor amzn not supported
```
=> Add Amazon Linux 2 as supported OS

pkg/cluster/manager/check.go, pkg/cluster/manager/manager_test.go
close #1724 
Use SetString to remove duplicate messages
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: deduplicate the check result

pkg/cluster/executor/local.go, pkg/cluster/executor/local_test.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/monitoring.go
Fix #1268 
Adjust commands to use `'` for `sed` instead of `"` and properly escape `"` in commands.
Tests 
Release notes:
```release-note
NONE
```
=> cluster: fix malformed commands in local executor

cmd/root.go, components/playground/grafana.go, components/playground/instance/drainer.go, components/playground/instance/pd.go, components/playground/instance/process.go, components/playground/instance/pump.go, components/playground/instance/ticdc.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/monitor.go, components/playground/ngmonitoring.go, components/playground/playground.go, pkg/environment/env.go, pkg/exec/run.go
- how tiup run component is different with playground. The old PrepareCommand should be splited to two simple function
- close #1732 
- refactor how tiup and playground run component
- use component exit code as tiup exit code
- make playground show version of component
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tiup/playground: refactor RunComponent

components/dm/command/prune.go, components/dm/command/scale_in.go, components/dm/spec/logic.go, embed/templates/config/prometheus.yml.tpl, embed/templates/scripts/run_dm-master.sh.tpl, embed/templates/scripts/run_dm-master_scale.sh.tpl, embed/templates/scripts/run_dm-worker.sh.tpl, pkg/cluster/template/scripts/dm_master.go, pkg/cluster/template/scripts/dm_worker.go, pkg/utils/utils.go
- close #1588
Tests 
- deploy display scale-in scale-out works
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> dm: add TLS support

components/bench/tpcc.go, components/bench/tpch.go
- fix #1754 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> bench: update cmd flags of go-tpc v1.0.8

components/cluster/command/check.go, components/dm/spec/topology_dm.go, components/dm/spec/topology_dm_test.go, pkg/cluster/ansible/inventory.go, pkg/cluster/manager/builder.go, pkg/cluster/manager/check.go, pkg/cluster/manager/deploy.go, pkg/cluster/manager/manager.go, pkg/cluster/manager/scale_out.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/spec_manager_test.go, pkg/cluster/spec/validate_test.go
Previously, the host would use the global os by default, but if it is a multi os mixed deployment, an exception will occur.
Completing the os type of the host  like full cpu architecture 
Tests 
Release notes:
```release-note
NONE
```
=> cluster:  completing the os type of the host

pkg/cluster/operation/action.go, pkg/cluster/operation/upgrade.go
close #1757 
fix upgrade  not restart exporer
Tests 
Release notes:
```release-note
NONE
```
=> cluster: fix upgrade  not restart exporer

components/playground/grafana.go, embed/templates/config/datasource.yml.tpl, pkg/cluster/manager/builder.go, pkg/cluster/manager/destroy.go, pkg/cluster/manager/scale_in.go
close #1762 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix Grafana error  datasource not found 

CHANGELOG.md, pkg/version/version.go
=> bump version 1.9.1

components/cluster/command/deploy.go, pkg/cluster/api/dmpb/dmmaster.pb.go, pkg/cluster/api/dmpb/dmworker.pb.go, pkg/cluster/manager/deploy.go
fix #1773 
There were two `IgnoreConfigCheck` fields, and the one in `DeployOptions` was never used (it was moved to `operator.Options` about a year ago)
Tests 
Code changes
Release notes:
```release-note
NONE
```
=> fix --ignore-config-check not working for deploy

pkg/cluster/manager/builder.go, pkg/cluster/manager/check.go, pkg/cluster/manager/destroy.go, pkg/cluster/manager/scale_in.go, pkg/cluster/module/systemd.go, pkg/cluster/task/builder.go, pkg/cluster/task/systemd.go
- close #1770
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: check active before reload promtheus when scale-in/scale-out

pkg/cluster/operation/check.go
Add Oracle  Linux 2 as supported OS
Tests 
Release notes:
```release-note
NONE
```
=> fix: Add Oracle  Linux 2 as supported OS

CHANGELOG.md, pkg/version/version.go
=> bump version 1.9.2

CHANGELOG.md
This pull request updates the CHANGELOG for TiUP 1.9.2 
This pull request updates Oracle Linux version, there is no `Oracle Linux 2` because Oracle Linux uses the same version semantics as Red Hat Enterprise Linux.
https://docs.oracle.com/en/operating-systems/oracle-linux/index.html
=> There is no `Oracle Linux 2`

components/cluster/command/audit.go, components/cluster/command/start.go, components/cluster/command/stop.go, components/dm/command/audit.go, components/dm/command/scale_in.go, components/dm/command/start.go, components/dm/command/stop.go, pkg/cluster/audit/audit.go, pkg/cluster/manager/basic.go, pkg/cluster/manager/builder.go, pkg/cluster/manager/cleanup.go, pkg/cluster/manager/destroy.go, pkg/cluster/operation/action.go, pkg/cluster/operation/destroy.go, pkg/cluster/operation/operation.go, pkg/cluster/task/action.go
Close #1781 
- Add a hidden `--evict-leaders` argument to `tiup-cluster stop` command, to evict store leaders from an instance and wait it to complete, ignored for non-store instances. Only use it with `-N` argument to stop specific instance, if there is no place for store leaders to transfer, the operation may fail.
- Add a hidden `--restore-leaders` argument to `tiup-cluster start` command, to delete the store leader evict scheduler of an instance, so that leaders are allowed to transfer back to it. If the instance was stopped with `--evict-leaders` and started without `--restore-leaders`, the instance will be up but no leader could be transferred to it, in that case, run `start` again with `--restore-leaders` or use `pd-ctl` to delete the store leader evict scheduler.
Also comment some …
=> cluster: support evict leaders on stop and restore on start

embed/examples/dm/minimal.yaml, embed/examples/dm/topology.example.yaml
There is no need for repeated  development work, it can be directly embedded grafana in WebUI to view Cluster statistics.
So it's need to make grafana allow anonymous access. 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> add grafana embedding config

pkg/cluster/spec/validate.go, pkg/cluster/spec/validate_test.go
The Flash* ports are not checked for conflicts for tiflash instances.
Tests 
- Unit test
=> cluster: fix port conflict check for tiflash instances

embed/templates/config/prometheus.yml.tpl, pkg/cluster/ansible/inventory.go, pkg/cluster/spec/monitoring.go, pkg/cluster/template/config/prometheus.go
- close #1799 
- fix #1809
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: add ngm metrics to promtheus config

components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, components/playground/instance/tiflash_proxy_config.go, components/playground/playground.go
Fix #1800 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: fix cannot bind 0.0.0.0

index.html
If you precede a command with a space in bash (and other shells?) it won't put it in the history, so it's more difficult to see the work you've done to set up an environment when the tiup install step is not visible!
Leading spaces are removed from `<code>` blocks in index.html.
Tests 
- No code
Release notes:
```release-note
NONE
```
=> remove preceding spaces from commands so they are not omitted from shell history

index.html
If you precede a command with a space in bash (and other shells?) it won't put it in the history, so it's more difficult to see the work you've done to set up an environment when the tiup install step is not visible!
Leading spaces are removed from <code> blocks in index.html.
Tests 
- No code
Release notes:
```release-note
NONE
```
=> removed leading and trailing spaces from code blocks

components/playground/playground.go
tiup playground cannot start due to copying Grafana files failed
Ignore errors and continue! Besides, `-f` will try to resolve read-only files by removing them first.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix playground start error in MacOS
```
=> playground: fix cp error when encountered readonly files

pkg/cluster/manager/check.go, pkg/cluster/operation/check.go
Close #1767 
Support disabling swap (as described in doc) by setting `vm.swappiness = 0` and `swapoff` to ensure all data already in the swap memory are swapped out.
=> cluster: try to disable swap when `check --apply`

pkg/exec/run.go
- fix #1828 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tiup: fix print duplicated component path

pkg/cluster/spec/spec_test.go, pkg/cluster/template/scripts/cdc.go
Fix cdc data-dir is not enable properly  for v6.0.0
Cc https://github.com/pingcap/tiflow/issues/5142
Tests 
- Unit test
Release notes:
```release-note
Fix cdc data-dir is not enable properly for v6.0.0
```
=> cluster: enable data-dir for versions above v5.0.3

cmd/mirror.go, cmd/root.go, components/cluster/command/root.go, components/dm/command/root.go, components/playground/main.go, pkg/environment/env.go, pkg/repository/model/model.go
Add `--key-dir` argument to `mirror rotate` subcommand
Tests 
Code changes
=> mirror: support custom key-dir when rotate root.json

embed/templates/config/prometheus.yml.tpl
close #1852 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix: exporter and grafana are abnormal in prometheus

components/dm/spec/logic.go, pkg/cluster/manager/display.go, pkg/cluster/operation/check.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/spec_manager_test.go
display support concurrent access to node status
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: display support concurrent access to node status

cmd/root.go, components/playground/main.go
- on #1831 , we parser flag of tiup rootCmd manually, if user use `tiup playground --tag xxx`, tiup cannot Identify the flag and generate a random flag and pass it to playground.
- make playground tag has higher priority than tiup
- make tiup scan the whole args insted of args[0]
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: make playground tag has higher priority than tiup

pkg/cluster/api/binlog.go
close #1854
I think that when there are multiple nodes with the same ip:port, an error should be returned and the client should check.
Release notes:
```release-note
NONE
```
=> cluster: return error when found multiple nodes with the same ip:port

index.html
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
The document links on the https://tiup.io/ page are outdated.
Update the document links.
Tests 
- No code
Release notes:
```release-note
NONE
```
=> Update outdated doc links

.github/workflows/integrate-cluster-cmd.yaml, .github/workflows/integrate-cluster-scale.yaml, tests/tiup-cluster/script/detect_error.sh
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> test: detect error log

pkg/cluster/manager/display.go
just add lock （
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix display exception

pkg/cluster/spec/profile.go
TIUP_HOME is not loaded on initializes meta
Release notes:
```release-note
NONE
```
=> fix: TIUP_HOME is not loaded on initializes meta

pkg/cluster/manager/display.go
fix #1897 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix concurrent map writes

pkg/cluster/manager/manager.go
close #1913 
fix fillHostArchOrOS not working when using Identity
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix fillHostArchOrOS not working when using Identity

pkg/cluster/manager/check.go
- fix #1919 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix cannot check time zone

components/playground/instance/pd.go, components/playground/main.go, components/playground/playground.go, go.mod, go.sum
Issue: #1833
Signed-off-by: pingyu <yuping@pingcap.com>
Close: #1833 
Add `pd.port` argument.
Tests 
```
bin/tiup-playground v6.1.0 --db 0 --tiflash 0 --kv 1 --pd 1 --pd.port 32379
Playground Bootstrapping...
Start pd instance:v6.1.0
Start tikv instance:v6.1.0
PD client endpoints: [127.0.0.1:32379]
To view the Prometheus: http://127.0.0.1:35411
To view the Grafana: http://127.0.0.1:33691
```
Code changes
Side effects
Release notes:
```release-note
Add `pd.port` argument to specify PD port of playground.
```
=> playground: add pd.port argument

README.md
=> README: a mis-spelling of `TiUp`

components/playground/playground.go
Closes #1932 
```
> main.(*Playground).terminate() ./components/playground/playground.go:990 (hits goroutine(1):1 total:1) (PC: 0x150724e)
985:	
986:		if p.grafana != nil {
987:			go kill("grafana", p.grafana.cmd.Process.Pid, p.grafana.wait)
988:		}
989:		for _, inst := range p.tiflashs {
=> 990:			fmt.Printf("inst: %-v\n", inst.Pid())
991:			kill(inst.Component(), inst.Pid(), inst.Wait)
992:		}
993:		for _, inst := range p.ticdcs {
994:			kill(inst.Component(), inst.Pid(), inst.Wait)
995:		}
(dlv) p inst
*github.com/pingcap/tiup/components/playground/instance.TiFlashInstance {
instance: github.com/pingcap/tiup/components/playground/instance.instance {
ID: 0,
Dir: "/home/dvaneeden/.tiup/data/T9HJm1o/tiflash-0",
Host: "127.0.0.1",
Port: 8123,
StatusPort: 8234,
ConfigPath: "",
BinPath: …
```
=> playground: don't get Pid() when there is no Process

components/playground/instance/ticdc.go
Issue Number: #1977
Signed-off-by: pingyu <yuping@pingcap.com>
#1977 
Add "--config=" to arguments of TiCDC.
Tests 
1. Prepare `cdc.toml`:
```
log-level = "debug"
```
2. Start playground
```
tiup-playground nightly --db 1 --tiflash 0 --kv 1 --kv.config etc/tikv-v2.toml --pd 1 --pd.config etc/pd.toml --ticdc 1 --ticdc.config etc/cdc.toml
```
3. Check log level of "cdc.log"
```sh
> cat cdc-0/ticdc.log
...
[2022/07/09 17:32:48.124 +08:00] [DEBUG] [etcd_worker.go:178] ["Etcd progress notification"] [revision=1284165]
[2022/07/09 17:32:48.124 +08:00] [DEBUG] [etcd_worker.go:178] ["Etcd progress notification"] [revision=1284165]
[2022/07/09 17:32:48.124 +08:00] [DEBUG] [etcd_worker.go:178] ["Etcd progress notification"] [revision=1284165] …
```
=> playground: fix ineffectiveness of ticdc.config

pkg/cluster/spec/tiflash.go
close #1975 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: unable to configure tiflash LearnerConfig

pkg/cluster/api/cdcapi.go, pkg/cluster/spec/cdc.go
cdc `prerestart` and `postrestart` method, remove status check, since after the instance restart, it would cost a few seconds to be available.
* this prevent false detect that a new start cdc instance is down, since it will be available just a few seconds later, around 3 ~ 5s seconds.
* When all cdc instance is down, for `upgrade` / `scale-in`, this would cost a little longer time to guarantee that the instance is down now, which is acceptable.
* adjust the timout for get capture open api to 10s, this should be long enough.
Tests 
* Deploy 2 cdc capture, restart the first one, the second one should perform the `prerestart` and `postrestart` as expected.
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cdc rolling upgrade remove status check to prevent false detection.

components/playground/main.go, tests/tiup-playground/test_playground.sh
Issue Number: #1997
Signed-off-by: pingyu <yuping@pingcap.com>
Close #1997 .
Use `rootCmd.PersistentFlags()` to add the "--tag" argument, other than `rootCmd.Flags()`, which is invisible to subcommands. Refer to https://github.com/spf13/cobra/blob/main/user_guide.md#persistent-flags.
Tests 
```
bin/tiup-playground display --tag clst21-up
Pid     Role      Uptime
---     ----      ------
743313  pd        125h42m51.503041111s
743345  tikv      125h42m51.372436142s
743346  tikv-cdc  125h42m51.363139055s
```
Code changes
- No.
Side effects
- No.
Release notes:
```release-note
Fix "--tag" argument for playground subcommands.
```
=> playground: Fix "--tag" argument for subcommands.

pkg/cluster/task/update_meta.go
- fix #1989
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix not delete tidb topo from pd when scale-in

server/handler/tarball.go, tools/check/golangci.yaml
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> server: fix not delete tmp file when upload package

pkg/cluster/api/cdcapi.go, pkg/cluster/spec/cdc.go
retry on owner resign, to make it more robust.
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cdc: retry on resign the owner, if old owner in power again.

.github/workflows/integrate-cluster-cmd.yaml, docker/up.sh, embed/examples/cluster/topology.example.yaml, embed/templates/config/prometheus.yml.tpl, embed/templates/scripts/run_tikv-cdc.sh.tpl, pkg/cluster/ansible/import_test.go, pkg/cluster/ansible/test-data/meta.yaml, pkg/cluster/api/tikv_cdc.go, pkg/cluster/spec/bindversion.go, pkg/cluster/spec/instance.go, pkg/cluster/spec/monitoring.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/spec_test.go, pkg/cluster/spec/tikv_cdc.go, pkg/cluster/task/update_meta.go, pkg/cluster/template/config/prometheus.go, pkg/cluster/template/scripts/tikv_cdc.go, pkg/tidbver/tidbver.go, tests/tiup-cluster/run.sh, tests/tiup-cluster/script/cmd_subtest.sh, tests/tiup-cluster/script/scale_core.sh, tests/tiup-cluster/script/tikv_cdc.sh, tests/tiup-cluster/test_cmd.sh, tests/tiup-cluster/test_cmd_tls_native_ssh.sh, tests/tiup-cluster/test_scale_core.sh, tests/tiup-cluster/test_tikv_cdc.sh, tests/tiup-cluster/topo/full.yaml, tests/tiup-cluster/topo/tikv_cdc.yaml, tests/tiup-cluster/topo/tikv_cdc_scale_in.yaml
Issue Number: #1999
Signed-off-by: pingyu <yuping@pingcap.com>
#1999 
TiUP cluster supports the [TiKV-CDC](https://github.com/tikv/migration/tree/main/cdc) component.
Tests 
- Unit test
```sh
➜  tiup-cluster deploy up v6.2.0 up.yaml
...
...
Cluster `up` deployed successfully, you can start it with command: `tiup-cluster start up --init`
➜  tiup-cluster start up -y
Starting cluster up...
...
...
Started cluster `up` successfully
➜  tiup-cluster display up
Cluster type:       tidb
Cluster name:       up
Cluster version:    v6.2.0
Deploy user:        root
SSH type:           builtin
...
...
Total nodes: 14
➜ tikv-cdc cli --pd 10.2.x.x:2379 capture list
[
{
"id": "3e2ede2a-13ad-4ded-8ac6-1c5f315dfd5e",
"is-owner": false, …
```
=> cluster: Support TiKV-CDC component

go.mod, go.sum, pkg/cluster/api/types.go, pkg/cluster/api/typeutil/size.go, pkg/cluster/api/typeutil/size_test.go, pkg/cluster/manager/display.go
Sync latest version of PD types and `typeutil` from `tikv/pd`.
The code we use in `pkg/cluster/api` is ported from PD (to avoid direct dependency) and is a little bit outdated. 
I've kept the upstream-removed `ApplyingSnapCount` field in our port and added an `omitempty` to the newly added field `SlowScore` in `StoreStatus` so there should be no compatibility issue with legacy PD releases.
This change should have no effect to end user.
Tests 
- Unit test
Release notes:
```release-note
NONE
```
=> cluster/api: sync pdapi & typeutil with pd 6.3.0

pkg/cluster/api/cdcapi.go, pkg/cluster/spec/cdc.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cdc: before drain the capture, check the capture can be found

embed/examples/cluster/topology.example.yaml, embed/templates/config/prometheus.yml.tpl, pkg/cluster/spec/monitoring.go, pkg/cluster/template/config/prometheus.go
- close #2049
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> support config scrape_interval and scrape_timeout for prometheus

pkg/cluster/operation/check.go
- close #2078
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: mark kylin v10 as supported OS

components/ctl/main.go
Ensure `tiup ctl etcd` works with TiDB by default.
Closes #2080
Tests 
Release notes:
```release-note
NONE
```
=> ctl: Set ETCDCTL_API=v3 to get the v3 API

pkg/cluster/spec/grafana.go
- close #2072 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: avoid redirect when grafana set root_url

components/playground/instance/tidb.go, components/playground/playground.go
TiDB Playground doesn't enable TLS by default. While TLS isn't needed in most cases to make the playground secure, it can help to detect issues with client code early on that could cause problems later when deployed on TiDB Cloud Serverless (which requires TLS).
if there is no config specified, create a temporary config that enables
AutoTLS.
https://docs.pingcap.com/tidb/stable/tidb-configuration-file#auto-tls
Tests 
Code changes
Side effects
Release notes:
```release-note
TiUP Playground enables AutoTLS by default
```
=> playground: Enable AutoTLS by default

components/playground/command.go, components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, pkg/cluster/template/scripts/pd.go
Signed-off-by: iosmanthus <myosmanthustree@gmail.com>
This pull request merges the default TiFlash config with the specified TiFlash config to reduce the handwrite config, which might be annoying while dealing with a few heterogeneous tiflash instances. You guy might ask why not use `tiup cluster` instead. The `tiup cluster` run pretty slow than the playground and makes users frustrated while debugging codes.
All generated config will write to the instance directory of the TiFlash instance, and if the config path is set, the config of it will be patched to the default config generated by `tiup playground`.
Tests 
- Unit test
- No code
Code changes
- Has exported variable/fields …
=> merge tiflash config in tiup playground to reduce handwrite config

pkg/base52/base52.go, pkg/base52/base52_test.go
The `Decode()` in `base52` does not check for input value for invalid characters, thus may have security risks.
Check for invalid characters and return an error.
Tests 
- Unit test
Code changes
=> base52: check for invalid chars in Decode()

cmd/clean.go
If the `tiup_process_meta` file is missing in a datadir of a tiup playground then `tiup clean` will silently skipp it.
This changes this to show a message in case this happens.
```
$ tiup clean TS9acXe
Can't clean directory due to missing meta file: /home/dvaneeden/.tiup/data/TS9acXe
$ tiup clean --all
Can't clean directory due to missing meta file: /home/dvaneeden/.tiup/data/TS9acXe
Clean instance of `playground`, directory: /home/dvaneeden/.tiup/data/foo
```
Tests 
Release notes:
```release-note
The `tiup clean` command now shows a message if it can't cleanup a directory due to a missing `tiup_process_meta` file.
```
=> clean: Warn for cleanup failures due to missing datadir

pkg/telemetry/meta.go, pkg/telemetry/meta_test.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> disable telemetry by default

components/playground/instance/ticdc.go, components/playground/main.go, components/playground/playground.go
Allow setting the TCP port for TiCDC
Example:
```
tiup playground --tiflash 0 --without-monitor --ticdc 1 --ticdc.port 8333 v6.6.0
```
Tests 
Code changes
Release notes:
```release-note
Add an option to set a custom TCP port for TiCDC to listen on.
```
=> playground: Allow setting the TiCDC port

pkg/cluster/manager/display.go, pkg/cluster/spec/instance.go, pkg/cluster/spec/tiflash.go
https://github.com/pingcap/tiup/issues/2135
When the label of TiFlash contains engine-role:write, it means that This TiFlash is a tiflash_write node. So tiflash_write should be displayed in tiup cluster display. But we don't support -R `tiflash_write` or `tiflash_compute` now, so just display `tiflash (write)` or `tiflash (compute)`.
Tests 
- Unit test
- No code
Code changes
Side effects
Release …
=> display disaggregated mode

cmd/clean.go
The pid that is read from `tiup_process_meta` can be old and might be recycled due to pid wrap around or after restarts.
This PR checks if the `p.Name()` is `tiup-playground` before killing it.
```
Kill instance of `playground`, pid: 2804212
Clean instance of `playground`, directory: /home/dvaneeden/.tiup/data/crp
Process name mismatch (`/usr/bin/gjs` != `tiup-playground`, not killing it.
Clean instance of `playground`, directory: /home/dvaneeden/.tiup/data/crp
```
For a actual playground the data looks like this:
```
PROC cmdline: /home/dvaneeden/.tiup/components/playground/v1.11.3/tiup-playground -T crp --tiflash 0 --without-monitor v6.6.0
PROC cwd: /home/dvaneeden
PROC exe: /home/dvaneeden/.tiup/components/playground/v1.11.3/tiup-playground
PROC name: tiup-playground
```
For a …
=> clean: check process name before killing it

pkg/cluster/operation/destroy.go, pkg/cluster/spec/tiflash.go
After https://github.com/pingcap/tiflash/pull/6967, TiFlash has added  `storage.remote.cache.dir` config, so tiup cluster prune need to delete storage.remote.cache.dir of TiFlash.
tiup cluster prune support to delete storage.remote.cache.dir of TiFlash.
Tests 
- Unit test
`./tiup-cluster prune ctl-test-2`
Check if the `storage.remote.cache.dir` has been deleted.
- No code
Code changes
Side effects …
=> tiup cluster prune need to delete storage.remote.cache.dir

components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, components/playground/instance/tiflash_proxy_config.go, components/playground/instance/tikv.go, pkg/tidbver/tidbver.go
Currently in playground we run TiFlash via a specified config file, and we put runtime config (like port, data directory) in the config file.
It is hard for us to specify a custom config file, because we must fill these runtime config in the custom config file as well.
Move TiFlash runtime config to args, thanks to https://github.com/pingcap/tiflash/pull/7251.
Tests 
Start one:
```shell
bin/tiup-playground nightly --tiflash.binpath ~/Work/tiflash-workspace2/cmake-build-Debug/dbms/src/Server/tiflash
Using the version nightly for version constraint "nightly".
If you'd like to use a TiDB version other than nightly, cancel and retry with the following arguments:
Specify version manually:   tiup playground <version>
Specify version range: …
```
=> playground: Run TiFlash via args

pkg/cluster/spec/parse_topology_test.go, pkg/cluster/spec/tiflash.go
TiUP Cluster will reject the deployment for the following TiFlash config:
```yaml
config:
storage.remote.dir: /tmp/tiflash/remote
```
Actually this is fine: TiFlash does not require `storage.main` defined in this case.
Only check `storage.main` exists when `storage.latest` or `storage.raft` is defined.
Tests 
- Unit test
Release notes:
```release-note
Allows setting other storage config for TiFlash when `storage.main` is not defined
```
=> cluster: Allows setting other storage config for TiFlash when `storage.main` is not defined

components/playground/main.go, components/playground/playground.go
There are many duplicate codes when introducing new args in TiUP Playground.
Keep code dry.
This PR is more like a re-implementation of https://github.com/pingcap/tiup/pull/1365 in another way.
Tests 
- Unit test
A simple test about how `options` looks like now after `populateDefaultOpt`:
```
❯ bin/tiup-playground nightly --mode tikv-slim
{"Mode":"tikv-slim","Version":"nightly","PD":{"Num":1},"TiDB":{"UpTimeout":60},"TiKV":{"Num":1},"TiFlash":{"UpTimeout":120},"TiCDC":{},"TiKVCDC":{},"Pump":{},"Drainer":{},"Host":"127.0.0.1","Monitor":true}
❯ bin/tiup-playground nightly --mode tidb
{"Mode":"tidb","Version":"nightly","PD":{"Num":1},"TiDB":{"Num":1,"UpTimeout":60},"TiKV":{"Num":1},"TiFlash":{"Num":1,"UpTimeout":120},"TiCD …
```
=> playground: Code refine for args

components/playground/instance/tiflash.go, components/playground/instance/tiflash_pre7.go, components/playground/instance/tiflash_pre7_config.go, components/playground/instance/tiflash_pre7_proxy_config.go, pkg/tidbver/tidbver.go
Group and move all legacy TiFlash config and start stuff into `tiflash_pre7_xxx` and name them as `xxx_old`, so that we don't need to care about them any more: we will not introduce any new features to these legacies.
The new start logic of TiFlash is very simple and it takes the place of the default start implementation.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes: …
=> playground: Code refine for TiFlash

pkg/cluster/api/pdapi.go, pkg/cluster/operation/destroy.go, pkg/cluster/operation/scale_in.go, pkg/cluster/operation/upgrade.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/pump.go, pkg/cluster/spec/validate.go, pkg/utils/utils.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix cannot prune/scale-in tikv when use ipv6

components/playground/playground.go
close #2186
It just adds `--comments` to the output to be used for running the mysql command line tool.
Tests 
`./bin/tidb-playground` and verify output when cluster is ready.
Code changes
- output text change only
Side effects
- none
- none
Release notes:
```release-note
NONE
```
=> playground: include '--comments' in mysql command line arguments

components/playground/instance/tiflash_pre7_config.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: fix port conflict when cluster version >= 5.4 and < 7.1

components/playground/main.go
Currently `--tiflash 0` is not working because we treat 0 as default value and 0 is discarded.
We use `.Changed` to check whether an option is set.
(Or may be some better way is to use `*int` instead? I'm not sure).
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: Fix --tiflash 0 not working

components/playground/instance/tikv.go, components/playground/main.go, components/playground/playground.go
Add:
```
--kv.host host             Playground TiKV host. If not provided, TiKV will still use host flag as its host
--kv.port int              Playground TiKV port. If not provided, TiKV will use 20160 as its port
```
Tests 
Code changes
- Has exported function/method change (`NewTiKVInstance`)
Side effects
Release notes:
```release-note
Add `--kv.port` option to TiUP Playground to set the TiKV port.
```
=> Playground: Option to specify TiKV port

components/dm/command/scale_in.go, components/playground/playground.go, go.mod, pkg/cluster/manager/display.go, pkg/cluster/operation/scale_in.go, pkg/cluster/operation/upgrade.go, pkg/cluster/spec/cdc.go, pkg/cluster/spec/pd.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/tikv_cdc.go
- close #2205
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix not use manage_host when connect to pd/cdc

components/dm/command/prune.go, components/dm/spec/topology_dm.go, pkg/cluster/manager/check.go, pkg/cluster/manager/display.go, pkg/cluster/operation/destroy.go, pkg/cluster/operation/upgrade.go, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/cdc.go, pkg/cluster/spec/dashboard.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/monitoring.go, pkg/cluster/spec/pd.go, pkg/cluster/spec/pump.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tidb.go, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/tikv.go, pkg/cluster/spec/tikv_cdc.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix not use manage_host when connect to components again

pkg/tui/progress/display_props.go, pkg/tui/progress/example_single_bar_test.go, pkg/tui/progress/single_bar.go
```
$ go test -v
=== RUN   TestExampleOutput
Prefix ... Done
Prefix ... Error: expected failure
--- PASS: TestExampleOutput (8.00s)
PASS
ok  	github.com/pingcap/tiup/pkg/tui/progress	8.004s
```
This could be helpful to add more detail to Clinic:
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> progress: Add option to add error detail

components/playground/instance/tiflash.go, components/playground/instance/tiflash_pre7.go, components/playground/instance/tiflash_pre7_config.go, embed/examples/cluster/minimal.yaml, embed/examples/cluster/multi-dc.yaml, embed/examples/cluster/topology.example.yaml, pkg/cluster/ansible/inventory.go, pkg/cluster/ansible/service_test.go, pkg/cluster/ansible/test-data/meta.yaml, pkg/cluster/spec/testdata/topology_err.yaml, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/validate.go, pkg/telemetry/testdata/single/nilvalue.yaml
This reverts commit a236734c7cd91fff4912e6d1d064a19c7ac27432.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Revert "*: remove tcp_port for tiflash (#2218)"

components/playground/instance/tiflash.go, components/playground/instance/tiflash_pre7.go, components/playground/instance/tiflash_pre7_config.go, embed/examples/cluster/minimal.yaml, embed/examples/cluster/multi-dc.yaml, embed/examples/cluster/topology.example.yaml, pkg/cluster/ansible/service_test.go, pkg/cluster/spec/tiflash.go, pkg/tidbver/tidbver.go
Remove tiflash tcp_port config for tiflash >= 7.1.0.
1. For playground, remove tcp_port for tiflash < 7.1.0, as there are no compatibility and instance identity issues.
2. For ansibile and cluster, not render tcp_port config in tiflash config file for tiflash >= 7.1.0.
Tests 
- No code
Code changes
Side effects
- None
- None
Release notes:
```release-note
NONE
```
=> *: remove tcp_port for tiflash >= 7.1.0

pkg/cluster/manager/display.go, pkg/cluster/operation/check.go, pkg/cluster/operation/systemd.go
- fix #2224
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix tiflash uptime

components/playground/command.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/main.go, components/playground/playground.go, pkg/tidbver/tidbver.go
Introduce the pd-ms mode for better testing of the PD microservices mode.
Usage:
```
tiup-playground nightly --pd.mode ms
```
It will start 1 API, 1 TSO, 1 resource manager server by default. If we want to start more, just use the following cmd like other mode:
```
tiup-playground nightly --pd.mode ms --pd.api 3 --pd.tso 2 --pd.rm 1
```
Output:
```
🎉 TiDB Playground Cluster is started, enjoy!
Connect TiDB:   mysql --comments --host 127.0.0.1 --port 4000 -u root
TiDB Dashboard: http://127.0.0.1:2379/dashboard
Grafana:        http://127.0.0.1:3000
```
For `tikv-slim`:
```
tiup-playground nightly --mode tikv-slim --pd.mode ms --pd.api 3 --pd.tso 2 --pd.rm 1
```
Output:
```
PD TSO Endpoints:   127.0.0.1:2386,127.0.0.1:2388
PD API Endpoints:   127.0.0.1:2379,127.0.0.1:2382,127.0.0.1:2384
PD …
```
=> playground: support microservices mode

pkg/cluster/spec/tiflash.go, pkg/tidbver/tidbver.go
Close https://github.com/pingcap/tiup/issues/2229
1. Include "nightly" in version check for tiflash that doesn't require tcp port.
2. Change ready detection to use service port rather than tcp port.
Tests 
Deploy v7.1.0/v7.2.0/nightly cluster. Before this patch, starting cluster failed at tiflash component. After this patch, starting cluster succeeded.
Code changes
- None
Side effects
- None
Release notes:
```release-note
Fix the issue that cluster start failure caused by tiflash checking for tcp port ready.
```
=> cluster: fix cannot start tiflash above 7.1.0

pkg/cluster/manager/exec.go
- fix #2247 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix node filter on exec

pkg/cluster/manager/patch.go, pkg/utils/ioutil.go
Close #2241
* Use the relative path to create a symbolic link when executing `tiup cluster patch --overwrte`.
* Support packaging symbolic links when executing `tiup cluster meta backup`.
Tests 
* Patch the pd and check the symbolic link is a relative path.
```
$ ./tiup-cluster patch my-cluster pd-v5.1.0-linux-amd64.tar.gz --overwrite -R pd
...
$ ll /root/.tiup/storage/cluster/clusters/my-cluster/patch/
total 40M
-rw-r--r-- 1 root root 40M Aug 18 06:58 pd-b64365c.tar.gz
lrwxrwxrwx 1 root root  17 Aug 18 06:58 pd.tar.gz -> pd-b64365c.tar.gz
```
* Backup cluster meta.
```
$ /tiup-cluster meta backup my-cluster
successfully backup meta of cluster my-cluster on tiup-cluster_my-cluster_metabackup_2023-08-18T07-00-21Z.tar.gz
```
* Restore to a new cluster and check the symbolic link.
```
$ …
```
=> Fix the issue meta backup is failed when symbolic links exist in meta dir.

components/dm/spec/logic.go, pkg/cluster/manager/check.go, pkg/cluster/manager/upgrade.go, pkg/cluster/operation/upgrade.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/spec_manager_test.go, pkg/tidbver/tidbver.go
Close #2166
Upgrade TiCDC before TiKV and PD when cluster is equal or greater than v5.1.0
Tests 
1. Upgrade cluster from v5.0.0 to v.5.2.0
```
$ ./tiup-cluster upgrade my-cluster v5.2.0
This operation will upgrade tidb v5.0.0 cluster my-cluster to v5.2.0.
...
Upgrading component pd
Restarting instance 127.0.0.1:2379
Restart instance 127.0.0.1:2379 success
Upgrading component tikv
Restarting instance 127.0.0.1:20160
Restart instance 127.0.0.1:20160 success
Upgrading component tidb
Restarting instance 127.0.0.1:4000
Restart instance 127.0.0.1:4000 success
Upgrading component cdc
Restarting instance 127.0.0.1:8300
Restart instance 127.0.0.1:8300 success
...
```
2. Upgrade cluster from v5.1.0 to v5.2.0
```
$ ./tiup-cluster upgrade my-cluster …
```
=> Upgrade TiCDC before TiKV and PD when cluster is equal or greater than v5.1.0

components/playground/main.go, components/playground/playground.go
https://github.com/pingcap/tiup/pull/2202#issuecomment-1689386442
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: refine ready message

cmd/link.go, cmd/root.go, cmd/unlink.go, pkg/environment/env.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tiup: support run components without tiup

components/playground/playground.go
close #2270 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> fix pd microservice component id

pkg/cluster/spec/grafana.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> grafana for Multiple instances of the same host

pkg/repository/mirror.go
- fix #2283
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> add cdn workaround

components/cluster/command/upgrade.go, components/dm/command/upgrade.go, pkg/cluster/manager/upgrade.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster/dm: support ignore version check when upgrade

pkg/cluster/api/tidbapi.go, pkg/cluster/manager/patch.go, pkg/cluster/manager/reload.go, pkg/cluster/manager/upgrade.go, pkg/cluster/operation/upgrade.go, pkg/tidbver/tidbver.go
- close #2248
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Support tidb upgrade api

pkg/utils/retry.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> show more retry error message

embed/templates/config/prometheus.yml.tpl, embed/templates/scripts/run_tiproxy.sh.tpl, pkg/cluster/ansible/import_test.go, pkg/cluster/ansible/test-data/meta.yaml, pkg/cluster/spec/bindversion.go, pkg/cluster/spec/monitoring.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tiproxy.go, pkg/cluster/task/update_meta.go, pkg/cluster/template/config/prometheus.go, pkg/cluster/template/scripts/tiproxy.go
As title. Also fixed meta update for `dashboard servers`.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Suppor tiproxy for tiup cluster
```
=> cluster: support tiproxy

components/cluster/command/display.go, pkg/cluster/manager/display.go, pkg/cluster/spec/alertmanager.go, pkg/cluster/spec/cdc.go, pkg/cluster/spec/dashboard.go, pkg/cluster/spec/drainer.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/instance.go, pkg/cluster/spec/monitoring.go, pkg/cluster/spec/pd.go, pkg/cluster/spec/pump.go, pkg/cluster/spec/tidb.go, pkg/cluster/spec/tiflash.go, pkg/cluster/spec/tikv.go, pkg/cluster/spec/tikv_cdc.go, pkg/cluster/spec/tiproxy.go, pkg/cluster/spec/tispark.go
Close #2294
add a new flag '--numa' to show numa in display command.
Tests 
- Unit test
1. Deploy a new cluster.
2. Display with '--numa' flag.
- No code
Code changes
Side effects
Release notes:
```release-note
add a new flag '--numa' to show numa in display command
```
=> add a new flag '--numa' to show numa in display command

components/playground/main.go
Close #2221
Use port not root user to probe db in playground.
Tests 
- Unit test
1. Create a tidb configuration that contains init SQL to init root password.
```
ALTER USER 'root'@'%' IDENTIFIED BY '123';
```
```toml
initialize-sql-file = "/root/shiori/pingcap/tiup/bin/init.sql"
```
2. Execute `tiup playground --db.config tidb.toml`.
3. Connect db with password successfully.
- No code
Code changes
Side effects
- Need to update the …
=> use port to probe db in playground

components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/main.go, components/playground/playground.go
Support scheduling service for tiup playground
Tests 
- Manual test
Release notes:
```release-note
NONE
```
=> Support scheduling service

pkg/cluster/api/tidbapi.go, pkg/cluster/executor/executor.go, pkg/cluster/module/wait_for.go
Close #2267
Add a function `UnwarpCheckPointExecutor` to get a real executor without checkpoints.
Use `UnwarpCheckPointExecutor` to executor `ss -tln` when checking wether components are started/stopped.
Tests 
- Unit test
1. Deploy a new cluster and check audit logs.
The `ss -tln` command isn't cached when starting components.
```
// ...
2023-11-01T02:34:40.179Z        INFO    Starting component blackbox_exporter
2023-11-01T02:34:40.179Z        INFO            Starting instance 127.0.0.1
2023-11-01T02:34:41.152Z        INFO    LocalCommand    {"cmd": "export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /usr/bin/sudo -H -u root bash -c \"cd; systemctl daemon-reload && systemctl start …
```
=> not cache the output of  `ss -tln` command when checking wether components are started/stopped

components/playground/instance/instance.go, components/playground/instance/tiproxy.go, components/playground/monitor.go, components/playground/playground.go
Playground promtheus pulls wrong metric addresses for tiproxy.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix tiproxy metrics on playground
```
=> playground: fix tiproxy metrics addr

.github/workflows/release-tiup.yaml, install.sh
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> improve install.sh and release ci

embed/templates/scripts/run_tidb-dashboard.sh.tpl, pkg/cluster/spec/dashboard.go, pkg/cluster/template/scripts/dashboard.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix tidb-dashboard listen_host

components/playground/main.go, components/playground/playground.go, pkg/cluster/spec/tiproxy.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tiproxy not use nightly by default

pkg/cluster/spec/spec.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> allow to set component version when scale-out

cmd/mirror.go, pkg/cluster/spec/bindversion.go, pkg/repository/clone_mirror.go
- close #2254 #2259
coreSuit: "tidb", "tikv", "pd", "tiflash", "prometheus", "grafana", "ctl", "cdc"
- before: clone gloabl version and component version,for components not in coreSuit, add latest is version not exist
- after: only clone component version if exist. only clone global version (may add latest) if component version not exist. 
Tests 
- Unit test
- No code
Code changes
Side effects …
=> Mirror clone err

components/playground/instance/pd.go, components/playground/playground.go
change log name for pd mcs
run `./tiup-playground nightly --pd.mode ms --pd.api 3 --pd.tso 2 --pd.rm 1`
before
after
Tests 
Release notes:
```release-note
NONE
```
=> playground/log: add mcs name for pd log

pkg/repository/clone_mirror.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> mirror: return err if specified latest not found when clone mirror

components/playground/playground.go
`tiup playground --tiproxy 1 v7.1.2`:
Without this PR:
```
Connect TiDB:    mysql --comments --host 127.0.0.1 --port 4000 -u root
Connect TiProxy: mysql --comments --host 127.0.0.1 --port 6000 -u root
TiDB Dashboard:  http://127.0.0.1:2379/dashboard
Grafana:        http://127.0.0.1:3000
```
With this PR:
```
Connect TiDB:    mysql --comments --host 127.0.0.1 --port 4000 -u root
Connect TiProxy: mysql --comments --host 127.0.0.1 --port 36243 -u root
TiDB Dashboard:  http://127.0.0.1:2379/dashboard
Grafana:         http://127.0.0.1:3000
```
The line with `Grafana:` isn't aligned correctly
Tests 
Release notes:
```release-note
NONE
```
=> playground: Fix alignment of output

components/playground/playground.go
Closes #2317 
Tests 
Release notes:
```release-note
TiUP Playground was updated to signal TiProxy to stop gracefully when stopping the playground.
```
=> playground: make sure to signal tiproxy to stop

.github/workflows/lint.yaml, components/dm/ansible/import.go, pkg/cluster/ansible/inventory.go, pkg/cluster/ansible/service.go, pkg/cluster/operation/scale_in.go, tools/check/revive.toml
The revive check for cognitive complexity was emitting warnings:
```
$ make lint 
linting
⚠  https://revive.run/r#cognitive-complexity  function (*Manager).Deploy has cognitive complexity 66 (> max enabled 48)  
./pkg/cluster/manager/deploy.go:57:1
⚠  https://revive.run/r#cognitive-complexity  function (*Specification).CountDir has cognitive complexity 51 (> max enabled 48)  
./pkg/cluster/spec/validate.go:812:1
⚠  https://revive.run/r#cognitive-complexity  function newImportCmd has cognitive complexity 51 (> max enabled 48)  
./components/cluster/command/import.go:31:1
⚠  https://revive.run/r#cognitive-complexity  function (*cleanupFiles).instanceCleanupFiles has cognitive complexity 54 (> max enabled 48)  
./pkg/cluster/manager/cleanup.go:186:1
⚠ …
```
=> Change revive cognitive-complexity settings

CHANGELOG.md, pkg/version/version.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> bump version to v1.14.0

components/playground/main.go, go.mod, go.sum, pkg/exec/run.go, pkg/tui/colorstr/builtin_tokens.go, pkg/tui/colorstr/color.go, pkg/tui/colorstr/color_test.go, pkg/tui/colorstr/test_util.go, pkg/tui/colorstr/test_util_test.go
Make output more cleaner for tiup and playground.
Before:
After:
Also introduced a new utility `colorstr`, which can be used to print colors easier.
Tests 
Release notes:
```release-note
NONE
```
=> tiup & playground: Tidy output

pkg/cluster/api/pdapi.go
Correct typo in pdapi messages.
Change the string from 'waitting' to 'waiting'. There are 6 'waiiting' typos in pdapi.go:
```
pkg/cluster/api/pdapi.go:288:           pc.l().Debugf("Still waitting for the PD leader to be elected")
pkg/cluster/api/pdapi.go:289:           return perrs.New("still waitting for the PD leader to be elected")
pkg/cluster/api/pdapi.go:447:           pc.l().Debugf("Still waitting for the PD leader to transfer")
pkg/cluster/api/pdapi.go:448:           return perrs.New("still waitting for the PD leader to transfer")
pkg/cluster/api/pdapi.go:527:                   "\t  Still waitting for %d store leaders to transfer...",
pkg/cluster/api/pdapi.go:735:                           return perrs.New("still waitting for the PD node to be deleted")
```
=> Change typo 'waitting' to 'waiting' in output messages within pdapi.go.

embed/templates/scripts/run_alertmanager.sh.tpl
Close #2329
Tests 
- Unit test
Deploy a cluster with a alertmanager.
```yaml
alertmanager_servers:
- host: 127.0.0.1
numa_node: "0"
```
Check the start script of this alertmanager.
```bash
#!/bin/bash
set -e
DEPLOY_DIR=/tidb-deploy/alertmanager-9093
cd "${DEPLOY_DIR}" || exit 1
exec > >(tee -i -a "/tidb-deploy/alertmanager-9093/log/alertmanager.log")
exec 2>&1
exec numactl --cpunodebind=0 --membind=0 bin/alertmanager/alertmanager \
--config.file="conf/alertmanager.yml" \
--storage.path="/tidb-data/alertmanager-9093" \
--data.retention=120h \
--log.level="info" \
--web.listen-address="0.0.0.0:9093" \
--web.external-url="http://127.0.0.1:9093" \
--cluster.peer="127.0.0.1:9094" \
--cluster.listen-address="127.0.0.1:9094" …
```
=> fix the start script for alertmanager when enabling numa

embed/templates/scripts/run_prometheus.sh.tpl, pkg/cluster/spec/instance.go, pkg/cluster/spec/monitoring.go, pkg/cluster/template/scripts/monitoring.go
Some users want to turn on Prometheus's hot load feature. Or add some Prometheus commands manually
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster/dm: support deploying Prometheus witch custom command parameters

components/playground/playground.go
Close #2343 . Fallback to default version when componen specific version is empty
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: fallback to default version when componen specific version is empty

components/playground/instance/tiproxy.go, go.mod, go.sum
Close #2339 
previously, it doesnt override user config correctly leading to port conflicts when using custom configs for multiple tiproxy instances. TiDB pass ports by cli flags so then are fine.
Also, log-file is not passed
1. use different logic than TiDB to generate configs.
2. pass log-file
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: tiproxy needs to override usercfg

pkg/cluster/spec/tiflash.go, pkg/tidbver/tidbver.go
delete logger.level and profiles.default.max_memory_usage in tiflash default configs since there is no need to set them explicitly in the config file.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> delete `logger.level` and `profiles.default.max_memory_usage` in tiflash default configs

components/playground/instance/pd.go, components/playground/instance/pd_config.go
close https://github.com/tikv/pd/issues/7507
Tests 
- Unit test
config:
```
➜  pd-0 cat pd.toml
[schedule]
patrol-region-interval = "100ms"
```
Release notes:
```release-note
NONE
```
=> playground: init some pd configuration

pkg/cluster/spec/tiproxy.go, pkg/cluster/spec/validate.go
1, `require-backend-tls` is useless
2. now we use `nightly` version by default
3. fix a bug where configs are lost
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix tiproxy config and version

pkg/cluster/spec/tiproxy.go
1. `server-tls` of tidb is manually specified, so does tiproxy's `server-tls`. Instead, for newer tiproxy, `server-http-tls` should be specified.
2. `topo.GlobalOptions.TLSEnabled` is not passed to `setTLSConfig`.
3. remove `schema://` and be consistent with tidb
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix TLS configs for tiproxy

pkg/cluster/manager/upgrade.go
Restart tiproxy iff version becomes different after `--tiproxyversion` or new cluster version(only `nightly` is possible though).
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix tiproxy will restart even if version is the same

CHANGELOG.md
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> bump to 1.14.1

tests/tiup-cluster/script/scale_core.sh, tests/tiup-cluster/script/scale_tools.sh, tests/tiup-cluster/topo/full.yaml, tests/tiup-cluster/topo/full_scale_in_tiproxy.yaml, tests/tiup-cluster/topo/full_tls.yaml, tests/tiup-cluster/topo/full_without_tiflash.yaml
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: add integration tests for tiproxy

embed/templates/systemd/system.service.tpl, pkg/cluster/manager/builder.go, pkg/cluster/manager/deploy.go, pkg/cluster/operation/destroy.go, pkg/cluster/spec/instance.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> create systemd dir when use systemd user mode

components/playground/playground.go
`tiup playground v7.5.0 --tiproxy 1` will fail since `bindVersion = "v7.5.0"`. We should only pull `nightly` instead.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: only pull nightly from cluster version

components/playground/playground.go, tests/tiup-playground/test_playground.sh
missing `sanitizeComponentConfig`.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix tiproxy playground scale out
```
=> playground: fix tiproxy scale

pkg/exec/run.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Fix timeout when checking component upgrade

pkg/cluster/manager/upgrade.go
Some components has different `Role()` and `Name()`. `FilterComponent` is a mixed of filtering by `Name()` and `Role()`, thus we need to add both into the filter set.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: skip tiproxy download & copy

pkg/cluster/manager/builder.go, pkg/cluster/spec/tidb.go, pkg/tidbver/tidbver.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: auto session certs

components/playground/instance/tidb.go, components/playground/instance/tidb_config.go, components/playground/instance/tiproxy.go, components/playground/playground.go
User needs to manually set `session-xxxxx` for tidb, to make tiproxy migration works. However, we could just generate a self-signed cert automatically. There is no security implication: the only requirement for this cert, is that, it should be same on all tidb instances.
Tests 
- Unit test
```
[2024/01/29 15:59:00.527 +08:00] [INFO] [session_token.go:198] ["signing cert is loaded successfully"] ["cert path"=/Users/xhe/.tiup/data/U2jjZcE/tiproxy.crt] ["key path"=/Users/xhe/.tiup/data/U2jjZcE/tiproxy.key]
```
- No code
Code changes
Side effects …
=> playground: auto tiproxy sign certs

components/playground/instance/tiflash.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Remove uselesss println

components/playground/playground.go
Tests 
before
after
Release notes:
```release-note
NONE
```
=> pdms: fix pdms grafana display

components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/main.go, components/playground/playground.go, pkg/cluster/executor/ssh.go
Resource manager microservice is never fully tested. So I'm going to remove it to avoid misleading the users.
Tests 
```
$ bin/tiup-playground nightly --pd.mode ms --pd 3 --scheduling 2 --tso 2 --kv 6 --tiflash 0 --host 10.2.8.101
Start pd instance:v8.0.0-alpha-nightly
Start pd instance:v8.0.0-alpha-nightly
Start pd instance:v8.0.0-alpha-nightly
Start tso instance:v8.0.0-alpha-nightly
Start tso instance:v8.0.0-alpha-nightly
Start scheduling instance:v8.0.0-alpha-nightly
Start scheduling instance:v8.0.0-alpha-nightly
Start tikv instance:v8.0.0-alpha-nightly
Start tikv instance:v8.0.0-alpha-nightly
Start tikv instance:v8.0.0-alpha-nightly
Start tikv instance:v8.0.0-alpha-nightly
Start tikv instance:v8.0.0-alpha-nightly
Start tikv …
```
=> playground: remove resource manager

components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/pd_config.go, components/playground/instance/tidb.go, components/playground/instance/tidb_config.go, components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, components/playground/instance/tikv.go, components/playground/instance/tikv_config.go, components/playground/main.go, components/playground/playground.go, pkg/tidbver/tidbver.go
Remove tidb-disagg, and add tidb-cse.
tidb-cse mode is used to start a TiDB CSE cluster, it contains disaggregated TiFlash and TiKV in CSE mode.
Tests 
- Manual test
Release notes:
```release-note
playground: Support --mode=tidb-cse
```
=> playground: Add tidb-cse mode

components/playground/instance/tiproxy.go, pkg/cluster/spec/tiproxy.go
#2391 
TiProxy reports its IP, instead of its DNS to ETCD.
Add config `advertise-addr` to tiproxy spec.
Note that it's compatible with old TiProxy versions because TiProxy won't report errors if there's an unknown config.
Tests 
With Playground:
```
MySQL [information_schema]> select * from cluster_config where key like '%advertise%';
+---------+---------------------+------------------------------+---------------------------+
| TYPE    | INSTANCE            | KEY                          | VALUE                     |
+---------+---------------------+------------------------------+---------------------------+
| tidb    | 10.233.90.245:4000  | advertise-address            | 10.233.90.245             |
| pd      | 10.233.90.245:2379  | …
```
=> cluster, playground: add config `advertise-addr` to tiproxy

pkg/cluster/manager/destroy.go, pkg/cluster/manager/scale_in.go
https://github.com/pingcap/tiup/issues/2327
https://github.com/pingcap/tiup/issues/2375
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> update prometheus config when scale in

CHANGELOG.md, pkg/version/version.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Bump version to v1.15.0

components/playground/playground.go
This reverts commit 38b6c96c2d27f16bbc7fd95644235010d319f6cc.
- fix #2395
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Revert "playground: only pull nightly from cluster version (#2364)"

pkg/cluster/spec/tiflash.go
Fix https://github.com/pingcap/tiup/issues/2384
See https://github.com/pingcap/tiup/issues/2384
Tests 
- No code
It seems these codes do not have tests. I don't know how to add a test properly.
Code changes
- No
Side effects
- No
Release notes:
```release-note
NONE
```
=> Fix tiflash numa node not working issue

components/playground/instance/tikv.go, components/playground/playground.go, pkg/cluster/api/pdapi.go
Close #2396
can reload cluster with tag
Tests 
- Unit test
- No cod
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground/pdms: wait for tso component ready

cmd/mirror.go
`GetComponentManifest()` can return a nil manifest if it returns an error. `newMirrorRenewCmd()` ignores expiration errors when calling `GetComponentManifest()`. It should make sure that the manifest is not nil when calling `RenewManifest()`.
ref #2398
Tests 
Release notes:
```release-note
Bugfix: The `tiup mirror renew` command could segfault on expired manifests.
```
=> Improve handling of mirror renw

pkg/cluster/spec/validate.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: fix the tls check for tso and scheduling service

components/playground/playground.go, pkg/cluster/api/pdapi.go
close #2416.
Tests 
- Manual test
Release notes:
```release-note
NONE
```
=> playground: fix the health check

components/playground/command.go, components/playground/playground.go
close #2418
Tests 
```
$ bin/tiup-playground scale-out --tso 1
$ bin/tiup-playground display
Pid      Role        Uptime
---      ----        ------
1664279  pd          50.760217075s
1664294  tso         50.047913364s
1668333  tso         5.790315547s
1664307  scheduling  49.294502817s
1664365  tikv        43.760522609s
1664865  tidb        43.38240817s
1665074  tiflash     34.235445093s
$ bin/tiup-playground scale-in --pid 1664294
scale in tso success
$ bin/tiup-playground display
Pid      Role        Uptime
---      ----        ------
1664279  pd          1m4.192541288s
1668333  tso         19.222638732s
1664307  scheduling  1m2.726825553s
1664365  tikv        57.192846277s
1664865  tidb        56.814730897s
1665074  tiflash …
```
=> playground: support scaling ms instances when using playground

components/playground/grafana.go, components/playground/main.go, components/playground/playground.go, doc/user/playground.md
The Grafana port is fixed at 3000 and cannot be changed.
I have made it possible to specify the Grafana port via options.
Tests 
```
$ ./bin/tiup-playground --grafana.port 3333
Note: Version constraint  is resolved to v8.0.0. If you'd like to use other versions:
Use exact version:      tiup playground v7.1.0
Use version range:      tiup playground ^5
Use nightly:            tiup playground nightly
Start pd instance:v8.0.0
Start tikv instance:v8.0.0
Start tidb instance:v8.0.0
Waiting for tidb instances ready
127.0.0.1:4000 ... Done
Start tiflash instance:v8.0.0
Waiting for tiflash instances ready
127.0.0.1:3930 ... Done
🎉 TiDB Playground Cluster is started, enjoy!
Connect TiDB:    mysql --comments --host 127.0.0.1 --port 4000 -u root
TiDB …
```
=> Allow specifying Grafana port via command-line arguments

components/playground/instance/pd.go
Redundant passing of --config command line argument to pd when launching playground.
Remove redundant line.
Tests 
- Unit test
- No code
Ran manual test and it still works
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Remove redundant config arg when launching pd

pkg/cluster/manager/upgrade.go, pkg/cluster/operation/download.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> remove duplicate download when upgrade

components/playground/instance/pd.go, embed/templates/scripts/run_scheduling.sh.tpl, embed/templates/scripts/run_tso.sh.tpl, pkg/cluster/spec/scheduling.go, pkg/cluster/spec/tso.go, pkg/cluster/spec/validate.go, pkg/cluster/template/scripts/scheduling.go, pkg/cluster/template/scripts/tso.go
need to merge after https://github.com/tikv/pd/pull/8157
```bash
curl --location --request GET 'http://127.0.0.1:2379/pd/api/v2/ms/members/tso'
```
get
```bash
[
{
"name": "tso-0",
"service-addr": "http://127.0.0.1:2384",
"version": "v8.2.0-alpha-23-gdd72b9c19-dirty",
"git-hash": "dd72b9c19707ccbdb1801d379b3982a7944df23f",
"deploy-path": "/Users/pingcap/CS/PingCAP/pd/bin",
"start-timestamp": 1715577605,
"member-value": "ChtodHRwOi8vMTI3LjAuMC4xOjIzODQtMDAwMDAQp+L2iMCp3NUaGhVodHRwOi8vMTI3LjAuMC4xOjIzODQ="
},
{
"name": "tso-1",
"service-addr": "http://127.0.0.1:2386",
"version": "v8.2.0-alpha-23-gdd72b9c19-dirty",
"git-hash": "dd72b9c19707ccbdb1801d379b3982a7944df23f",
"deploy-path": "/Users/pingcap/CS/PingCAP/pd/bin",
"start-timestamp": 1715577605,
"member-value": …
```
=> pdms: add name to start pdms

components/playground/instance/pd.go, embed/templates/scripts/run_scheduling.sh.tpl, embed/templates/scripts/run_tso.sh.tpl, pkg/cluster/spec/scheduling.go, pkg/cluster/spec/tso.go, pkg/cluster/spec/validate.go, pkg/cluster/template/scripts/scheduling.go, pkg/cluster/template/scripts/tso.go
=> Revert "pdms: add name to start pdms"

pkg/environment/history.go, pkg/exec/run.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> hide password

CHANGELOG.md, pkg/version/version.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> bump version to v1.16.0

pkg/cluster/manager/destroy.go
Bug introduced by #2387. 
The task builder `b` is reused without reseting. Thus `FindTomestoneNodes` will be executed twice, which is not expected.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix duplicated prompt at `tiup-cluster prune`
```
=> cluster: remove duplicated tasks when prune

embed/templates/scripts/run_tiflash.sh.tpl
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> TiFlash: Enable and inactive prof when start

pkg/environment/history.go
As title.
Tests 
- Unit test
```
[xhe@M1PRO-2 tiup]$ ./bin/tiup tidb-lightning:v6.5.3 --tidb-password tidb
Starting component tidb-lightning: /Users/xhe/.tiup/components/tidb-lightning/v6.5.3/tidb-lightning --tidb-password ******
Verbose debug logs will be written to /var/folders/4q/x954lkc95gl34qjnx2hbcr640000gn/T/lightning.log.2024-07-09T14.51.18+0800
```
- No code
Code changes
Side effects …
=> hide other password args

components/playground/playground.go, components/playground/playground_test.go
From https://dev.mysql.com/doc/relnotes/mysql/8.1/en/news-8-1-0.html
> Comments in the mysql client are now enabled by default. To disable them, start mysql with the --skip-comments option.
> 
> Our thanks to Daniël van Eeden for the contribution. (Bug #109972, Bug #35061087, WL #15597)
This means we can shorten the commandline to connect to TiDB if the client is newer than 8.1.0.
Tests 
- Unit test
Side effects
Release notes:
```release-note
TiUP Playground now only prints `--comments` for older versions of MySQL Client.
```
=> playground: Only add --comments when needed

pkg/cluster/spec/tiflash.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: do not need to check TiFlash http_port

embed/examples/cluster/topology.example.yaml
Finding out how to set the tiflash-proxy configs in tiup is hard.
Add example of setting the tiflash-proxy configs
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tiflash: Add example of setting the tiflash-proxy configs

components/playground/instance/pd.go, embed/templates/scripts/run_scheduling.sh.tpl, embed/templates/scripts/run_tso.sh.tpl, pkg/cluster/manager/manager_test.go, pkg/cluster/manager/transfer_test.go, pkg/cluster/spec/scheduling.go, pkg/cluster/spec/spec.go, pkg/cluster/spec/tso.go, pkg/cluster/spec/validate.go, pkg/cluster/template/scripts/pdms_test.go, pkg/cluster/template/scripts/scheduling.go, pkg/cluster/template/scripts/tso.go, pkg/tidbver/tidbver.go
after https://github.com/tikv/pd/pull/8461, we can start PDms with name.
But startup previous pd which support ms before 8.3.0 will failure because of `unkown flag`
for 8.2.0 
```bash
$ cat tidb-deploy/tso-3379/scripts/run_tso.sh
#!/bin/bash
set -e
DEPLOY_DIR=/root/husharp/tidb-deploy/tso-3379
cd "${DEPLOY_DIR}" || exit 1
exec env GODEBUG=madvdontneed=1 bin/pd-server services tso \
--backend-endpoints="http://10.2.7.79:2379" \
--listen-addr="http://10.2.7.79:3379" \
--advertise-listen-addr="http://10.2.7.79:3379" \
--config=conf/tso.toml \
--log-file="/root/husharp/tidb-deploy/tso-3379/log/tso.log" 2>> "/root/husharp/tidb-deploy/tso-3379/log/tso_stderr.log"
```
after `./tiup-cluster upgrade tidb-test v8.2.0 --tso-version v8.3.0` and with 
```bash
tso_servers:
- host:  10.2.7.79
port: 3379 …
```
=> pdms(playground, cluster): add name to start pdms

components/playground/grafana.go, components/playground/instance/drainer.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/pump.go, components/playground/instance/ticdc.go, components/playground/instance/tidb.go, components/playground/instance/tiflash.go, components/playground/instance/tikv.go, components/playground/instance/tikv_cdc.go, components/playground/instance/tiproxy.go, components/playground/main.go, components/playground/monitor.go, components/playground/ngmonitoring.go, components/playground/playground.go, pkg/proxy/proxy.go, pkg/proxy/tcp_proxy.go, pkg/utils/freeport.go, pkg/utils/freeport_test.go
Sometimes we want to start multiple clusters concurrently (and also preserve them).
Preserving data is possible by specifying --tag.
But multiple co-exist clusters will meet issues after restart because dynamic port may be changed and stores are regarded as new stores.
This PR adds `--port-offset` so that this could work nicely, e.g:
- Cluster1: `--tag=cluster1 --port-offset=10000`
- Cluster2: `--tag=cluster2 --port-offset=20000`
Tests 
- Unit test
- No code
Code changes
Side effects
Related …
=> playground: Allow specifying port offset

pkg/crypto/rand/rand.go, pkg/telemetry/meta.go
Replace `math/rand` with `crypto/rand`, which resolve some potential security vulnerability issue according to some third-party security scanners.
As described.
Tests 
- No code
Code changes
Side effects
- None
- None
Release notes:
```release-note
NONE
```
=> pkg/crypto: replace 'math/rand' with 'crypto/rand'

components/playground/instance/process.go
When something is wrong, and tiup did not start the component correctly, playground instance may have a nil `process` pointer. Let us just prevent it from panic.
Refer https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fpd%2Fpull_integration_realcluster_test/detail/pull_integration_realcluster_test/809/pipeline/.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes: …
=> playground: add panic guard to prevent some corner cases

.github/workflows/integrate-dm.yaml, .github/workflows/integrate-playground.yaml, docker/control/Dockerfile, pkg/cluster/operation/download.go, pkg/repository/v1_repository.go, pkg/repository/v1_repository_test.go, pkg/repository/v1manifest/local_manifests.go, tests/tiup-playground/test_playground.sh
Close #2452 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix downloads racing bugs that results into 'No such file or directory'
```
=> *: try to fix download racing bugs

CHANGELOG.md, pkg/version/version.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Bump to version 1.16.1
```
=> bump version to v1.16.1

embed/examples/cluster/topology.example.yaml
As title.
Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> add cdc server topylogy example

components/playground/instance/pd_config.go, components/playground/playground.go
1. Fix a typo, to make `low-space-ratio` effective
2. Small improvements
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: Fix typo and update

pkg/cluster/manager/display.go, pkg/cluster/spec/spec.go
Signed-off-by: xhe <xw897002528@gmail.com>
Close #2470
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: display dashboard server URLs

pkg/cluster/operation/check.go
`tiup cluster check ...` might report different information than https://docs.pingcap.com/tidb/stable/hardware-and-software-requirements#os-and-platform-requirements
Tests 
Release notes:
```release-note
NONE
```
=> cluster: Update supported OS versions

components/playground/main.go, components/playground/playground.go, doc/user/playground.md
Signed-off-by: xhe <xw897002528@gmail.com>
Tests 
- Unit test
```
TiDB Playground Cluster will delete all data after exit. Please use --tag xx to pin the data dir.
🎉 TiDB Playground Cluster is started, enjoy!
Connect TiDB:    mysql --host 127.0.0.1 --port 4000 -u root
```
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: add warning for deletion of data dir

pkg/cluster/manager/display.go
After I patched grafana, the tiup cluster display does not display grafana url information, which causes users to feel confused and think that there is an unknown problem with the patch
grafana (patched) judgment added
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
./bin/tiup-cluster display tidb-xx
Cluster type:       tidb
Cluster name:       tidb-xx
Cluster …
```
=> display grafana with grafana patched

components/playground/instance/pd.go, components/playground/playground.go, pkg/cluster/api/pdapi.go, pkg/cluster/spec/scheduling.go, pkg/cluster/spec/tso.go, pkg/tidbver/tidbver.go
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> *: fix typo

.github/workflows/integrate-cluster-cmd.yaml, .github/workflows/integrate-cluster-scale.yaml, .github/workflows/integrate-dm.yaml, .github/workflows/integrate-playground.yaml, components/playground/instance/pd.go, components/playground/instance/pd_config.go, components/playground/instance/tidb.go, components/playground/instance/tidb_config.go, components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, components/playground/instance/tikv.go, components/playground/instance/tikv_config.go, components/playground/main.go, components/playground/playground.go
Previously https://github.com/pingcap/tiup/pull/2194 introduced --mode=tidb-disagg, and later I removed it and substituted it with --mode=tidb-cse in https://github.com/pingcap/tiup/pull/2386.
However, it turns out that actually we need both mode in daily development, so this PR add back tidb-disagg mode (and renamed it to tiflash-disagg mode for better name).
Tests 
Release notes:
```release-note
playground: Add --mode=tiflash-disagg
```
=> playground: Add --mode=tiflash-disagg

pkg/cluster/task/install_package.go
With a minimal install of Rocky Linux 9.5 tar isn't installed and the error could be improved
Without this PR:
```
$ tiup cluster check topology.yaml 
The SSH identity key is encrypted. Input its passphrase: 
+ Detect CPU Arch Name
- Detecting node 192.168.122.196 Arch info ... Done
+ Detect CPU OS Name
- Detecting node 192.168.122.196 OS info ... Done
+ Download necessary tools
- Downloading check tools for linux/amd64 ... Done
+ Collect basic system information
- Getting system info of 192.168.122.196:22 ... Error
Error: stderr: bash: line 1: tar: command not found
: executor.ssh.execute_failed: Failed to execute command over SSH for 'dvaneeden@192.168.122.196:22' {ssh_stderr: bash: line 1: tar: command not found
, ssh_stdout: , ssh_command: export LANG=C; …
```
=> cluster: improved error for missing tar

cmd/uninstall.go
Currently, `tiup unintall xxx` shows only directory name that was deleted.
```bash
$ tiup uninstall tiup:v1.16.0
/home/user/.tiup/components/tiup/v1.16.0
/home/user/.tiup/components/tiup
Uninstalled component `tiup:v1.16.0` successfully!
```
This PR implements more clearly messages.
```bash
$ tiup uninstall tiup:v1.16.0
Removing directory /home/user/.tiup/components/tiup/v1.16.0
Removing directory /home/user/.tiup/components/tiup
Uninstalled component `tiup:v1.16.0` successfully!
```
This PR changes only output messages.
Tests 
- Unit test
- No code
Code changes
Side effects
- Possible …
=> uninstall: more clearly messages

pkg/cluster/task/check.go
Close https://github.com/pingcap/tiup/issues/2159, https://github.com/pingcap/tiup/issues/2497
In `tiup cluster check topology.yaml --enable-disk=true`, the parent directories of `tiup-fio-test` are created with root but are not removed after the test. The subsequent operations will fail because the directories exist but the user doesn't have permission.
Before creating `tiup-fio-test`, check which parent directory doesn't exist and should be removed.
After testing, remove the parent directory.
Tests 
- Unit test
- No code
1. Remove `/home/xxx/data` and execute `tiup cluster check --enable-disk=true`. After the test, check that `/home/xxx/data` is removed.
2. Create ``/home/xxx/data` and execute `tiup cluster check --enable-disk=true`. After the test, check that …
=> cluster: remove created directories after fio test in `tiup cluster check`

components/cluster/command/check.go, pkg/cluster/manager/check.go, pkg/cluster/task/check.go
If `/tmp` is mounted with `noexec` then copying a binary and running it won't work. This adds an option to specify an alternative directory.
Tests 
Release notes:
```release-note
An option to specify the temporary directory has been added to `tiup cluster check`.
```
=> cluster: add option for tmpdir

embed/templates/config/prometheus.yml.tpl
ref https://github.com/pingcap/tidb/issues/59815
Tests 
- Unit test
1. tiup cluster deploy and check the config file of prometheus
```
...
scrape_configs:
- job_name: "overwritten-nodes"
honor_labels: true # don't overwrite job & instance labels
static_configs:
- targets:
- '127.0.0.1:9120'
- job_name: "tidb"
honor_labels: true # don't overwrite job & instance labels
metric_relabel_configs:
- action: drop
regex: tidb_tikvclient_source_request_seconds_count|tidb_tikvclient_batch_requests_sum|tidb_tikvclient_batch_requests_count|tidb_tikvclient_batch_pending_requests_sum|tidb_tikvclient_batch_pending_requests_count
source_labels:
- __name__
static_configs:
- targets:
- '127.0.0.1:10030'
...
```
2. The cluster is deployed …
=> drop some useless metrics in the prometheus config file

components/cluster/command/reload.go, components/cluster/command/upgrade.go, pkg/cluster/operation/upgrade.go
Also set ROLE and NODE for script usage
Tests 
- Unit test
```
tiup cluster deploy
tiup cluster reload --pre-restart-script 'echo $NODE $ROLE > /test'
cat /test (on instance machaine， check the value)
```
- No code
Code changes
Side effects
Release notes:
```release-note
cluster: add ROLE and NODE variable in custom upgrade scripts
```
=> cluster: fill node & role information in custom upgrade scripts

.github/workflows/install.yaml, .github/workflows/integrate-cluster-cmd.yaml, .github/workflows/integrate-cluster-scale.yaml, .github/workflows/integrate-dm.yaml, .github/workflows/integrate-playground.yaml, .github/workflows/integrate-tiup.yaml, .github/workflows/release-tiup.yaml, .github/workflows/reprotest.yaml, pkg/cluster/manager/reload.go, pkg/cluster/spec/grafana.go, pkg/cluster/spec/grafana_test.go, pkg/cluster/spec/monitoring.go, pkg/cluster/spec/monitoring_test.go, pkg/cluster/task/init_config_test.go
ref https://github.com/pingcap/tiup/issues/2531
Support changing the data source when multiple data sources exist
Introduce the VMConfig
- `enableVMRemoteWrite` moved to VMConfig's `enable`
- added the config item `IsVMDefaultDatasource` to switch vm datasource 
Once you configure the isDefaultDatasource, run:
```
tiup cluster reload <cluster-name> -N grafana_node:3000 
```
it will re-generate the dashboards template with the new datasource.
Tests 
- Unit test
- No code
Code changes
Side effects
- Breaking backward …
=> *: Support changing the data source when multiple data sources exist

components/playground/instance/dm_master.go, components/playground/instance/dm_worker.go, components/playground/instance/drainer.go, components/playground/instance/instance.go, components/playground/instance/pd.go, components/playground/instance/pd_config.go, components/playground/instance/pump.go, components/playground/instance/ticdc.go, components/playground/instance/tidb.go, components/playground/instance/tidb_config.go, components/playground/instance/tiflash.go, components/playground/instance/tiflash_config.go, components/playground/instance/tiflash_pre7.go, components/playground/instance/tikv.go, components/playground/instance/tikv_cdc.go, components/playground/instance/tikv_config.go, components/playground/instance/tiproxy.go, components/playground/main.go, components/playground/monitor.go, components/playground/ngmonitoring.go, components/playground/playground.go
Currently playground cluster is boot for debug-friendly by default.
- Add `--perf` to allow the cluster boot for higher performance instead of debug friendly.
Currently only TiFlash config is polished (and is sufficient for testing the TiDB cluster using VectorDBBench). Other config can be also added if someone need it.
- Now there are more and more global options. It makes code hard to read. So I reorganized these options and grouped them into a single structure. In this way it is more clear and will be easy to add global options later.
Tests 
Tested with --perf, --mode=tidb-cse and all works as expected.
Release notes:
```release-note
playground: Add --perf for starting cluster for higher performance
```
=> playground: Add --perf for starting cluster for higher performance

components/playground/instance/instance.go, components/playground/instance/tiflash_config.go, components/playground/instance/tikv_config.go, components/playground/instance/tikv_worker.go, components/playground/main.go, components/playground/playground.go, pkg/cluster/spec/instance.go
When `--mode=tidb-cse`, a fully functional tikv-worker process will be started as well (with remote compactor, remote cop and schema manager running).
Additionally, when `--tikv.columnar` is specified in this mode, TiKVColumnar query will be enabled (this brings all TiFlash Compute Node to read via TiKVColumnar).
Tests 
- Manual test
```
/Users/breezewish/Work/tiup/bin/tiup-playground v7.3.0 --mode=tidb-cse --tag serverless \
--db.binpath ../tidb-cse/bin/tidb-server \
--kv.binpath ../tikv-cse/target/release/tikv-server \
--pd.binpath ../pd-cse/bin/pd-server \
--tiflash.binpath ../tiflash-cse/cmake-build-Release/dbms/src/Server/tiflash \
--tiflash.compute 1 --tikv.columnar
```
Release notes:
```release-note
playground: Support tikv-worker and --tikv.columnar in tidb-cse mode
```
=> playground: Support tikv-worker and --tikv.columnar in tidb-cse mode

go.mod, go.sum, pkg/tui/tui.go
ref #2508 
Switch back from forked go-pretty to upstream to make packaging and future maintenance easier 
The fork was done because of the `DoNotFillSpaceWhenEndOfLine` option that was added. But it looks like `t.SuppressTrailingSpaces()` achieves the same. See also https://github.com/jedib0t/go-pretty/pull/318
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Switch from go-pretty fork back to upstream

pkg/cluster/spec/instance.go, pkg/cluster/spec/tispark.go, pkg/cluster/task/monitored_config.go
- Improve SELinux compatibility
- Fix the context of the systemd files after moving them from `/tmp` to `/etc/systemd`
This doesn't change the SELinux policy. We *could* do that later if we want. So no docs changes for now.
Because of this we don't change the `tiup cluster check` for SELinux.
Tests 
Tested:
- Deploy cluster
- Start/Stop cluster
Release notes:
```release-note
NONE
```
=> cluster: improve SELinux compatibility

components/playground/instance/tici.go
close #xxx
Update the default config filename of tici according to https://github.com/pingcap-inc/tici/pull/221
Update the default port of tici according to https://github.com/pingcap-inc/tici/pull/232
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> tici: Update the default config filename & default port of tici

embed/templates/systemd/system.service.tpl, pkg/cluster/spec/instance.go, pkg/cluster/task/monitored_config.go, pkg/cluster/template/systemd/system.go, pkg/meta/resource_ctrl.go
close #xxx
Tests 
```
tiup cluster deploy
see if service file have those fields
```
Code changes
Side effects
Release notes:
```release-note
cluster: add stop/start timeout for systemd service
```
=> cluster: add stop/start timeout for systemd service

go.mod, go.sum, pkg/utils/ioutil.go
ref #2508 
Replace github.com/otiai10/copy with [`os.CopyFS`](https://pkg.go.dev/os#CopyFS) that was introduced in Go 1.23.0
This removes one direct dependency
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> Replace otiai10/copy with os.CopyFS

components/playground/playground.go
close #xxx
Make the url configurable by the passed config.
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> playground: make the tici changefeed endpoint configurable

pkg/cluster/api/pdapi.go, pkg/cluster/spec/pd.go
close #2223
Tests 
This can only be tested by a cluster with more than 2 pd server, using pd-ctl set a high leader_priority before testing.
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: clear leader_priority for pd leader if exist

pkg/cluster/operation/upgrade.go
introduced by #2513
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```
=> cluster: prevent panic when the operation is not upgrade
