pingcap/tiup

cmd/component.go
cmd/root.go
cmd/update.go
pkg/meta/component.go
pkg/meta/repository.go
pkg/meta/version.go

implement the tiup update subcommand

---

cmd/component.go
cmd/run.go

Fix getBinPath

---

cmd/component.go
cmd/self.go
main.go
mirror/tiup-component-pd.index
mirror/tiup-component-tidb.index
mirror/tiup-component-tikv.index
mirror/tiup-manifest.index
pkg/meta/component.go
pkg/meta/mirror.go
pkg/meta/repository.go

add mirror manifest

---

cmd/run.go
components/playground/go.mod
components/playground/package.sh
mirror/fetch.sh
mirror/tiup-component-playground.index
mirror/tiup-manifest.index

add playground component to mirror manifest

---

components/playground/main.go
install.sh

Update install script

---

install.sh

Hightlight notify

---

cmd/run.go
components/playground/main.go

Fix mass log

---

Makefile

Put install.sh to package

---

install.sh

Fixes to some quoting errors and POSIX problems in install.sh.

Improvements to install.sh

---

components/playground/instance/tidb.go
components/playground/instance/tikv.go

Write log to disk

---

Makefile
cmd/binary.go
cmd/install.go
cmd/list.go
cmd/run.go
cmd/uninstall.go
cmd/update.go
pkg/localdata/profile.go
pkg/meta/meta_test.go
pkg/meta/repository.go
pkg/meta/version.go

support nightly version

---

components/playground/main.go

Replace dsn with mysql connect string

---

components/playground/instance/pd.go
components/playground/instance/tidb.go
components/playground/instance/tikv.go
components/playground/main.go
pkg/utils/freeport.go

Fix port reuse

---

cmd/list.go
cmd/run.go
components/playground/Makefile
components/playground/instance/pd.go
components/playground/instance/tidb.go
components/playground/instance/tikv.go
components/playground/main.go
pkg/localdata/constant.go
pkg/localdata/profile.go
pkg/meta/repository.go
pkg/meta/version.go
pkg/utils/ioutil.go

refactor tiup run command and introduce name for instance

---

components/playground/instance/pd.go
components/playground/instance/tidb.go
components/playground/instance/tikv.go
pkg/utils/freeport.go

Fix freeport

---

cmd/status.go

cmd: output the args in tiup status

---

components/playground/instance/pd.go

change the default PD port

---

cmd/update.go

cmd: fix 'text file is busy' while tiup update --self

---

cmd/testdata/tiup-component-test.index
components/package/main.go
pkg/meta/testdata/test1.bin

Tests 
- Unit test
- No code
Code changes
Side effects

Fix index cache

---

cmd/clean.go
cmd/root.go
cmd/status.go
tests/expected/tiup/tiup-h.output
tests/expected/tiup/tiup-help.output
tests/expected/tiup/tiup.output

fix help message
Tests 
- Unit test
Code changes
Side effects

cmd: fix help message

---

cmd/run.go
components/playground/instance/pd.go
components/playground/instance/tidb.go
components/playground/instance/tikv.go
components/playground/main.go
tests/expected/tiup/tiup-run-test-flag.output
tests/expected/tiup/tiup-run-test-v1.1.1.output
tests/expected/tiup/tiup-run-test.output
tests/expected/tiup/tiup-run-test2.output

* remove "--" in starting command of playground
* add progress bar when the playground is starting the cluster
* color the monitor's link to green
Tests 
- Unit test
Code changes
- None
Side effects
- None

fix playground

---

components/tiops/tiops/cmd.py

Tests 
- Unit test
- No code
Code changes
Side effects

fix err msg for tiops help

---

mirror/localmirrors.sh
pkg/meta/meta.go
pkg/repository/repository.go

pkg/repository: support specify the GOOS and GOARCH

---

components/playground/main.go
pkg/meta/meta.go

Signed-off-by: mapleFU <1506118561@qq.com>
Tests 
- Unit test
- No code
Code changes
Side effects

Try to fix lint and bug

---

components/tiops/tiops/topology.py

Tests 
- Unit test
- No code
Code changes
Side effects

fix some tiops error

---

localmirrors.sh

The origin way means download 2 url.
-O,  --output-document=FILE      write documents to FILE
Tests 
- Unit test
- No code
Code changes
Side effects

Fix specify wirte file.

---

components/package/Makefile
components/package/main.go

Tests 
- Unit test
- No code
Code changes
Side effects

Add -C for package component and support multiple targets

---

components/package/main.go
pkg/set/string_set.go

Tests 
- Unit test
- No code
Code changes
Side effects

Add remove method to StringSet

---

pkg/set/string_set.go

Tests 
- Unit test
- No code
Code changes
Side effects

Support difference on StringSet

---

README.md

Add some docs for contributors to README.md
PTAL @lonng

README: add some overview docs and instructions for building

---

README.md
cmd/help.go
cmd/install.go
cmd/list.go
cmd/root.go
cmd/uninstall.go
cmd/update.go
index.html
pkg/meta/meta.go
tests/expected/tiup/tiup-h.output
tests/expected/tiup/tiup-help-install.output
tests/expected/tiup/tiup-help.output
tests/expected/tiup/tiup-uninstall-test-v1.1.2.output
tests/expected/tiup/tiup.output

Simply cleans up some English language issues in help text and error/info messages.
Tests 
- No code
Please update documentation in any cases where output of commands may have changed in this patch.

Cleaned up some English language issues

---

components/3rd/prometheus.sh

Signed-off-by: yeya24 <yb532204897@gmail.com>
Tests 
- Unit test
- No code
Code changes
Side effects

Update prometheus to 2.17.1

---

cmd/install.go
cmd/list.go
cmd/run.go
components/package/main.go
pkg/repository/component.go
tests/expected/tiup/tiup-install-not-exists.output

This PR support hides the component when `tiup list` and fix the bug that installs unsupported components.
Tests 
- Unit test

support hide component when tiup list subcommand

---

pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects

Add build info for tiup cmd

---

components/mirrors/main.go
go.sum
pkg/repository/file_source.go
pkg/repository/file_source_test.go
pkg/repository/repository.go
pkg/repository/repository_test.go
pkg/repository/version.go
pkg/utils/sha1.go

This PR implements the `mirrors` component, which is used to build a local mirror repository.

implement the mirrors components

---

cmd/cmd_test.go
components/bench/main.go
components/mirrors/main.go
pkg/localdata/profile.go
pkg/meta/meta.go
pkg/repository/mirror.go
pkg/repository/progress.go
pkg/repository/version.go
pkg/utils/sha1.go

This PR introduces the `DownloadProgress` interface to allow the external application to customize the download progress displaying.

improve the download progress display

---

README.md
doc/README.md
doc/design/README.md
doc/dev/README.md
doc/user/README.md

This is a text-only change; no code. Create a doc directory and move some existing documentation there, plus add a very small outline for design docs.
PTAL @lonng

Add a doc directory and outline

---

components/doc/baseof.tpl.html
components/doc/main.go

Tests 
- Unit test
- No code
Code changes
Side effects

Add doc component

---

cmd/run.go

Signed-off-by: Zheng Xiangsheng <hundundm@gmail.com>
* According to this [issue](https://github.com/pingcap/pd/issues/392), after receiving the SIGINT, the exit code of 1 is reasonable behavior, not an error.
* ignore exit code is 1 when SIGINT is received

cmd: ignore exit code is 1 when SIGINT is received

---

components/doc/baseof.tpl.html
components/doc/main.go

Tests 
- Unit test
- No code
Code changes
Side effects

Use english for default on doc

---

Makefile
cmd/help.go
components/ctl/main.go
pkg/utils/args.go
tests/cases_cov.json
tests/expected/tiup/tiup-h.output
tests/expected/tiup/tiup-help-ctl.output
tests/expected/tiup/tiup-help-doc.output
tests/expected/tiup/tiup-help.output
tests/expected/tiup/tiup.output
tests/tiup_mirrors/prepare.sh

Tests 
- Unit test
- No code
Code changes
Side effects

Combile *-ctl to one component `ctl`

---

components/ctl/main.go
install.sh

Tests 
- Unit test
- No code
Code changes
Side effects

Fix ctl with transparent params

---

cmd/list.go

Tests 
- Unit test
- No code
Code changes
Side effects

Bugfix: panic on mirror error

---

components/bench/main.go
components/bench/tpch.go

Tests 
- Unit test
- No code
Code changes
Side effects

bench: set default sf to 1

---

doc/design/README.md
doc/design/requirements.md

This PR is a start to the design docs section, adding a document for goals, requirements, and vision for the project. The doc is incomplete, I've just added my opinions on some areas. I'd really input from others with more context about how the tool is intended to be used.
PTAL @lonng @c4pt0r @lucklove @AstroProfundis

Add requirements doc

---

doc/design/README.md
doc/design/manifest.md

~~Still some TODOs to complete and needs a good check over. Uploading early because it is taking quite a while.~~
cc #114, #117, #119, #120, #121,

Manifest and server organisation design doc

---

components/playground/main.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
Fixes #199 
Verification
``` bash
➜  ~ tiup playground  --db.host 0.0.0.0 --pd.host 0.0.0.0 --tiflash 0                                                                                                    <<<
Starting component `playground`: /Users/yeya24/.tiup/components/playground/v0.0.9/playground --db.host 0.0.0.0 --pd.host 0.0.0.0 --tiflash 0
Playground Bootstrapping...
Starting component `pd`: /Users/yeya24/.tiup/components/pd/v4.0.0-rc.1/pd-server --name=pd-0 --data-dir=/Users/yeya24/.tiup/data/Ryh0Eeb/pd-0/data --peer-urls=http://0.0.0.0:2380 --advertise-peer-urls=http://0.0.0.0:2380 --client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://0.0.0.0:2379 --log-file=/Users/yeya24/.tiup/data/Ryh0Eeb/pd-0/pd.log …
```

Add db.host and pd.host flag

---

pkg/localdata/manifests.go
pkg/localdata/profile.go
pkg/repository/keys.go
pkg/repository/manifest.go
pkg/repository/manifest_test.go
pkg/repository/mirror.go

cc #201 
Support loading/saving of new manifests. Needed some refactoring of repository/manifests.go
PTAL @AstroProfundis

localdata: load/save new manifests

---

go.mod
go.sum
pkg/repository/crypto/keys.go
pkg/repository/crypto/rsa.go
pkg/repository/crypto/rsa_test.go
pkg/repository/keys.go
pkg/repository/local_manifests.go
pkg/repository/manifest.go
pkg/repository/manifest_test.go
pkg/repository/v1_repository.go

Tests 
- Unit test
- No code
Code changes
Side effects

Add RSA signature

---

Makefile
doc/design/manifest.md
pkg/repository/crypto/keys.go
pkg/repository/v1_repository.go
pkg/repository/v1_repository_test.go
pkg/repository/v1manifest/local_manifests.go
pkg/repository/v1manifest/manifest.go
pkg/repository/v1manifest/manifest_test.go
pkg/repository/v1manifest/repo.go
pkg/repository/v1manifest/types.go
tools/migrate/main.go

Based on top of #217 and that should land first
Implements updating of index and component manifests
PTAL @lucklove

Implement update index and update component manifest

---

cmd/repo.go
pkg/repository/crypto/keys.go
pkg/repository/crypto/rsa.go
pkg/repository/crypto/rsa_test.go
pkg/repository/v1_repository_test.go
pkg/repository/v1manifest/manifest.go
pkg/repository/v1manifest/manifest_test.go
pkg/repository/v1manifest/repo.go
pkg/repository/v1manifest/types.go
tools/migrate/main.go

Add basic implementation of `Component` manifest, and add a function to generate new component.
Also implemented signing of manifests during init.
An `AddComponent()` is added but not used yet, commands will be added in a following PR.
Tests 
- Unit test
Code changes
Side effects

Add basic implementation of component

---

pkg/repository/v1manifest/repo.go
tools/migrate/main.go

Tests 
- Unit test
- No code
Code changes
Side effects

Generate local keys

---

pkg/repository/crypto/keys.go
pkg/repository/crypto/rsa.go
pkg/repository/crypto/rsa_test.go
pkg/repository/v1_repository.go
pkg/repository/v1_repository_test.go
pkg/repository/v1manifest/keys.go
pkg/repository/v1manifest/local_manifests.go
pkg/repository/v1manifest/manifest.go
pkg/repository/v1manifest/manifest_test.go
pkg/repository/v1manifest/repo.go
pkg/utils/sha.go
tools/migrate/main.go

Also does some minor refactoring.
PTAL @lucklove

Implement fetching and checking of components using v1 manifests

---

pkg/repository/mirror.go
pkg/repository/v1_repository.go

Make sure update root success iff we reach the newest version

---

cmd/repo.go

- genkey: store keyinfo as ~/.tiup/private.json instead of ~/.tiup/private.pem
- genkey: support -p flag to show public key content:
```
KeyID: 79fa37bc6b41d52f0980caf1574768a001478e1d11af07c876bf70f06076f258
KeyContent: 
{
"keyid_hash_algorithms": [
"sha256",
"sha512"
],
"keytype": "rsa",
"keyval": {
"public": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0kgU3v3SxYzm5J6P+GPP\nmy6toBnKYtTViAVmpUJiIEjdZ9NLpoJU0na9q0CD8sIgo2Js/W/owJUvSj6rm8us\nsu/Ve5KsoJN6zca2am1uZ5IKnc48i0mCv76WXawCxM+NFGqSCMJcltlhj3fC/GDS\ngu+BiIbrgR1PgJf6Jk6l7uMJdN3TL6JJQcEC4lz+2hj5zoVNYkq06ZC79j2tPDCI\nkTAYGF/TAAVLH08/kGH5ZeRPlVKJ7cwW3OniLM5NeFnS8+shRNb6AYr7xju3Ikbw\nDo14ipIghBI0iAxn6Lvr/iilc7TM7RWJ4OiTrmK3SQSJ+U6H2N2/I5OGEHBEKzbA\nOQIDAQAB\n---- …
```

Refine genkey with keyinfo instead of pem file

---

pkg/repository/v1manifest/repo.go
pkg/utils/ioutil.go
tools/migrate/main.go

Generate a repository in new v1 format from a local v0 mirror
Adjust manifest formats to fit latest implementation
Tests 
Code changes
Side effects

tools/migrate: adjust manifest parsing

---

tools/migrate/main.go

Fix generate manefest file names
root index component should be versioned
also, root.json is a copy of the newest version

Fix generate manefest file names

---

cmd/cmd_test.go
cmd/install.go
cmd/run.go
cmd/update.go
pkg/localdata/profile.go
pkg/meta/meta.go
pkg/repository/mirror.go
pkg/repository/v0manifest/component.go
pkg/repository/v1_repository.go
pkg/repository/v1_repository_test.go
pkg/repository/v1manifest/local_manifests.go
pkg/repository/v1manifest/manifest.go
pkg/repository/v1manifest/repo.go
pkg/utils/args.go
tests/expected/tiup/tiup-install-not-exists.output
tests/expected/tiup/tiup-self-update.output
tests/expected/tiup/tiup-update-test-nightly.output
tests/expected/tiup/tiup-update-test.output

Update and install components using v1 manifests

---

pkg/repository/v1_repository.go
pkg/repository/v1manifest/manifest.go

Use SignatureError error

---

tools/migrate/main.go

1. Fix wrong length(less then the finally file write).
2. Fix losing snapshot role in root.json

Fix migrate

---

cmd/run.go
go.mod
pkg/meta/meta.go
pkg/repository/v1_repository.go
pkg/repository/v1_repository_test.go
pkg/repository/v1manifest/local_manifests.go
pkg/utils/args.go

In order to do this test it required a little refactoring, but nothing very significant.
PTAL @july2993

Implement a test for UpdateComponents

---

cmd/uninstall.go
tests/cases.json

Fix https://github.com/pingcap-incubator/tiup/issues/150
Change the behavior of `tiup uninstall --self` and keep user data.

Change the behavior of 'tiup uninstall --self' and keep user data

---

pkg/meta/meta.go
pkg/repository/v1_repository.go
pkg/repository/v1manifest/local_manifests.go

support self update
TODO: make sure the server supports  tiup as a component too and test it.

Self update

---

components/bench/main.go
components/bench/misc.go
components/bench/tpcc.go
go.mod
go.sum

Signed-off-by: mahjonp <junpeng.man@gmail.com>
See https://github.com/pingcap/go-tpc/pull/44
We have solved the problem in go-tpc, and this PR only update its dependency.
Tests 
- Unit test
- No code
Code changes
Side effects

bench: update the go-tpc dependency

---

cmd/run.go
cmd/telemetry.go
tests/expected/tiup/tiup-h.output
tests/expected/tiup/tiup-help.output
tests/expected/tiup/tiup.output

ref #212 
Temparally disalbe telemetry

Temparally disalbe telemetry

---

cmd/telemetry.go
components/playground/instance/tiflash.go
components/playground/main.go
pkg/localdata/profile.go
pkg/meta/meta.go

new version playground should still work but without test.

rename BinaryPath in Profile to BinaryPathV0

---

tools/migrate/main.go

Treat TiUP as a component when migrating

Treat TiUP as a component when migrating

---

pkg/repository/v1manifest/types.go
tools/migrate/main.go

Add standalone/hidden field to index.json

Add standalone/hidden field to index.json

---

pkg/repository/v1manifest/manifest.go
pkg/repository/v1manifest/repo.go
pkg/repository/v1manifest/types.go

Verify signatures base on JSON raw message to prevent verify failed from specification changing.

Verify signatures base on JSON raw message

---

cmd/list.go

The command `tiup list` doesn't compatible with previous, this PR introduces `--verbose` and `--all` flags to control the behavior of `tiup list` subcommand.
```
➜  tiup git:(verbose-list) ✗ tiup list
Available components:
Name        Owner    Description
----        -----    -----------
package     pingcap  A toolbox to package tiup component
tidb        pingcap  TiDB is an open source distributed HTAP database compatible with the MySQL protocol
bench       pingcap  Benchmark database with different workloads
cluster     pingcap  Deploy a TiDB cluster for production
client      pingcap  A simple mysql client to connect TiDB
ctl         pingcap  
mirrors     pingcap  Build a local mirrors and download all selected components
playground  pingcap …
```

Add the --verbose mode when tiup list command

---

cmd/list.go

Fix fail to load component and not handle install only

Fix fail to load component and not handle install only

---

cmd/help.go
cmd/run.go
doc/user/README.md
doc/user/overview.md
doc/user/package-manage.md
doc/user/package.md
tests/cases_cov.json
tests/expected/tiup/tiup-h.output
tests/expected/tiup/tiup-help.output
tests/expected/tiup/tiup.output

clear refresh prompt
clear refresh prompt

clear refresh prompt

---

doc/user/cluster.md

The link of `topology.example.yaml` was invalid.
Update the link of `topology.example.yaml`.
Tests 
- No code

doc: fix the link of topology.example.yaml

---

cmd/list.go

show all components for installed index
Tests 

show all components for installed index

---

cmd/uninstall.go

When we remove version one by one, the component dir won't be deleted even if we have deleted all versions.
remove whole component dir for the last removed version
Tests 

remove whole component dir for the last removed version

---

cmd/uninstall.go
pkg/assets/local_install.sh.go

Remove the TIUP_HOME/manifests when offline local install

Remove the TIUP_HOME/manifests when offline local install

---

pkg/repository/v1manifest/local_manifests.go

Fix the bug that ManifestVersion always return 0

Fix the bug that ManifestVersion always return 0

---

pkg/repository/crypto/rsa.go
pkg/repository/mirror.go
pkg/repository/v1_repository.go
pkg/repository/v1_repository_test.go
pkg/repository/v1manifest/local_manifests.go
pkg/repository/v1manifest/manifest.go

Fix lint of pkg/... enable all linter of golangci

Fix lint of pkg/... enable all linter of golangci

---

cmd/clean.go
pkg/repository/clone_mirror.go
pkg/repository/mirror.go

…l for not found error
some prompts are hard to recognize.
add prompt for tiup clean, skip tiup not found error, add resource/url for not found error

add prompt for tiup clean

---

cmd/run.go
go.sum

force user update the playground/cluster component
```
➜  tiup git:(fix-tags) ✗ tiup playground
Failed to start component `playground`
Error: incompatible component version, please use `tiup update playground` to upgrade to the latest version
```

force user update the playground/cluster component

---

pkg/version/version.go

bump version to v1.0.0

---

pkg/repository/mirror.go

Fix panic problem.
change `Annotatef` to `Errorf`
Tests 

fix http download nil pointer

---

cmd/mirror.go
pkg/localdata/constant.go
tools/migrate/main.go

Tests 
Code changes
Side effects

*: update migrate tool and repo sub command

---

components/playground/instance/instance.go
components/playground/main.go

Tiny refactor for opt of playground

Tiny refactor options of playground

---

Makefile
doc/user/cluster.md
pkg/repository/v1_repository.go
pkg/version/version.go

- Update manifest version check, not reporting error if cached version is the same as remote
- Remove build time from version string, it's not needed for reproducible build

*: update manifest version checking & build miscs

---

pkg/cluster/operation/destroy.go

1. It does not make sense to check port for down **after** deleting files and dirs
2. The error could be ignored when checking port for down, as there might be other process listening on that port after we stopped the service, and before we start destroying the instance
Tests 

cluster/destroy: fix wait for down & ignore the timeout error

---

cmd/mirror.go
pkg/repository/clone_mirror.go
pkg/repository/remote/upload.go
pkg/repository/utils/hash.go
pkg/version/version.go
tools/migrate/main.go

- Use HashFile to calculate tarball hash
- Fix sha512 hash in component manifest

Refactor the upload logic

---

pkg/repository/clone_mirror.go

save key to directory `/keys` while clone.
Tests 
- Unit test
- No code
Code changes
Side effects

save key to keys

---

cmd/run.go
cmd/telemetry.go
tests/expected/tiup/tiup-h.output
tests/expected/tiup/tiup-help.output
tests/expected/tiup/tiup.output

Enable telemetry

---

install.sh
pkg/cluster/template/install/local_install.sh.go

This PR enables tiup in arm64 by adding arm64 as a valid platform in the install script.

Support arm64 in install script

---

Makefile

Tests 
- Unit test
- No code
Code changes
Side effects

Add server target in Makefile

---

.github/workflows/reprotest.yaml

Add a CI workflow to check for reproducible build
Tests 

workflow: add reprotest ci

---

pkg/environment/env.go

Skip update or install tiup when execute `tiup install/update`.
Tests 

Skip tiup component when tiup update/install

---

pkg/version/version.go

Release v1.0.2

---

pkg/cluster/flags/debug.go

Fix default mode

---

components/playground/playground.go

fix not starting tiflash in playground

fix not starting tiflash in playground

---

server/store/qcloud.go

Tests 
- Unit test
- No code
Code changes
Side effects

Fix tiup-server upstream fetch

---

pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects

Release v1.0.3

---

__config.yml

ignore the doc directory when building Github pages

ignore the doc directory when building Github pages

---

README.md

fix the coverage badge

---

pkg/utils/ioutil.go
tests/tiup/.gitignore

After importing, it raises a `directory not empty` error when trying to move the inventory dir to a new location.

utils: fix directory removing

---

pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects

Release 1.0.4

---

doc/user/cluster.md

Fix the dead link in documentations

Fix the dead link in documentation

---

cmd/mirror.go

resolve https://github.com/pingcap/tiup/issues/492
fix genkey panic bug
Tests 
- Unit test
- No code
Code changes
Side effects

fix genkey panic bug

---

examples/topology.example.yaml

Add syncer.ignore-table example

Add syncer.ignore-table example

---

pkg/cluster/clusterutil/cluster.go

tiup-cluster： disable progress when downloading components

tiup-cluster： disable progress when downloading components

---

pkg/version/version.go

- Bugfix:
- Fix timeout when target directory exists and there is lots of content (#501)
- executor/ssh: fix PATH for non-shell executors (#510)
- Fix tiup server transaction bug (#505)
- Fix the bug that generate wrong snapshot meta when tiup mirror clone (#482)
- Reorder imported (ansible) config priority (#500)

Release 1.0.5

---

pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects

Release v1.0.6

---

components/ctl/main.go

Fix #508 
Tests 
- No code
Code changes
- None
Side effects
- None

Support cdc cli in tiup ctl

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/general-question.md

update github issue template

---

examples/minimal.yaml
examples/topology.example.yaml

Change example to show how to deploy to different arch

---

.github/workflows/ci.yaml
.github/workflows/integrate.yaml
.github/workflows/reprotest.yaml

Trigger the Github actions when PR merged.

Run github action after PR merged

---

pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects

Bump v1.0.8

---

.github/workflows/integrate.yaml
tests/tiup-cluster/script/cmd_subtest.sh
tests/tiup-cluster/script/scale_core.sh
tests/tiup-cluster/script/scale_tools.sh
tests/tiup-cluster/test_cmd.sh
tests/tiup-cluster/test_cmd_no_cdc.sh
tests/tiup-cluster/test_scale_core.sh
tests/tiup-cluster/test_scale_tools.sh
tests/tiup-cluster/test_upgrade.sh

Split integrate testing jobs of `cluster` to smaller jobs to speed up the CI a little.
Tests 

tests: split CI jobs to smaller groups

---

pkg/cluster/spec/spec.go

Tweak the upgrade order of components

---

CHANGELOG.md
pkg/version/version.go

Add changelog and bump 1.0.9
Add changelog and bump 1.0.9

Add changelog and bump 1.0.9

---

.github/pull_request_template.md
doc/dev/release-note-guide.md

Add release guide

---

doc/user/playground.md

Part of `playground.md` is not translated, and it seems strange.
Just do the translation.
Tests 
- No code

Fix an untranslated part of playground.md

---

components/cluster/command/root.go
components/dm/command/root.go
pkg/logger/audit.go

the deploy command is missing at some time in CI for unknown reason:
https://github.com/pingcap/tiup/pull/654/checks?check_run_id=1002381009
this PR make sure we do write audit success.
fail the command if failed to write audit
```release-note
NONE
```

fail the command if failed to write audit

---

examples/dm/topology.example.yaml
pkg/cluster/api/pdapi.go

Remote component specified in tryURLs
also, add the `name` in example
Release notes:
```release-note
NONE
```

Remove component specified in tryURLs

---

docker/README.md
docker/docker-compose.yml

YAML indent with space
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

typo(docker): indent

---

.github/workflows/integrate.yaml
docker/control/Dockerfile

Try to fix the codecov report
Release notes:
```release-note
NONE
```

ci: apply codecov path fix

---

CHANGELOG.md
pkg/version/version.go

Bump v1.1.2

---

pkg/cluster/api/binlog.go

Fix panic if the query key not exist
check and return error
Tests 
Release notes:
```release-note
NONE
```

Fix panic if the query key not exist

---

components/playground/command.go
components/playground/playground.go
tests/tiup-playground/test_playground.sh

remove the duplicated code in [components/playground](components/playground) module.
Tests 
- Unit test
Release notes:
```release-note
NONE
```

playground: dry, rm duplicated code

---

components/err/error.go
components/err/testdata/tidb.toml

Adjust error spec due to https://github.com/pingcap/tidb/pull/20303

Adjust error spec

---

doc/user/README.md

Update the output of TiUp and add links to TiDB docs
Tests 
- No code
Release notes:
```release-note
NONE
```

docs: update user/README.md

---

README.md

No existing issue.
Fix the broken link.
Tests 
- No code
Release notes:
```release-note
NONE
```

Fix the broken contribution guide link in README.md

---

components/errdoc/main.go
components/errdoc/spec/spec.go

Currently, we cannot search the errors documentation via error code prefix, this PR fixes this issue.
Tests 
- Unit test
```
$ tiup errdoc BR:Restore
restore checksum mismatch
invalid backup
invalid restore range
invalid rewrite rule
restore mode mismatch
region does not have peer
restore range mismatch
failed to restore remove rejected store
resolved ts constrain violation
schema not exists
fail to split region
restore table ID mismatch
failed to write and ingest
13 matched
```
Release notes:
```release-note
NONE
```

Fix search error documentation via error code

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Bump v1.2.3

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Bump v1.2.5

---

cmd/mirror.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Use more readable mirror init command

---

cmd/mirror.go
pkg/repository/v1manifest/repo.go

Introduced by https://github.com/pingcap/tiup/pull/967
The tiup mirror sign doesn't handle --key flag correctly for local manifest file
We can use `tiup mirror sign` command to sign manifest file for both local manifest and remote manifest, and it provide a `--key` flag to specify a custom private key file. But for local manifest, it doesn't handle the flag correctly (still use the `args[1]` as extra key file instead of `--key`) 
Use `--key` flag for both local and remote sign
Tests 
- Unit test
- No code
Code changes
Side effects
- Increased code …

Fix mirror sign command

---

components/cluster/command/deploy.go
pkg/cluster/manager/deploy.go
pkg/cluster/manager/edit_config.go

Adjust console output
Tests 
Release notes:
```release-note
NONE
```

cluster: refine some outputs

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Bump v1.3.1

---

pkg/repository/clone_mirror.go

Close https://github.com/pingcap/tiup/issues/1059
Check if the component is yanked
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Fix the issue that tiup mirror clone not handle yanked tarball correctly

---

pkg/repository/clone_mirror.go

Close https://github.com/pingcap/tiup/issues/1058

Fix the issue that tiup mirror clone not handle any platform correctly

---

components/cluster/command/check.go
pkg/cluster/api/pdapi.go

Implement task 1 of #1033 
Add a new API to query for region info from PD (`pd-ctl region check`) and check for `miss-peer` and `pending-peer` counts for existing clusters.
Tests 
Release notes:
```release-note
cluster: query region info for existing cluster in `check` subcommand
```

cluster: check region info for existing cluster

---

examples/topology.example.yaml

Update the correspondence between component default port and dir
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Update the correspondence between component default port and dir

---

cmd/mirror.go
pkg/repository/model/error.go
pkg/repository/model/model.go
pkg/repository/v1_repository.go
pkg/repository/v1_repository_test.go
server/handler/component.go

https://github.com/pingcap/tiup/issues/1162
Check the checksum and name for uploaded tarball.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Check tarball checksum on tiup-server

---

cmd/mirror.go
pkg/cluster/operation/upgrade.go
server/handler/component.go

Retry publish if the tarball validation failed on server side
Release notes:
```release-note
NONE
```

mirror: retry publish if tarball is not valid

---

CHANGELOG.md
pkg/cluster/manager/patch.go
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Bump v1.3.3

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Bump v1.3.4

---

.github/workflows/install.yaml
.github/workflows/integrate-cluster-cmd.yaml
.github/workflows/integrate-cluster-scale.yaml
.github/workflows/integrate-dm.yaml
.github/workflows/integrate-playground.yaml
.github/workflows/integrate-tiup.yaml
.github/workflows/release-tiup.yaml
.github/workflows/reprotest.yaml

Ignore paths that don't affect any executable codes for CI workflows. 
Release notes:
```release-note
NONE
```

ci: not running CI jobs if no code has been changed

---

CHANGELOG.md

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Change changelog

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Bump v1.3.5

---

components/ctl/main.go
pkg/exec/run.go
pkg/localdata/constant.go

Fix https://github.com/pingcap/tiup/issues/1209
Fix https://github.com/pingcap/tiup/issues/1190

Add TIUP_USER_INPUT_VERSION to support components that must have a specified version

---

Makefile
cmd/mirror.go
components/bench/main.go
components/bench/tpcc.go
components/cluster/command/check.go
components/dm/spec/cluster.go
components/playground/grafana.go
install.sh
pkg/cluster/ansible/config.go
pkg/cluster/ansible/inventory.go
pkg/cluster/api/pdapi.go
pkg/cluster/audit/audit.go
pkg/cluster/manager/transfer_test.go
pkg/cluster/module/user.go
pkg/cluster/operation/check.go
pkg/cluster/operation/upgrade.go
pkg/cluster/spec/util.go
pkg/cluster/task/builder.go
pkg/cluster/template/config/grafana.go
pkg/crypto/ca_test.go
pkg/repository/merge_mirror_test.go

Signed-off-by: Xiaoguang Sun <sunxiaoguang@zhihu.com>
Make tiup build natively on Apple Silicon M1
Upgrade golangci-lint to versions that support M1 and fix lints with newer version. Also changed a little bit to Makefile in order to build using native arch as default
Tests 
- Unit test
Code changes
- Minor lint changes
- Makefile changes
Side effects
- NA
Release notes:
```release-note
Support Apple Silicon M1
```

Support Apple Silicon

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version to v1.3.6

---

CHANGELOG.md
pkg/version/version.go

Bump v1.3.7

---

components/dm/spec/bindversion.go
components/dm/spec/logic.go
components/dm/spec/topology_dm.go
components/dm/spec/topology_dm_test.go
embed/templates/config/prometheus.yml.tpl
tests/tiup-cluster/topo/full.yaml
tests/tiup-dm/script/task/run.sh
tests/tiup-dm/test_cmd.sh
tests/tiup-dm/topo/full_dm.yaml.tpl
tests/tiup-dm/topo/full_dm_monitored.yaml.tpl

fix #1233 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

dm: support monitored config

---

.github/workflows/integrate-cluster-cmd.yaml
.github/workflows/integrate-cluster-scale.yaml
.github/workflows/integrate-dm.yaml
.github/workflows/integrate-playground.yaml
CHANGELOG.md
pkg/version/version.go

Bump version to 1.4.0
Release notes:
```release-note
NONE
```

Bump v1.4.0

---

components/playground/main.go
embed/templates/scripts/run_cdc.sh.tpl
pkg/cluster/spec/cdc.go
pkg/cluster/template/scripts/cdc.go

implement #1205 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Support config on TiCDC

---

embed/templates/scripts/run_pd.sh.tpl
embed/templates/scripts/run_pd_scale.sh.tpl
embed/templates/scripts/run_tidb.sh.tpl
embed/templates/scripts/run_tikv.sh.tpl
pkg/cluster/spec/pd.go
pkg/cluster/spec/spec.go
pkg/cluster/spec/tidb.go
pkg/cluster/spec/tikv.go
pkg/cluster/template/scripts/pd.go
pkg/cluster/template/scripts/tidb.go
pkg/cluster/template/scripts/tikv.go

Fix https://github.com/pingcap/tiup/issues/1218
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Add advertise addr for TiKV and PD

---

embed/templates/scripts/run_pd_scale.sh.tpl
pkg/cluster/template/scripts/pd.go

Introduced by #1224 
The test can't pass but ci-bot merge that PR by mistake.
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Fix the issue that cluster can't start with TLS

---

pkg/repository/v1_repository.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Fix the issue the playground can't start when there is a nightly in and not in remote

---

CHANGELOG.md
pkg/version/version.go

Bump v1.4.1

---

components/playground/playground.go

Fix #1315
Tests 
- No code
Release notes:
```release-note
playground: update version selection examples
```

playground: update version selection examples

---

pkg/cluster/manager/scale_out.go
pkg/cluster/template/scripts/pd.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Fix issue that advertise address not work with PD non-default ports

---

CHANGELOG.md
pkg/version/version.go

bump version 1.4.2

---

CHANGELOG.md
pkg/version/version.go

Bump v1.5.0
Release notes:
```release-note
NONE
```

bump version 1.5.0

---

tests/tiup-cluster/script/cmd_subtest.sh
tests/tiup-cluster/script/scale_core.sh
tests/tiup-cluster/script/scale_tools.sh
tests/tiup-cluster/script/util.sh

Reduce the warning message of `test_cmd_tls_native_ssh`
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

tests/cluster: --native-ssh is deprecated, use --ssh=system

---

CHANGELOG.md
pkg/version/version.go

bump version 1.5.1

---

components/playground/main.go

Signed-off-by: ekexium <ekexium@gmail.com>
Fix a missing single quote in the help message.
Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

doc: fix a help message of playground

---

pkg/cluster/manager/patch.go
tests/tiup-cluster/test_cmd_tls_native_ssh.sh

cluster/patch: add pkg path in patch error msg
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

tests/tiup-cluster: duplicated version v

---

embed/templates/examples/topology.example.yaml

the original link is 404
Tests 
- No code
Code changes
- N/A
Side effects
- N/A
- N/A
Release notes:
```release-note
NONE
```

docs: update topology.example.yaml

---

CHANGELOG.md
pkg/version/version.go

bump version 1.5.3

---

pkg/cluster/spec/tiflash.go

Fix #1493 
Release notes:
```release-note
NONE
```

cluster: allow editing of lernel_config in tiflash

---

Makefile
components/dm/ansible/import.go

Update linter version
Release notes:
```release-note
NONE
```

*: update linter

---

CHANGELOG.md
pkg/version/version.go

bump v1.5.5
Release notes:
```release-note
NONE
```

bump version 1.5.5

---

tests/tiup-dm/test_cmd.sh

dm changed json name https://github.com/pingcap/dm/commit/8325f1bc473d337e74c2a931e8a8a71c11483234
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix dm test

---

CHANGELOG.md
pkg/version/version.go

Bump v1.5.6
Release notes:
```release-note
NONE
```

bump version 1.5.6

---

cmd/help.go
components/cluster/command/root.go
components/ctl/main.go
components/dm/command/root.go
components/playground/main.go
components/playground/playground_test.go
pkg/exec/run.go
pkg/localdata/constant.go
pkg/tui/cliutil.go
server/package/package.go

it is unnecessary to set TIUP_WORK_DIR
remove it
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

remove TIUP_WORK_DIR

---

CHANGELOG.md
pkg/version/version.go

bump version 1.7.0

---

components/playground/instance/ticdc.go

- playground: add data-dir to ticdc
- close #1614 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: add data-dir to ticdc

---

.github/workflows/release-tiup.yaml
CHANGELOG.md
pkg/version/version.go

bump version 1.8.0

---

CHANGELOG.md
pkg/version/version.go

bump version 1.8.1

---

cmd/root.go

- close #952
- when shell call `tiup __complete cluster xxx`, exec `~/.tiup/component/version/clster __complete xxx`
both tiup and components and component list have shell auto-completion now!
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

*: add initial support for auto-completion for components

---

pkg/cluster/manager/tls.go

cluster:  perfect  the tips of TLS sub commands
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster:  perfect  the tips of TLS sub commands

---

components/playground/playground.go

- fix #1711 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: fix panic when boot monitor

---

pkg/repository/v1_repository.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: fix cannot find nightly version

---

CHANGELOG.md
pkg/version/version.go

bump version 1.8.2

---

pkg/cluster/manager/tls.go

close #1728 
Tests 
Release notes:
```release-note
NONE
```

cluster: fix tls op not check topo Validate

---

components/cluster/command/start.go
pkg/exec/run.go

Close #1708 and update some other prompts

Update error messages and prompts

---

pkg/cluster/spec/alertmanager.go
pkg/cluster/spec/grafana.go
pkg/cluster/spec/monitoring.go
pkg/cluster/spec/tispark.go

- close #1736 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix wrong status when display due to closure

---

embed/templates/systemd/system.service.tpl

- fix #1731
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix ngm cannot be reload

---

pkg/utils/http_client.go

add Download and SetRequestHeader func for http_clinet
add some http operations
Tests 
Release notes:
```release-note
NONE
```

utils: add some http operations

---

pkg/cluster/manager/deploy.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

dm: fix messige at the end of deploy

---

CHANGELOG.md
pkg/version/version.go

bump version 1.9.0

---

pkg/cluster/spec/spec.go

- close #1756
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix ngm nightly not start by default

---

pkg/cluster/ansible/service.go
pkg/cluster/spec/spec.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: change initial_commit_ts to initial-commit-ts

---

pkg/cluster/audit/audit.go
pkg/cluster/audit/audit_test.go
pkg/logger/audit.go

support save audit to soecified fileSuffix
```
logger.OutputAuditLogToFileIfEnabled(resultDir, "diag_audit.log")
```
Tests 
Release notes:
```release-note
NONE
```

*: support save audit to specified file

---

pkg/utils/ioutil.go

- fix #1779 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

utils: support symlink when untar

---

components/cluster/command/audit.go
components/dm/command/audit.go
pkg/cluster/audit/audit.go

support dm/cluster audit logs
Tests 
Release notes:
```release-note
NONE
```

*: support  cleanup audit logs  

---

pkg/cluster/api/pdapi.go

when json.Unmarshal, clusterID was parsed as float64, so it lost precision
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

pdapi: fix loss of precision on GetClusterID()

---

.github/workflows/install.yaml
.github/workflows/integrate-cluster-cmd.yaml
.github/workflows/integrate-cluster-scale.yaml
.github/workflows/integrate-dm.yaml
.github/workflows/integrate-playground.yaml
.github/workflows/integrate-tiup.yaml
.github/workflows/release-tiup.yaml
.github/workflows/reprotest.yaml
Makefile
components/playground/playground.go
go.mod
pkg/cluster/operation/action.go
pkg/cluster/spec/instance.go
pkg/cluster/task/init_config.go

Use go1.18 as the default toolchain

*: bump go 1.18

---

CHANGELOG.md
pkg/version/version.go

bump version 1.9.3

---

components/bench/ch_benchmark.go
components/bench/tpcc.go
components/bench/tpch.go

Fix the typo in the error message of bench command.
s/pleae/please/
Tests 
```bash
make
./bin/tiup-bench tpcc run
```
Code changes
None
Side effects
None
Release notes:
```release-note
NONE
```

bench: fix the typo in the error message of bench command

---

CHANGELOG.md
pkg/version/version.go

bump version 1.9.4

---

embed/examples/cluster/topology.example.yaml
embed/examples/dm/topology.example.yaml

- close #1834 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

examples: update monitoring and grafana example

---

pkg/cluster/manager/destroy.go
pkg/cluster/manager/display.go
pkg/cluster/manager/scale_in.go
pkg/cluster/spec/drainer.go
pkg/cluster/spec/pump.go

close #1861 
close #1860 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: display  pump/drainer server status

---

components/cluster/command/display.go
components/dm/command/display.go
components/dm/spec/logic.go
components/dm/spec/topology_dm.go
components/playground/playground.go
embed/templates/config/prometheus.yml.tpl
pkg/cluster/api/binlog.go
pkg/cluster/manager/display.go
pkg/cluster/operation/destroy.go
pkg/cluster/operation/scale_in.go
pkg/cluster/spec/alertmanager.go
pkg/cluster/spec/cdc.go
pkg/cluster/spec/drainer.go
pkg/cluster/spec/grafana.go
pkg/cluster/spec/instance.go
pkg/cluster/spec/monitoring.go
pkg/cluster/spec/pd.go
pkg/cluster/spec/pump.go
pkg/cluster/spec/spec.go
pkg/cluster/spec/tidb.go
pkg/cluster/spec/tiflash.go
pkg/cluster/spec/tikv.go
pkg/cluster/spec/tispark.go
pkg/cluster/spec/util.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: display support set status-timeout

---

CHANGELOG.md
pkg/version/version.go

bump version 1.9.5

---

CHANGELOG.md

Add PR missed in #1874  to the changelog

adjust changelog

---

components/dm/command/deploy.go
components/dm/command/deploy_test.go
components/playground/instance/ticdc.go
components/playground/instance/tiflash_config.go
components/playground/instance/tiflash_proxy_config.go
pkg/cluster/manager/basic.go
pkg/cluster/spec/cdc.go
pkg/cluster/spec/spec.go
pkg/cluster/spec/spec_test.go
pkg/cluster/spec/tidb.go
pkg/cluster/spec/tiflash.go
pkg/cluster/template/config/prometheus.go
pkg/cluster/template/scripts/cdc.go
pkg/cluster/template/scripts/tikv.go
pkg/tidbver/tidbver.go

close #1870 and other issues about nightly judgment error
- move almost all code about version judgment to a single package "tidbver"
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

add package tidbver

---

CHANGELOG.md
pkg/version/version.go

bump version 1.9.6

---

embed/examples/dm/minimal.yaml
embed/examples/dm/topology.example.yaml

Due to current implement is too complicated to users. We decide to remove dashboard from dm's webui.
So this anonymous configs are useless .
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Revert grafana anonymous config

---

pkg/cluster/operation/check.go

close #1865 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: add kylin Linux  as supported OS 

---

components/dm/command/root.go
pkg/cluster/manager/basic.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster:fix info when restore meta

---

CHANGELOG.md
pkg/version/version.go

bump version 1.10.1

---

pkg/cluster/api/binlog.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix: fix can not get drainer status from pd

---

embed/templates/scripts/run_dm-master.sh.tpl
embed/templates/scripts/run_dm-master_scale.sh.tpl

- fix #1911 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

dm: fix peer-urls of dm-master

---

CHANGELOG.md
pkg/version/version.go

- bump version 1.10.2
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version 1.10.2

---

pkg/cluster/manager/check.go
pkg/cluster/operation/check.go

- close #1905 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix THP check

---

cmd/mirror.go

- close #1980
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

update mirror clone help

---

pkg/cluster/manager/transfer.go

- close #1901
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix cannot push to some instance

---

CHANGELOG.md
pkg/version/version.go

- bump version 1.10.3
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version 1.10.3

---

embed/examples/cluster/topology.example.yaml
embed/templates/scripts/run_tidb-dashboard.sh.tpl
pkg/cluster/ansible/import_test.go
pkg/cluster/ansible/test-data/meta.yaml
pkg/cluster/spec/dashboard.go
pkg/cluster/spec/instance.go
pkg/cluster/spec/spec.go
pkg/cluster/spec/validate.go
pkg/cluster/task/update_meta.go
pkg/cluster/template/scripts/dashboard.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: add tidb dashboard

---

pkg/cluster/operation/check.go
pkg/cluster/operation/systemd.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix service check

---

embed/templates/config/prometheus.yml.tpl

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix prometheus config template

---

components/playground/playground.go

- close #2067 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: fix panic

---

embed/templates/config/datasource.yml.tpl
embed/templates/config/ngmonitoring.toml.tpl
pkg/cluster/spec/grafana.go
pkg/cluster/spec/monitoring.go
pkg/cluster/spec/spec.go
pkg/cluster/template/config/datasource.go
pkg/cluster/template/config/ngmonitoring.go
pkg/cluster/template/scripts/pd.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

modify config template to support ipv6

---

.github/workflows/install.yaml
.github/workflows/integrate-cluster-cmd.yaml
.github/workflows/integrate-cluster-scale.yaml
.github/workflows/integrate-dm.yaml
.github/workflows/integrate-playground.yaml
.github/workflows/integrate-tiup.yaml
.github/workflows/release-tiup.yaml
.github/workflows/reprotest.yaml
tests/tiup-cluster/script/tikv_cdc.sh

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

test: pin github action image

---

pkg/cluster/spec/tiflash.go

#2093 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster:support display tiflash uptime

---

pkg/exec/run.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

improve tiup timeout message

---

pkg/cluster/executor/scp.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

allow download directory when use builtin scp

---

doc/dev/README.md

Document `TIUP_VERBOSE`
Tests 
- No code
Release notes:
```release-note
NONE
```

doc/dev: Add TIUP_VERBOSE

---

embed/examples/cluster/topology.example.yaml

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster:comment out tidb-dashboard in template

---

pkg/cluster/manager/upgrade.go

- close #2104
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster:update upgrade message

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

add v1.11.2 release note

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

add v1.11.3 release note

---

pkg/cluster/executor/scp.go
tools/check/golangci.yaml

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix build-in scp

---

components/cluster/command/import.go
pkg/cluster/executor/local.go
pkg/cluster/executor/ssh.go
pkg/cluster/manager/cacert.go
pkg/cluster/spec/profile.go
pkg/cluster/spec/spec_manager.go
pkg/cluster/task/tls.go
pkg/logger/audit.go
pkg/utils/http_client.go
pkg/utils/ioutil.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

scp: create dir before download

---

pkg/cluster/manager/upgrade.go

Tests 
- Unit test
Release notes:
```release-note
NONE
```

cluster: check upgrade offline

---

embed/templates/config/prometheus.yml.tpl

add ticdc port prob config
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

add ticdc port prob config

---

pkg/crypto/rand/passwd.go

- close #2126 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: delete !#$%&= from init password

---

embed/templates/config/prometheus.yml.tpl
pkg/cluster/spec/monitoring.go
pkg/cluster/template/config/prometheus.go

- close #2095 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: support connect to external Pushgateway

---

components/cluster/command/root.go
components/cluster/command/rotate_ssh.go
components/dm/command/root.go
components/dm/command/rotate_ssh.go
pkg/cluster/manager/rotate_ssh.go
pkg/cluster/task/builder.go
pkg/cluster/task/rotate_ssh.go

- close #2097
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster/dm: support rotate ssh key

---

components/dm/spec/logic.go
components/dm/spec/topology_dm.go
embed/templates/scripts/run_dm-master.sh.tpl
embed/templates/scripts/run_dm-master_scale.sh.tpl
embed/templates/scripts/run_dm-worker.sh.tpl
pkg/cluster/api/dmapi.go
pkg/cluster/operation/upgrade.go
pkg/cluster/template/scripts/dm_master.go
pkg/cluster/template/scripts/dm_worker.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

dm: support ipv6

---

pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix TiUP version

---

components/cluster/command/meta.go

- close #2168 
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: remove : on default backup filename

---

components/playground/instance/tiflash.go
components/playground/instance/tiflash_config.go
components/playground/playground.go
embed/examples/cluster/minimal.yaml
embed/examples/cluster/multi-dc.yaml
embed/examples/cluster/topology.example.yaml
pkg/cluster/ansible/inventory.go
pkg/cluster/ansible/service_test.go
pkg/cluster/ansible/test-data/meta.yaml
pkg/cluster/spec/testdata/topology_err.yaml
pkg/cluster/spec/tiflash.go
pkg/telemetry/testdata/single/nilvalue.yaml
pkg/tidbver/tidbver.go
tools/check/golangci.yaml

remove TiFlash http service
remove `http_port` configuration
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

*: remove TiFlash http service

---

embed/templates/config/ngmonitoring.toml.tpl
pkg/cluster/spec/monitoring.go
pkg/cluster/template/config/ngmonitoring.go

https://github.com/pingcap/tiup/issues/2170
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix ngm config

---

pkg/cluster/manager/exec.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: fix exec

---

.github/workflows/release-tiup.yaml

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

publish nightly package

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version 1.12.2

---

components/dm/spec/topology_dm.go
pkg/cluster/spec/alertmanager.go
pkg/cluster/spec/cdc.go
pkg/cluster/spec/dashboard.go
pkg/cluster/spec/drainer.go
pkg/cluster/spec/grafana.go
pkg/cluster/spec/monitoring.go
pkg/cluster/spec/pd.go
pkg/cluster/spec/pump.go
pkg/cluster/spec/tidb.go
pkg/cluster/spec/tiflash.go
pkg/cluster/spec/tikv.go
pkg/cluster/spec/tikv_cdc.go
pkg/cluster/spec/tispark.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: make manage_host editable

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version to v1.12.3

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version to v1.12.4

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version to v1.12.5

---

components/dm/spec/logic.go
components/dm/spec/topology_dm.go
pkg/cluster/manager/builder.go
pkg/cluster/manager/deploy.go
pkg/cluster/manager/upgrade.go
pkg/cluster/spec/alertmanager.go
pkg/cluster/spec/cdc.go
pkg/cluster/spec/dashboard.go
pkg/cluster/spec/drainer.go
pkg/cluster/spec/instance.go
pkg/cluster/spec/monitoring.go
pkg/cluster/spec/pd.go
pkg/cluster/spec/pump.go
pkg/cluster/spec/server_config.go
pkg/cluster/spec/tidb.go
pkg/cluster/spec/tiflash.go
pkg/cluster/spec/tikv.go
pkg/cluster/spec/tikv_cdc.go
pkg/cluster/task/builder.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

Component source

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version to v1.13.0

---

pkg/repository/mirror.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

mirror: increase publish timeout

---

pkg/repository/mirror.go
pkg/repository/progress.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

mirror: fix progress bar is not accurate

---

OWNERS

Revert "OWNERS: Auto Sync OWNERS files from community membership"

---

pkg/repository/clone_mirror.go

- fix #2336
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

tiup: fix cannot clone without global version

---

components/playground/playground.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: fix default tiproxy version

---

CHANGELOG.md

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump to v1.15.1

---

CHANGELOG.md
pkg/version/version.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump to v1.15.2

---

pkg/exec/run.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

remove test code

---

pkg/cluster/spec/spec.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: make pd mode editable

---

pkg/repository/v1_repository.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix tiup cannot update itself when tiup comonent exist

---

embed/templates/config/grafana.ini.tpl
pkg/cluster/spec/grafana_test.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

fix # cannot be included in grafana password

---

components/playground/main.go
components/playground/playground.go

Close #2473
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: add tiproxy to dsn

---

pkg/telemetry/node_info.go
pkg/telemetry/node_info_generic.go
pkg/telemetry/node_info_loong64.go

Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
Fix build with loong64
```

telemetry: fix loong64 build

---

pkg/cluster/operation/check.go

Tests 
- No code
Release notes:
```release-note
NONE
```

cluster: Fix message for net.core.somaxconn check

---

CHANGELOG.md
pkg/version/version.go

Tests 
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

bump version to v1.16.2

---

components/client/main.go
components/cluster/command/reload.go
components/ctl/main.go
components/dm/command/reload.go
components/playground/playground.go
pkg/cluster/api/typeutil/duration.go
pkg/cluster/module/wait_for.go
pkg/cluster/operation/scale_in.go
pkg/cluster/operation/upgrade.go
pkg/cluster/spec/tiflash.go
pkg/crypto/ca_test.go
pkg/localdata/profile.go
pkg/queue/any_queue.go
pkg/set/any_set.go
pkg/utils/ioutil.go
pkg/utils/semver.go
server/handler/component.go

Run `go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...`
Tests 
Release notes:
```release-note
NONE
```

Run golang.org/x/tools/gopls modernize

---

embed/templates/scripts/run_prometheus.sh.tpl
pkg/cluster/spec/grafana.go
pkg/cluster/spec/grafana_test.go
pkg/cluster/spec/monitoring.go
pkg/cluster/spec/monitoring_test.go
pkg/cluster/template/config/prometheus.go
pkg/cluster/template/config/prometheus_test.go
pkg/cluster/template/scripts/monitoring.go
pkg/cluster/template/scripts/monitoring_test.go

ref https://github.com/pingcap/tiup/issues/2531
cluster: add agent mode for prometheus
Tests 
- Unit test
- No code
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: add agent mode for prometheus

---

go.mod
go.sum
pkg/utils/diff.go

Follow up for https://github.com/pingcap/tiup/commit/85b624234d7fe44394e6c350e318211a901cbcab
This makes it easier to package tiup as debian package, see also #2508 
Tests 
Release notes:
```release-note
NONE
```

Update to github.com/r3labs/diff/v3

---

pkg/set/any_set_test.go
pkg/set/string_set_test.go

ref #2554 
This one was done with help of AI (Copilot)
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

check_to_require: set

---

pkg/meta/err_test.go

ref #2554 
This change was made with AI (Copilot)
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

meta: replace pingcap/check with testing

---

pkg/localdata/profile_test.go

ref #2554
Done using Copilot AI
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

check_to_require: localdata

---

.github/workflows/release-tiup.yaml

close #xxx
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

ci: fix STAGING version competition

---

components/playground/instance/pd_config.go

```
[2025/08/11 12:23:42.791 +08:00] [INFO] [versioninfo.go:109] [PD] [utc-build-time="2025-08-11 03:51:20"]
[2025/08/11 12:23:42.791 +08:00] [WARN] [main.go:223] ["Config contains undefined item: replication.max-replica"]
```
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: fix config typo

---

.github/workflows/integrate-playground.yaml
.github/workflows/integrate-tiup.yaml
.github/workflows/reprotest.yaml

close #xxx
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

ci: add ci for feature branch

---

components/playground/instance/tici.go
components/playground/instance/tiflash.go
components/playground/playground.go

Signed-off-by: Lloyd-Pottiger <yan1579196623@gmail.com>
close #xxx
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

playground: fix --tici.binpath

---

.github/workflows/integrate-cluster-cmd.yaml
docker/control/Dockerfile
pkg/cluster/api/pdapi.go
pkg/cluster/operation/action.go
pkg/cluster/operation/scale_in.go
pkg/cluster/operation/upgrade.go
pkg/cluster/spec/cdc.go
pkg/cluster/spec/instance.go
pkg/cluster/spec/pd.go
pkg/cluster/spec/scheduling.go
pkg/cluster/spec/tikv.go
pkg/cluster/spec/tikv_cdc.go
pkg/cluster/spec/tiproxy.go
pkg/cluster/spec/tso.go
pkg/tidbver/tidbver.go

close #2461
Tests 
Just test any deployment of 8.5.2 and above will work
Code changes
Side effects
Release notes:
```release-note
NONE
```

cluster: support new ready api for PD

---

cmd/mirror.go
cmd/root.go
components/client/main.go
components/cluster/command/root.go
components/dm/command/root.go
components/playground/main.go
pkg/cluster/manager/upgrade.go
pkg/cluster/spec/instance.go
pkg/environment/env.go

close #xxx
Tests 
Code changes
Side effects
Release notes:
```release-note
NONE
```

*: fix unclosed mirror
